In [1]:
seed=197

In [2]:
# importing required libraries
import torch.nn as nn
import torch
import torch.nn.functional as F
import math,copy,re
import warnings
import pandas as pd
import numpy as np
import random
import pickle
import torch.nn.init as init
from torchviz import make_dot
import plotly.graph_objects as go
import pickle
# import seaborn as sns
# import torchtext
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import torch.nn.functional as F
import torch.optim as optim
from IPython.display import display
import matplotlib.pyplot as plt
import os 
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

warnings.simplefilter("ignore")
print(torch.__version__)

1.13.1+cu117


In [3]:
# Check if CUDA is available
if torch.cuda.is_available():
    # CUDA is available, so PyTorch can use a GPU
    device = torch.device("cuda")
    print("PyTorch is using GPU.")
else:
    # CUDA is not available, PyTorch will use CPU
    device = torch.device("cpu")
    print("PyTorch is using CPU.")

# Create a tensor and move it to the device
tensor = torch.randn(3, 4).to(device)

# Check the device of the tensor
print("Tensor device:", tensor.device)

PyTorch is using GPU.
Tensor device: cuda:0


In [4]:
def reset_random_seeds(seed):
    os.environ['PYTHONHASHSEED']=str(seed)
#     tf.random.set_seed(seed)
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

In [74]:
# pickle_file_path = '/media/terminator/Data/NatureData/Auto Ten Minutes.pkl'
pickle_file_path = '/media/terminator/NatureData/Ten Minutes.pkl'

In [75]:
# Load data from the pickle file
with open(pickle_file_path, "rb") as f:
    loaded_data_dict = pickle.load(f)


In [76]:
# Retrieve data and labels
X_train = loaded_data_dict["X_train"]
y_train = loaded_data_dict["y_train"]
X_test = loaded_data_dict["X_test"]
y_test = loaded_data_dict["y_test"]

In [77]:
X_train.shape,y_train.shape

(torch.Size([23328, 144, 13]), torch.Size([23328, 3]))

In [78]:
features=13

In [79]:
def reconstructData(packets):
    # Take the first packet
    first_packet = packets[0]
    
    # Concatenate the last index of every packet
    reconstructed_data = np.concatenate([packet[-1:] for packet in packets[1:]])
    
    # Combine the first packet with the concatenated data
    reconstructed_data = np.concatenate([first_packet, reconstructed_data])
    
    return reconstructed_data

In [100]:
Valid,Test = X_test[:100000],X_test[100000:]
Valid_label,Test_label = y_test[:100000],y_test[100000:]

In [101]:
num_epochs = 500
# Define batch size
batch_size = 256
# Create DataLoader for training set
train_dataset = torch.utils.data.TensorDataset(X_train.float(), y_train.float())
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
valid_dataset = torch.utils.data.TensorDataset(Valid.float(), Valid_label.float())
valid_loader = torch.utils.data.DataLoader(valid_dataset, batch_size=batch_size, shuffle=False)
test_dataset = torch.utils.data.TensorDataset(Test.float(), Test_label.float())
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [102]:
print(X_train.dtype)
print(y_train.dtype)

torch.float64
torch.float64


In [103]:
X_train.shape, y_train.shape

(torch.Size([23328, 144, 13]), torch.Size([23328, 3]))

In [129]:
import torch
import torch.nn as nn

class TimeSeriesEncoder(nn.Module):
    def __init__(self, input_channels):
        super(TimeSeriesEncoder, self).__init__()
        
        self.encoder = nn.Sequential(
            nn.Conv1d(input_channels, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2, stride=1),  # Reduce sequence length to 36 / 4 = 9
            nn.Conv1d(128, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2, stride=1)  # Reduce sequence length to 9 / 2 = 4.5 (rounded to 4)
        )
        self.classifier = nn.Sequential(
            nn.Linear(64*142, 1024),
            nn.ReLU(), 
            nn.Linear(1024, 3), 
            nn.Softmax(dim=1)  
        )
        
    
    def forward(self, x):
        x = x.permute(0,2,1)
        x = self.encoder(x)
#         print(x.shape)
        x = torch.reshape(x,(x.shape[0],-1))
        x = self.classifier(x)
#         x = x.permute(0,2,1)
        return x

# Create the autoencoder model
input_channels = 13  # Number of input features
# encoder = TimeSeriesEncoder(input_channels).to(device)





In [130]:
train = 1
avg = 'weighted'
seq_length = 144
num_epochs = 5000
reset_random_seeds(seed)
src_vocab_size = features+5
target_vocab_size = features
num_layers = 2
latent_dim = 8
embed_dim = 128
n_heads = 8
expansion_factor = 2

Cf = TimeSeriesEncoder(input_channels).to(device)

criterion = nn.CrossEntropyLoss()
optimizer_cf = optim.Adam(Cf.parameters(), lr=0.00001)

# Define early stopping parameters
patience = 100
best_loss = 0
epochs_without_improvement = 0

if train:
    # Step 4: Training loop
    for epoch in range(num_epochs):
        running_loss = 0.0
        latents = []
        PR, PL = [], []
        train_input,train_output = [], []

        # Iterate over mini-batches
        for i, (inputs, labels) in enumerate(train_loader):
            
            probability = 0.0
            coin_toss = random.random()  

            if coin_toss < probability:
                continue
            
            # Clear gradients
            optimizer_cf.zero_grad()
            inputs = inputs.to(device)
            labels = labels.to(device)
            
            # Forward pass
            
            prediction = Cf(inputs)
            
            
            # Calculate loss
            loss = criterion(prediction, labels)
            loss = loss.float()

            # Backpropagation
            loss.backward()
            
            optimizer_cf.step()
            
            # Update running loss
            running_loss += loss.item()
            
            
            PR.append(prediction)
            PL.append(labels)
            

        # Calculate average loss per epoch
        PR = torch.cat(PR, dim=0)
        PL = torch.cat(PL, dim=0)
        _, predicted = torch.max(PR.data, 1)
        _, lbl = torch.max(PL.data, 1)
        total = lbl.size(0)
        correct = (predicted == lbl).sum().item()

        accuracy = 100 * correct / total
        print(f'Train Accuracy: {accuracy:.2f}%')
        conf_matrix = confusion_matrix(lbl.cpu().detach().numpy(),predicted.cpu().detach().numpy())
        print('Confusion Matrix:')
        print(conf_matrix)
        # Calculate average loss per epoch
        epoch_loss = running_loss / len(train_loader)
        print(f"Epoch: {epoch+1}, Train Loss: {round(epoch_loss,6)}")
        
        if epoch%1==0:
            valid_latents = []
            VR,VL = [], []
            valid_loss = 0.0
            for j, (inp, lab) in enumerate(valid_loader):
                probability = 0.0
                coin_toss = random.random()  

                if coin_toss < probability:
                    continue
                inp = inp.to(device)
                lab = lab.to(device)
                
                with torch.no_grad():
                    # Forward pass
                    outp = Cf(inp)
                    
                VR.append(outp)
                VL.append(lab)
            
            VR = torch.cat(VR, dim=0)
            VL = torch.cat(VL, dim=0)
            _, vpre = torch.max(VR.data, 1)
            _, vlbl = torch.max(VL.data, 1)
            total = vlbl.size(0)
            correct = (vpre == vlbl).sum().item()

            vaccuracy = 100 * correct / total
            print('-----------------------------------------')
            print(f'Valid Accuracy: {vaccuracy:.2f}%')
            lb = vlbl.cpu().detach().numpy()
            pre = vpre.cpu().detach().numpy()
            conf_matrix = confusion_matrix(lb,pre)
            precision = precision_score(lb, pre,average=avg)
            recall = recall_score(lb, pre,average=avg)
            f1 = f1_score(lb, pre,average=avg)
            print('Confusion Matrix:')
            print(conf_matrix)
            print()
            print("Precision:", precision)
            print("Recall:", recall)
            print("F1 Score:", f1)
            print(epochs_without_improvement, best_loss)
            print('-----------------------------------------')
            print()
            print()
            
                
                    
        # Check for early stopping and save the best weights
        th = (conf_matrix[0][0]> conf_matrix[0][1]+conf_matrix[0][2] and conf_matrix[1][1]>conf_matrix[1][0]+conf_matrix[1][2] and conf_matrix[2][2]>conf_matrix[2][0]+conf_matrix[2][1])
        if th and vaccuracy > best_loss:
            best_loss = vaccuracy
            epochs_without_improvement = 0
            # Save the model weights
            torch.save(Cf.state_dict(), 'cnn10.pt')
            print('##############################################')
            print('saved', best_loss)
            print('##############################################')
            print()
            print()
            
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                print("Early stopping triggered. Training stopped.")
                break

# Recover the best weights
Cf.load_state_dict(torch.load('cnn10.pt'))


Train Accuracy: 48.23%
Confusion Matrix:
[[4159    0 3617]
 [2044    0 5732]
 [ 684    0 7092]]
Epoch: 1, Train Loss: 1.079045
-----------------------------------------
Valid Accuracy: 51.80%
Confusion Matrix:
[[51054     0 45428]
 [  665     0  2084]
 [   26     0   743]]

Precision: 0.9520542503837298
Recall: 0.51797
F1 Score: 0.6648612722841476
0 0
-----------------------------------------


Train Accuracy: 51.01%
Confusion Matrix:
[[4375    1 3400]
 [1875    2 5899]
 [ 253    0 7523]]
Epoch: 2, Train Loss: 1.022987
-----------------------------------------
Valid Accuracy: 52.24%
Confusion Matrix:
[[51500   114 44868]
 [  683     2  2064]
 [   26     0   743]]

Precision: 0.952311523273576
Recall: 0.52245
F1 Score: 0.6686164004181419
1 0
-----------------------------------------


Train Accuracy: 53.85%
Confusion Matrix:
[[4374  256 3146]
 [1863  667 5246]
 [ 254    0 7522]]
Epoch: 3, Train Loss: 0.987147
-----------------------------------------
Valid Accuracy: 52.96%
Confusion Mat

Train Accuracy: 74.43%
Confusion Matrix:
[[5302 2084  390]
 [2400 4769  607]
 [ 144  339 7293]]
Epoch: 18, Train Loss: 0.801649
-----------------------------------------
Valid Accuracy: 68.53%
Confusion Matrix:
[[66133 27367  2982]
 [  894  1707   148]
 [   23    51   695]]

Precision: 0.9546332149887353
Recall: 0.68535
F1 Score: 0.7856253797742774
0 67.561
-----------------------------------------


##############################################
saved 68.535
##############################################


Train Accuracy: 75.03%
Confusion Matrix:
[[5319 2079  378]
 [2316 4884  576]
 [ 144  331 7301]]
Epoch: 19, Train Loss: 0.797297
-----------------------------------------
Valid Accuracy: 68.93%
Confusion Matrix:
[[66523 27059  2900]
 [  891  1710   148]
 [   23    51   695]]

Precision: 0.9548023824666524
Recall: 0.68928
F1 Score: 0.7884500276971039
0 68.535
-----------------------------------------


##############################################
saved 68.928
#######################

Train Accuracy: 79.44%
Confusion Matrix:
[[5465 1994  317]
 [1585 5747  444]
 [ 283  174 7319]]
Epoch: 34, Train Loss: 0.763331
-----------------------------------------
Valid Accuracy: 70.88%
Confusion Matrix:
[[68229 25862  2391]
 [  681  1941   127]
 [   32    31   706]]

Precision: 0.9584427935019116
Recall: 0.70876
F1 Score: 0.802087239813304
0 70.884
-----------------------------------------


Train Accuracy: 79.58%
Confusion Matrix:
[[5476 1987  313]
 [1565 5768  443]
 [ 285  171 7320]]
Epoch: 35, Train Loss: 0.762106
-----------------------------------------
Valid Accuracy: 70.99%
Confusion Matrix:
[[68343 25803  2336]
 [  678  1944   127]
 [   32    34   703]]

Precision: 0.9585309384221041
Recall: 0.7099
F1 Score: 0.8029222742035186
1 70.884
-----------------------------------------


##############################################
saved 70.99
##############################################


Train Accuracy: 79.63%
Confusion Matrix:
[[5478 1986  312]
 [1558 5777  441]
 [ 285  1

Train Accuracy: 80.92%
Confusion Matrix:
[[5527 1976  273]
 [1375 6019  382]
 [ 292  154 7330]]
Epoch: 51, Train Loss: 0.748155
-----------------------------------------
Valid Accuracy: 71.78%
Confusion Matrix:
[[69105 25401  1976]
 [  620  2005   124]
 [   44    59   666]]

Precision: 0.9594961217810268
Recall: 0.71776
F1 Score: 0.8086331272856481
0 71.751
-----------------------------------------


##############################################
saved 71.776
##############################################


Train Accuracy: 80.99%
Confusion Matrix:
[[5529 1976  271]
 [1370 6035  371]
 [ 293  153 7330]]
Epoch: 52, Train Loss: 0.747469
-----------------------------------------
Valid Accuracy: 71.83%
Confusion Matrix:
[[69154 25364  1964]
 [  620  2005   124]
 [   44    52   673]]

Precision: 0.9595286360246456
Recall: 0.71832
F1 Score: 0.8090052825628353
0 71.776
-----------------------------------------


##############################################
saved 71.832
#######################

Train Accuracy: 81.61%
Confusion Matrix:
[[5643 1872  261]
 [1360 6066  350]
 [ 352   94 7330]]
Epoch: 67, Train Loss: 0.739211
-----------------------------------------
Valid Accuracy: 72.61%
Confusion Matrix:
[[69872 24615  1995]
 [  594  2033   122]
 [   51    14   704]]

Precision: 0.960010279625174
Recall: 0.72609
F1 Score: 0.8141734153436315
0 72.556
-----------------------------------------


##############################################
saved 72.609
##############################################


Train Accuracy: 81.66%
Confusion Matrix:
[[5647 1868  261]
 [1353 6073  350]
 [ 369   77 7330]]
Epoch: 68, Train Loss: 0.738744
-----------------------------------------
Valid Accuracy: 72.66%
Confusion Matrix:
[[69922 24565  1995]
 [  594  2033   122]
 [   51    14   704]]

Precision: 0.9600204708395123
Recall: 0.72659
F1 Score: 0.8145158015614913
0 72.609
-----------------------------------------


##############################################
saved 72.659
########################

Train Accuracy: 82.44%
Confusion Matrix:
[[5729 1809  238]
 [1257 6172  347]
 [ 379   67 7330]]
Epoch: 84, Train Loss: 0.731499
-----------------------------------------
Valid Accuracy: 73.02%
Confusion Matrix:
[[70226 24246  2010]
 [  548  2079   122]
 [   49    10   710]]

Precision: 0.9607784114021204
Recall: 0.73015
F1 Score: 0.8169173837860615
1 73.015
-----------------------------------------


Train Accuracy: 82.48%
Confusion Matrix:
[[5733 1808  235]
 [1253 6178  345]
 [ 381   65 7330]]
Epoch: 85, Train Loss: 0.731063
-----------------------------------------
Valid Accuracy: 73.00%
Confusion Matrix:
[[70215 24270  1997]
 [  548  2079   122]
 [   49    10   710]]

Precision: 0.9607840002439789
Recall: 0.73004
F1 Score: 0.8168514479972193
2 73.015
-----------------------------------------


Train Accuracy: 82.57%
Confusion Matrix:
[[5737 1805  234]
 [1242 6195  339]
 [ 381   65 7330]]
Epoch: 86, Train Loss: 0.730629
-----------------------------------------
Valid Accuracy: 73.01%

-----------------------------------------
Valid Accuracy: 72.36%
Confusion Matrix:
[[69480 25018  1984]
 [  458  2169   122]
 [   48    14   707]]

Precision: 0.9619691308698101
Recall: 0.72356
F1 Score: 0.8124056755664613
15 73.032
-----------------------------------------


Train Accuracy: 83.55%
Confusion Matrix:
[[5816 1729  231]
 [1101 6341  334]
 [ 393   49 7334]]
Epoch: 105, Train Loss: 0.722262
-----------------------------------------
Valid Accuracy: 72.42%
Confusion Matrix:
[[69548 24961  1973]
 [  458  2167   124]
 [   48    14   707]]

Precision: 0.961984844881085
Recall: 0.72422
F1 Score: 0.8128765570998135
16 73.032
-----------------------------------------


Train Accuracy: 83.59%
Confusion Matrix:
[[5822 1723  231]
 [1101 6343  332]
 [ 393   49 7334]]
Epoch: 106, Train Loss: 0.7219
-----------------------------------------
Valid Accuracy: 72.49%
Confusion Matrix:
[[69614 24891  1977]
 [  458  2167   124]
 [   48    14   707]]

Precision: 0.9619943173113891
Recall: 0.724

Train Accuracy: 83.92%
Confusion Matrix:
[[5897 1648  231]
 [1099 6346  331]
 [ 392   49 7335]]
Epoch: 122, Train Loss: 0.717063
-----------------------------------------
Valid Accuracy: 74.00%
Confusion Matrix:
[[71130 23384  1968]
 [  460  2165   124]
 [   49    13   707]]

Precision: 0.9622356005133539
Recall: 0.74002
F1 Score: 0.8236597682235992
0 73.92
-----------------------------------------


##############################################
saved 74.002
##############################################


Train Accuracy: 83.96%
Confusion Matrix:
[[5905 1641  230]
 [1098 6347  331]
 [ 392   49 7335]]
Epoch: 123, Train Loss: 0.716797
-----------------------------------------
Valid Accuracy: 74.08%
Confusion Matrix:
[[71213 23300  1969]
 [  460  2165   124]
 [   49    13   707]]

Precision: 0.9622505161406189
Recall: 0.74085
F1 Score: 0.824220748882717
0 74.002
-----------------------------------------


##############################################
saved 74.085
#######################

Train Accuracy: 84.31%
Confusion Matrix:
[[5970 1584  222]
 [1082 6363  331]
 [ 392   49 7335]]
Epoch: 138, Train Loss: 0.712854
-----------------------------------------
Valid Accuracy: 75.04%
Confusion Matrix:
[[72176 22363  1943]
 [  471  2165   113]
 [   54    12   703]]

Precision: 0.9622373783982371
Recall: 0.75044
F1 Score: 0.8306398639590868
0 74.991
-----------------------------------------


##############################################
saved 75.044
##############################################


Train Accuracy: 84.34%
Confusion Matrix:
[[5976 1581  219]
 [1080 6365  331]
 [ 392   49 7335]]
Epoch: 139, Train Loss: 0.712585
-----------------------------------------
Valid Accuracy: 75.08%
Confusion Matrix:
[[72208 22337  1937]
 [  471  2165   113]
 [   54    12   703]]

Precision: 0.9622472865113311
Recall: 0.75076
F1 Score: 0.8308584794025079
0 75.044
-----------------------------------------


##############################################
saved 75.076
#####################

-----------------------------------------
Valid Accuracy: 75.65%
Confusion Matrix:
[[72782 21870  1830]
 [  467  2169   113]
 [   53    13   703]]

Precision: 0.96249777253333
Recall: 0.75654
F1 Score: 0.8348022462387089
0 75.621
-----------------------------------------


##############################################
saved 75.654
##############################################


Train Accuracy: 84.75%
Confusion Matrix:
[[6058 1506  212]
 [1090 6378  308]
 [ 375   66 7335]]
Epoch: 155, Train Loss: 0.70828
-----------------------------------------
Valid Accuracy: 75.71%
Confusion Matrix:
[[72842 21813  1827]
 [  467  2169   113]
 [   53    13   703]]

Precision: 0.9625115783104871
Recall: 0.75714
F1 Score: 0.8352039719249282
0 75.654
-----------------------------------------


##############################################
saved 75.714
##############################################


Train Accuracy: 84.77%
Confusion Matrix:
[[6060 1504  212]
 [1088 6380  308]
 [ 372   69 7335]]
Epoch: 1

-----------------------------------------
Valid Accuracy: 76.38%
Confusion Matrix:
[[73507 21203  1772]
 [  457  2179   113]
 [   53    20   696]]

Precision: 0.9628054405811276
Recall: 0.76382
F1 Score: 0.8396995545817083
0 76.317
-----------------------------------------


##############################################
saved 76.382
##############################################


Train Accuracy: 85.11%
Confusion Matrix:
[[6125 1449  202]
 [1077 6395  304]
 [ 373   68 7335]]
Epoch: 171, Train Loss: 0.704415
-----------------------------------------
Valid Accuracy: 76.40%
Confusion Matrix:
[[73529 21183  1770]
 [  457  2179   113]
 [   53    20   696]]

Precision: 0.9628112135050989
Recall: 0.76404
F1 Score: 0.839846593145446
0 76.382
-----------------------------------------


##############################################
saved 76.404
##############################################


Train Accuracy: 85.11%
Confusion Matrix:
[[6125 1449  202]
 [1077 6395  304]
 [ 373   68 7335]]
Epoch:

-----------------------------------------
Valid Accuracy: 77.16%
Confusion Matrix:
[[74303 20472  1707]
 [  451  2185   113]
 [   70    32   667]]

Precision: 0.9628117153455119
Recall: 0.77155
F1 Score: 0.8448434853996851
0 77.075
-----------------------------------------


##############################################
saved 77.155
##############################################


Train Accuracy: 85.46%
Confusion Matrix:
[[6194 1381  201]
 [1064 6407  305]
 [ 362   79 7335]]
Epoch: 187, Train Loss: 0.700915
-----------------------------------------
Valid Accuracy: 77.17%
Confusion Matrix:
[[74321 20465  1696]
 [  451  2185   113]
 [   70    32   667]]

Precision: 0.9628233106849055
Recall: 0.77173
F1 Score: 0.8449702657466871
0 77.155
-----------------------------------------


##############################################
saved 77.173
##############################################


Train Accuracy: 85.48%
Confusion Matrix:
[[6198 1377  201]
 [1063 6408  305]
 [ 362   79 7335]]
Epoch

-----------------------------------------
Valid Accuracy: 77.82%
Confusion Matrix:
[[74987 19778  1717]
 [  463  2176   110]
 [   79    29   661]]

Precision: 0.9626605581041224
Recall: 0.77824
F1 Score: 0.8491717950324525
0 77.778
-----------------------------------------


##############################################
saved 77.824
##############################################


Train Accuracy: 85.80%
Confusion Matrix:
[[6264 1317  195]
 [1053 6417  306]
 [ 360   81 7335]]
Epoch: 203, Train Loss: 0.697739
-----------------------------------------
Valid Accuracy: 77.91%
Confusion Matrix:
[[75058 19704  1720]
 [  463  2176   110]
 [   79    18   672]]

Precision: 0.9626999998492146
Recall: 0.77906
F1 Score: 0.8496759176129709
0 77.824
-----------------------------------------


##############################################
saved 77.906
##############################################


Train Accuracy: 85.82%
Confusion Matrix:
[[6268 1313  195]
 [1052 6417  307]
 [ 360   81 7335]]
Epoch

-----------------------------------------
Valid Accuracy: 78.69%
Confusion Matrix:
[[75830 18973  1679]
 [  453  2187   109]
 [   85     9   675]]

Precision: 0.962970524295704
Recall: 0.78692
F1 Score: 0.8547802650234507
0 78.65
-----------------------------------------


##############################################
saved 78.692
##############################################


Train Accuracy: 86.11%
Confusion Matrix:
[[6328 1257  191]
 [1041 6424  311]
 [ 363   78 7335]]
Epoch: 219, Train Loss: 0.694984
-----------------------------------------
Valid Accuracy: 78.74%
Confusion Matrix:
[[75877 18926  1679]
 [  453  2187   109]
 [   85     9   675]]

Precision: 0.9629810244220868
Recall: 0.78739
F1 Score: 0.8550845908573858
0 78.692
-----------------------------------------


##############################################
saved 78.739
##############################################


Train Accuracy: 86.13%
Confusion Matrix:
[[6334 1252  190]
 [1042 6424  310]
 [ 363   78 7335]]
Epoch: 

-----------------------------------------
Valid Accuracy: 79.51%
Confusion Matrix:
[[76679 18145  1658]
 [  464  2176   109]
 [  109     9   651]]

Precision: 0.962676403971181
Recall: 0.79506
F1 Score: 0.8599886768554715
0 79.445
-----------------------------------------


##############################################
saved 79.506
##############################################


Train Accuracy: 86.32%
Confusion Matrix:
[[6378 1212  186]
 [1039 6424  313]
 [ 364   77 7335]]
Epoch: 235, Train Loss: 0.692377
-----------------------------------------
Valid Accuracy: 79.61%
Confusion Matrix:
[[76784 18040  1658]
 [  469  2171   109]
 [  109     9   651]]

Precision: 0.962633431188382
Recall: 0.79606
F1 Score: 0.8606281258988081
0 79.506
-----------------------------------------


##############################################
saved 79.606
##############################################


Train Accuracy: 86.33%
Confusion Matrix:
[[6379 1212  185]
 [1039 6424  313]
 [ 364   77 7335]]
Epoch: 

-----------------------------------------
Valid Accuracy: 80.50%
Confusion Matrix:
[[77738 17156  1588]
 [  500  2154    95]
 [  139    21   609]]

Precision: 0.9620603372944427
Recall: 0.80501
F1 Score: 0.8662938255897241
0 80.431
-----------------------------------------


##############################################
saved 80.501
##############################################


Train Accuracy: 86.51%
Confusion Matrix:
[[6421 1176  179]
 [1045 6425  306]
 [ 352   89 7335]]
Epoch: 251, Train Loss: 0.689677
-----------------------------------------
Valid Accuracy: 80.59%
Confusion Matrix:
[[77832 17078  1572]
 [  500  2154    95]
 [  139    21   609]]

Precision: 0.9620965338078887
Recall: 0.80595
F1 Score: 0.8669047665069909
0 80.501
-----------------------------------------


##############################################
saved 80.595
##############################################


Train Accuracy: 86.53%
Confusion Matrix:
[[6425 1172  179]
 [1045 6425  306]
 [ 352   89 7335]]
Epoch

-----------------------------------------
Valid Accuracy: 81.71%
Confusion Matrix:
[[78973 16016  1493]
 [  523  2133    93]
 [  144    22   603]]

Precision: 0.9620847109847078
Recall: 0.81709
F1 Score: 0.8739904540067427
0 81.671
-----------------------------------------


##############################################
saved 81.709
##############################################


Train Accuracy: 86.77%
Confusion Matrix:
[[6468 1132  176]
 [1035 6438  303]
 [ 347   94 7335]]
Epoch: 267, Train Loss: 0.686733
-----------------------------------------
Valid Accuracy: 81.74%
Confusion Matrix:
[[79007 15982  1493]
 [  523  2133    93]
 [  144    22   603]]

Precision: 0.9620942085017506
Recall: 0.81743
F1 Score: 0.8742050183378358
0 81.709
-----------------------------------------


##############################################
saved 81.743
##############################################


Train Accuracy: 86.82%
Confusion Matrix:
[[6480 1120  176]
 [1035 6438  303]
 [ 346   95 7335]]
Epoch

Train Accuracy: 87.23%
Confusion Matrix:
[[6533 1081  162]
 [1024 6481  271]
 [ 342   99 7335]]
Epoch: 284, Train Loss: 0.682878
-----------------------------------------
Valid Accuracy: 82.05%
Confusion Matrix:
[[79273 15742  1467]
 [  501  2161    87]
 [  122    28   619]]

Precision: 0.9628002817384571
Recall: 0.82053
F1 Score: 0.8762569096045408
0 82.015
-----------------------------------------


##############################################
saved 82.053
##############################################


Train Accuracy: 87.24%
Confusion Matrix:
[[6534 1080  162]
 [1022 6483  271]
 [ 340  101 7335]]
Epoch: 285, Train Loss: 0.68267
-----------------------------------------
Valid Accuracy: 82.09%
Confusion Matrix:
[[79309 15703  1470]
 [  501  2161    87]
 [  119    28   622]]

Precision: 0.9628513778718107
Recall: 0.82092
F1 Score: 0.8765083743130071
0 82.053
-----------------------------------------


##############################################
saved 82.092
######################

-----------------------------------------
Valid Accuracy: 82.59%
Confusion Matrix:
[[79792 15191  1499]
 [  480  2182    87]
 [  140    17   612]]

Precision: 0.9629714123182509
Recall: 0.82586
F1 Score: 0.8795366676637548
0 82.585
-----------------------------------------


##############################################
saved 82.586
##############################################


Train Accuracy: 87.53%
Confusion Matrix:
[[6600 1015  161]
 [1027 6483  266]
 [ 339  102 7335]]
Epoch: 301, Train Loss: 0.679754
-----------------------------------------
Valid Accuracy: 82.62%
Confusion Matrix:
[[79824 15152  1506]
 [  483  2179    87]
 [  140    14   615]]

Precision: 0.9629436143522689
Recall: 0.82618
F1 Score: 0.8797234599623639
0 82.586
-----------------------------------------


##############################################
saved 82.618
##############################################


Train Accuracy: 87.54%
Confusion Matrix:
[[6604 1010  162]
 [1027 6483  266]
 [ 339  102 7335]]
Epoch

-----------------------------------------
Valid Accuracy: 83.36%
Confusion Matrix:
[[80571 14397  1514]
 [  486  2176    87]
 [  146    14   609]]

Precision: 0.9630362731964563
Recall: 0.83356
F1 Score: 0.884323788557238
0 83.302
-----------------------------------------


##############################################
saved 83.356
##############################################


Train Accuracy: 87.76%
Confusion Matrix:
[[6653  966  157]
 [1026 6484  266]
 [ 327  114 7335]]
Epoch: 317, Train Loss: 0.676966
-----------------------------------------
Valid Accuracy: 83.34%
Confusion Matrix:
[[80554 14416  1512]
 [  486  2176    87]
 [  146    14   609]]

Precision: 0.9630324940462566
Recall: 0.83339
F1 Score: 0.8842189141032208
0 83.356
-----------------------------------------


Train Accuracy: 87.77%
Confusion Matrix:
[[6656  963  157]
 [1025 6485  266]
 [ 325  116 7335]]
Epoch: 318, Train Loss: 0.67674
-----------------------------------------
Valid Accuracy: 83.35%
Confusion Matrix:


Train Accuracy: 88.11%
Confusion Matrix:
[[6721  897  158]
 [1023 6498  255]
 [ 335  106 7335]]
Epoch: 333, Train Loss: 0.673625
-----------------------------------------
Valid Accuracy: 84.34%
Confusion Matrix:
[[81563 13391  1528]
 [  504  2161    84]
 [  143    11   615]]

Precision: 0.9631675459025786
Recall: 0.84339
F1 Score: 0.8904190764608514
0 84.281
-----------------------------------------


##############################################
saved 84.339
##############################################


Train Accuracy: 88.13%
Confusion Matrix:
[[6725  893  158]
 [1023 6498  255]
 [ 336  105 7335]]
Epoch: 334, Train Loss: 0.673453
-----------------------------------------
Valid Accuracy: 84.45%
Confusion Matrix:
[[81669 13286  1527]
 [  501  2164    84]
 [  143    11   615]]

Precision: 0.9632436821069643
Recall: 0.84448
F1 Score: 0.89110213763595
0 84.339
-----------------------------------------


##############################################
saved 84.448
#######################

-----------------------------------------
Valid Accuracy: 85.14%
Confusion Matrix:
[[82377 12611  1494]
 [  510  2152    87]
 [  150    11   608]]

Precision: 0.9632915008959749
Recall: 0.85137
F1 Score: 0.8953792737655605
0 85.113
-----------------------------------------


##############################################
saved 85.137
##############################################


Train Accuracy: 88.38%
Confusion Matrix:
[[6784  840  152]
 [1015 6498  263]
 [ 337  104 7335]]
Epoch: 350, Train Loss: 0.670761
-----------------------------------------
Valid Accuracy: 85.14%
Confusion Matrix:
[[82381 12607  1494]
 [  510  2152    87]
 [  150    11   608]]

Precision: 0.9632929547089352
Recall: 0.85141
F1 Score: 0.8954040809500995
0 85.137
-----------------------------------------


##############################################
saved 85.141
##############################################


Train Accuracy: 88.39%
Confusion Matrix:
[[6786  839  151]
 [1015 6498  263]
 [ 336  105 7335]]
Epoch

-----------------------------------------
Valid Accuracy: 85.60%
Confusion Matrix:
[[82825 12184  1473]
 [  496  2166    87]
 [  149    14   606]]

Precision: 0.9636613334920863
Recall: 0.85597
F1 Score: 0.8982736495559609
0 85.555
-----------------------------------------


##############################################
saved 85.597
##############################################


Train Accuracy: 88.61%
Confusion Matrix:
[[6838  790  148]
 [1022 6498  256]
 [ 324  117 7335]]
Epoch: 366, Train Loss: 0.668166
-----------------------------------------
Valid Accuracy: 85.65%
Confusion Matrix:
[[82869 12140  1473]
 [  490  2172    87]
 [  149    14   606]]

Precision: 0.9637565566910791
Recall: 0.85647
F1 Score: 0.8985926652706742
0 85.597
-----------------------------------------


##############################################
saved 85.647
##############################################


Train Accuracy: 88.63%
Confusion Matrix:
[[6842  787  147]
 [1023 6498  255]
 [ 322  119 7335]]
Epoch

-----------------------------------------
Valid Accuracy: 86.72%
Confusion Matrix:
[[83905 11119  1458]
 [  462  2200    87]
 [  140    18   611]]

Precision: 0.9646608523796966
Recall: 0.86716
F1 Score: 0.9052971519648205
0 86.691
-----------------------------------------


##############################################
saved 86.716
##############################################


Train Accuracy: 89.04%
Confusion Matrix:
[[6914  717  145]
 [1013 6523  240]
 [ 334  107 7335]]
Epoch: 382, Train Loss: 0.664475
-----------------------------------------
Valid Accuracy: 86.80%
Confusion Matrix:
[[83987 11048  1447]
 [  462  2200    87]
 [  140    18   611]]

Precision: 0.9647029603408015
Recall: 0.86798
F1 Score: 0.9058113604383987
0 86.716
-----------------------------------------


##############################################
saved 86.798
##############################################


Train Accuracy: 89.06%
Confusion Matrix:
[[6917  714  145]
 [1014 6523  239]
 [ 336  105 7335]]
Epoch

-----------------------------------------
Valid Accuracy: 87.33%
Confusion Matrix:
[[84527 10493  1462]
 [  448  2214    87]
 [  148    27   594]]

Precision: 0.9649757659342751
Recall: 0.87335
F1 Score: 0.9091389719328827
0 87.331
-----------------------------------------


##############################################
saved 87.335
##############################################


Train Accuracy: 89.31%
Confusion Matrix:
[[6964  670  142]
 [1002 6535  239]
 [ 356   85 7335]]
Epoch: 398, Train Loss: 0.661323
-----------------------------------------
Valid Accuracy: 87.38%
Confusion Matrix:
[[84568 10459  1455]
 [  448  2214    87]
 [  148    27   594]]

Precision: 0.9649987991039206
Recall: 0.87376
F1 Score: 0.9093966577654718
0 87.335
-----------------------------------------


##############################################
saved 87.376
##############################################


Train Accuracy: 89.33%
Confusion Matrix:
[[6968  666  142]
 [1003 6535  238]
 [ 355   86 7335]]
Epoch

Train Accuracy: 89.68%
Confusion Matrix:
[[7017  622  137]
 [ 966 6569  241]
 [ 349   92 7335]]
Epoch: 415, Train Loss: 0.657708
-----------------------------------------
Valid Accuracy: 87.45%
Confusion Matrix:
[[84584 10470  1428]
 [  388  2274    87]
 [  147    33   589]]

Precision: 0.9658011223337853
Recall: 0.87447
F1 Score: 0.9099709366401041
5 87.737
-----------------------------------------


Train Accuracy: 89.72%
Confusion Matrix:
[[7025  614  137]
 [ 965 6570  241]
 [ 347   94 7335]]
Epoch: 416, Train Loss: 0.657486
-----------------------------------------
Valid Accuracy: 87.54%
Confusion Matrix:
[[84681 10380  1421]
 [  388  2274    87]
 [  147    39   583]]

Precision: 0.9658317211931405
Recall: 0.87538
F1 Score: 0.910547142323388
6 87.737
-----------------------------------------


Train Accuracy: 89.73%
Confusion Matrix:
[[7028  611  137]
 [ 966 6570  240]
 [ 348   93 7335]]
Epoch: 417, Train Loss: 0.657289
-----------------------------------------
Valid Accuracy: 87.7

Train Accuracy: 89.94%
Confusion Matrix:
[[7076  566  134]
 [ 969 6571  236]
 [ 338  103 7335]]
Epoch: 432, Train Loss: 0.655079
-----------------------------------------
Valid Accuracy: 88.72%
Confusion Matrix:
[[85906  9226  1350]
 [  407  2255    87]
 [  183    23   563]]

Precision: 0.9657921336442072
Recall: 0.88724
F1 Score: 0.917768697809593
0 88.612
-----------------------------------------


##############################################
saved 88.724
##############################################


Train Accuracy: 89.95%
Confusion Matrix:
[[7078  564  134]
 [ 970 6571  235]
 [ 338  103 7335]]
Epoch: 433, Train Loss: 0.65493
-----------------------------------------
Valid Accuracy: 88.78%
Confusion Matrix:
[[85969  9160  1353]
 [  413  2249    87]
 [  183    23   563]]

Precision: 0.9657467732947124
Recall: 0.88781
F1 Score: 0.9181088499531989
0 88.724
-----------------------------------------


##############################################
saved 88.781
#######################

Train Accuracy: 90.11%
Confusion Matrix:
[[7116  527  133]
 [ 965 6570  241]
 [ 331  110 7335]]
Epoch: 448, Train Loss: 0.652892
-----------------------------------------
Valid Accuracy: 89.45%
Confusion Matrix:
[[86646  8468  1368]
 [  425  2237    87]
 [  183    23   563]]

Precision: 0.9659746124228384
Recall: 0.89446
F1 Score: 0.922210131463858
0 89.415
-----------------------------------------


##############################################
saved 89.446
##############################################


Train Accuracy: 90.12%
Confusion Matrix:
[[7119  524  133]
 [ 965 6570  241]
 [ 331  110 7335]]
Epoch: 449, Train Loss: 0.652768
-----------------------------------------
Valid Accuracy: 89.46%
Confusion Matrix:
[[86664  8450  1368]
 [  428  2234    87]
 [  183    23   563]]

Precision: 0.9659466056196215
Recall: 0.89461
F1 Score: 0.9222971413726984
0 89.446
-----------------------------------------


##############################################
saved 89.461
######################

Train Accuracy: 90.29%
Confusion Matrix:
[[7157  491  128]
 [ 963 6570  243]
 [ 335  106 7335]]
Epoch: 467, Train Loss: 0.650688
-----------------------------------------
Valid Accuracy: 89.69%
Confusion Matrix:
[[86864  8237  1381]
 [  415  2258    76]
 [  183    23   563]]

Precision: 0.9662681236941816
Recall: 0.89685
F1 Score: 0.9236972988932438
0 89.636
-----------------------------------------


##############################################
saved 89.685
##############################################


Train Accuracy: 90.32%
Confusion Matrix:
[[7164  483  129]
 [ 963 6570  243]
 [ 334  107 7335]]
Epoch: 468, Train Loss: 0.650556
-----------------------------------------
Valid Accuracy: 89.77%
Confusion Matrix:
[[86952  8183  1347]
 [  421  2252    76]
 [  183    23   563]]

Precision: 0.9662638690115061
Recall: 0.89767
F1 Score: 0.9242104023477028
0 89.685
-----------------------------------------


##############################################
saved 89.767
#####################

Train Accuracy: 90.50%
Confusion Matrix:
[[7207  447  122]
 [ 963 6571  242]
 [ 338  103 7335]]
Epoch: 485, Train Loss: 0.648545
-----------------------------------------
Valid Accuracy: 89.93%
Confusion Matrix:
[[87106  8050  1326]
 [  406  2270    73]
 [  191    24   554]]

Precision: 0.9664665054642306
Recall: 0.8993
F1 Score: 0.9252406376651453
0 89.891
-----------------------------------------


##############################################
saved 89.93
##############################################


Train Accuracy: 90.51%
Confusion Matrix:
[[7208  447  121]
 [ 963 6571  242]
 [ 338  103 7335]]
Epoch: 486, Train Loss: 0.648436
-----------------------------------------
Valid Accuracy: 89.97%
Confusion Matrix:
[[87148  8008  1326]
 [  406  2270    73]
 [  191    24   554]]

Precision: 0.9664942437100512
Recall: 0.89972
F1 Score: 0.9255031828848915
0 89.93
-----------------------------------------


##############################################
saved 89.972
########################

-----------------------------------------
Valid Accuracy: 90.40%
Confusion Matrix:
[[87578  7617  1287]
 [  393  2272    84]
 [  198    24   547]]

Precision: 0.9668464527935308
Recall: 0.90397
F1 Score: 0.9282039318111399
0 90.349
-----------------------------------------


##############################################
saved 90.397
##############################################


Train Accuracy: 90.63%
Confusion Matrix:
[[7237  422  117]
 [ 962 6571  243]
 [ 340  101 7335]]
Epoch: 502, Train Loss: 0.646898
-----------------------------------------
Valid Accuracy: 90.41%
Confusion Matrix:
[[87596  7602  1284]
 [  393  2272    84]
 [  201    24   544]]

Precision: 0.9668195365794637
Recall: 0.90412
F1 Score: 0.9282894388234746
0 90.397
-----------------------------------------


##############################################
saved 90.412
##############################################


Train Accuracy: 90.64%
Confusion Matrix:
[[7238  419  119]
 [ 963 6571  242]
 [ 340  101 7335]]
Epoch

-----------------------------------------
Valid Accuracy: 90.92%
Confusion Matrix:
[[88113  7098  1271]
 [  402  2263    84]
 [  201    21   547]]

Precision: 0.9671044983390498
Recall: 0.90923
F1 Score: 0.9314849140514477
0 90.851
-----------------------------------------


##############################################
saved 90.923
##############################################


Train Accuracy: 90.77%
Confusion Matrix:
[[7266  400  110]
 [ 960 6573  243]
 [ 332  109 7335]]
Epoch: 520, Train Loss: 0.645447
-----------------------------------------
Valid Accuracy: 90.95%
Confusion Matrix:
[[88141  7069  1272]
 [  402  2263    84]
 [  201    21   547]]

Precision: 0.9671259647027646
Recall: 0.90951
F1 Score: 0.9316612268755617
0 90.923
-----------------------------------------


##############################################
saved 90.951
##############################################


Train Accuracy: 90.77%
Confusion Matrix:
[[7267  400  109]
 [ 961 6573  242]
 [ 331  110 7335]]
Epoch

-----------------------------------------
Valid Accuracy: 91.14%
Confusion Matrix:
[[88325  6897  1260]
 [  395  2270    84]
 [  201    18   550]]

Precision: 0.9673802583304772
Recall: 0.91145
F1 Score: 0.9329045950606933
3 91.161
-----------------------------------------


Train Accuracy: 90.89%
Confusion Matrix:
[[7292  376  108]
 [ 957 6575  244]
 [ 339  102 7335]]
Epoch: 537, Train Loss: 0.64398
-----------------------------------------
Valid Accuracy: 91.14%
Confusion Matrix:
[[88319  6903  1260]
 [  395  2270    84]
 [  198    21   550]]

Precision: 0.967405507371058
Recall: 0.91139
F1 Score: 0.9328788904940213
4 91.161
-----------------------------------------


Train Accuracy: 90.89%
Confusion Matrix:
[[7292  376  108]
 [ 957 6575  244]
 [ 339  102 7335]]
Epoch: 538, Train Loss: 0.64392
-----------------------------------------
Valid Accuracy: 91.14%
Confusion Matrix:
[[88324  6898  1260]
 [  395  2270    84]
 [  198    21   550]]

Precision: 0.967409562376437
Recall: 0.91144


Train Accuracy: 90.95%
Confusion Matrix:
[[7307  364  105]
 [ 961 6575  240]
 [ 345   96 7335]]
Epoch: 557, Train Loss: 0.642972
-----------------------------------------
Valid Accuracy: 91.08%
Confusion Matrix:
[[88249  6958  1275]
 [  389  2276    84]
 [  195    21   553]]

Precision: 0.9674616637101408
Recall: 0.91078
F1 Score: 0.9325121367879795
24 91.161
-----------------------------------------


Train Accuracy: 90.95%
Confusion Matrix:
[[7307  364  105]
 [ 960 6575  241]
 [ 343   98 7335]]
Epoch: 558, Train Loss: 0.642931
-----------------------------------------
Valid Accuracy: 91.06%
Confusion Matrix:
[[88234  6973  1275]
 [  389  2276    84]
 [  194    21   554]]

Precision: 0.9674633021848511
Recall: 0.91064
F1 Score: 0.9324268192606636
25 91.161
-----------------------------------------


Train Accuracy: 90.96%
Confusion Matrix:
[[7308  362  106]
 [ 960 6575  241]
 [ 343   98 7335]]
Epoch: 559, Train Loss: 0.642892
-----------------------------------------
Valid Accuracy: 9

-----------------------------------------
Valid Accuracy: 91.46%
Confusion Matrix:
[[88621  6581  1280]
 [  390  2275    84]
 [  191    18   560]]

Precision: 0.9678216113794995
Recall: 0.91456
F1 Score: 0.9349146940265255
0 91.414
-----------------------------------------


##############################################
saved 91.456
##############################################


Train Accuracy: 91.07%
Confusion Matrix:
[[7325  345  106]
 [ 949 6585  242]
 [ 334  107 7335]]
Epoch: 576, Train Loss: 0.641705
-----------------------------------------
Valid Accuracy: 91.50%
Confusion Matrix:
[[88661  6541  1280]
 [  390  2275    84]
 [  191    18   560]]

Precision: 0.9678563389852389
Recall: 0.91496
F1 Score: 0.9351691005362007
0 91.456
-----------------------------------------


##############################################
saved 91.496
##############################################


Train Accuracy: 91.07%
Confusion Matrix:
[[7325  345  106]
 [ 949 6585  242]
 [ 334  107 7335]]
Epoch

Train Accuracy: 91.19%
Confusion Matrix:
[[7353  320  103]
 [ 950 6585  241]
 [ 329  112 7335]]
Epoch: 593, Train Loss: 0.640478
-----------------------------------------
Valid Accuracy: 91.71%
Confusion Matrix:
[[88847  6345  1290]
 [  381  2295    73]
 [  180    18   571]]

Precision: 0.9683234034833402
Recall: 0.91713
F1 Score: 0.9365910409271183
6 91.765
-----------------------------------------


Train Accuracy: 91.20%
Confusion Matrix:
[[7354  319  103]
 [ 949 6585  242]
 [ 331  110 7335]]
Epoch: 594, Train Loss: 0.640398
-----------------------------------------
Valid Accuracy: 91.71%
Confusion Matrix:
[[88841  6351  1290]
 [  375  2301    73]
 [  180    18   571]]

Precision: 0.9683962853805408
Recall: 0.91713
F1 Score: 0.9366055589743957
7 91.765
-----------------------------------------


Train Accuracy: 91.20%
Confusion Matrix:
[[7354  319  103]
 [ 948 6585  243]
 [ 330  111 7335]]
Epoch: 595, Train Loss: 0.640336
-----------------------------------------
Valid Accuracy: 91.

Train Accuracy: 91.26%
Confusion Matrix:
[[7368  304  104]
 [ 946 6585  245]
 [ 333  108 7335]]
Epoch: 613, Train Loss: 0.639636
-----------------------------------------
Valid Accuracy: 91.86%
Confusion Matrix:
[[88987  6201  1294]
 [  379  2297    73]
 [  184     8   577]]

Precision: 0.9684601881956275
Recall: 0.91861
F1 Score: 0.9375204185226813
0 91.843
-----------------------------------------


##############################################
saved 91.861
##############################################


Train Accuracy: 91.26%
Confusion Matrix:
[[7369  303  104]
 [ 952 6585  239]
 [ 333  108 7335]]
Epoch: 614, Train Loss: 0.639576
-----------------------------------------
Valid Accuracy: 91.86%
Confusion Matrix:
[[88982  6213  1287]
 [  379  2297    73]
 [  181    11   577]]

Precision: 0.9684871518495276
Recall: 0.91856
F1 Score: 0.9375017754182835
0 91.861
-----------------------------------------


Train Accuracy: 91.26%
Confusion Matrix:
[[7370  302  104]
 [ 950 6585  241]
 [ 3

Train Accuracy: 91.34%
Confusion Matrix:
[[7387  287  102]
 [ 957 6585  234]
 [ 336  105 7335]]
Epoch: 632, Train Loss: 0.638725
-----------------------------------------
Valid Accuracy: 92.36%
Confusion Matrix:
[[89503  5709  1270]
 [  393  2283    73]
 [  185    14   570]]

Precision: 0.9687596851711522
Recall: 0.92356
F1 Score: 0.9406780613863355
1 92.464
-----------------------------------------


Train Accuracy: 91.35%
Confusion Matrix:
[[7390  284  102]
 [ 958 6585  233]
 [ 331  110 7335]]
Epoch: 633, Train Loss: 0.638655
-----------------------------------------
Valid Accuracy: 92.32%
Confusion Matrix:
[[89450  5762  1270]
 [  393  2283    73]
 [  171    14   584]]

Precision: 0.9688928056772547
Recall: 0.92317
F1 Score: 0.9404679198680193
2 92.464
-----------------------------------------


Train Accuracy: 91.35%
Confusion Matrix:
[[7390  284  102]
 [ 957 6585  234]
 [ 331  110 7335]]
Epoch: 634, Train Loss: 0.638614
-----------------------------------------
Valid Accuracy: 92.

-----------------------------------------
Valid Accuracy: 92.02%
Confusion Matrix:
[[89152  6028  1302]
 [  378  2298    73]
 [  177    22   570]]

Precision: 0.9686717923354464
Recall: 0.9202
F1 Score: 0.9385759758009834
21 92.464
-----------------------------------------


Train Accuracy: 91.38%
Confusion Matrix:
[[7398  276  102]
 [ 954 6585  237]
 [ 342   99 7335]]
Epoch: 653, Train Loss: 0.638225
-----------------------------------------
Valid Accuracy: 92.09%
Confusion Matrix:
[[89224  5963  1295]
 [  378  2298    73]
 [  177    22   570]]

Precision: 0.9687441032472865
Recall: 0.92092
F1 Score: 0.939040160754438
22 92.464
-----------------------------------------


Train Accuracy: 91.39%
Confusion Matrix:
[[7399  275  102]
 [ 955 6585  236]
 [ 341  100 7335]]
Epoch: 654, Train Loss: 0.638072
-----------------------------------------
Valid Accuracy: 92.13%
Confusion Matrix:
[[89266  5924  1292]
 [  383  2293    73]
 [  177    22   570]]

Precision: 0.9687210729095553
Recall: 0.92

Train Accuracy: 91.46%
Confusion Matrix:
[[7416  259  101]
 [ 953 6585  238]
 [ 338  103 7335]]
Epoch: 673, Train Loss: 0.637312
-----------------------------------------
Valid Accuracy: 92.09%
Confusion Matrix:
[[89205  5968  1309]
 [  378  2298    73]
 [  156    27   586]]

Precision: 0.9689860697778563
Recall: 0.92089
F1 Score: 0.9390858698504236
42 92.464
-----------------------------------------


Train Accuracy: 91.47%
Confusion Matrix:
[[7419  256  101]
 [ 954 6585  237]
 [ 338  103 7335]]
Epoch: 674, Train Loss: 0.637224
-----------------------------------------
Valid Accuracy: 92.12%
Confusion Matrix:
[[89235  5941  1306]
 [  378  2298    73]
 [  156    27   586]]

Precision: 0.9690163661212237
Recall: 0.92119
F1 Score: 0.9392794550267667
43 92.464
-----------------------------------------


Train Accuracy: 91.47%
Confusion Matrix:
[[7419  256  101]
 [ 953 6585  238]
 [ 338  103 7335]]
Epoch: 675, Train Loss: 0.637137
-----------------------------------------
Valid Accuracy: 9

Train Accuracy: 91.57%
Confusion Matrix:
[[7442  233  101]
 [ 952 6585  239]
 [ 345   96 7335]]
Epoch: 693, Train Loss: 0.636339
-----------------------------------------
Valid Accuracy: 91.77%
Confusion Matrix:
[[88849  6273  1360]
 [  362  2303    84]
 [  119    28   622]]

Precision: 0.9692982311234962
Recall: 0.91774
F1 Score: 0.9372157229781689
7 92.562
-----------------------------------------


Train Accuracy: 91.57%
Confusion Matrix:
[[7442  233  101]
 [ 954 6585  237]
 [ 340  101 7335]]
Epoch: 694, Train Loss: 0.636351
-----------------------------------------
Valid Accuracy: 91.78%
Confusion Matrix:
[[88859  6263  1360]
 [  362  2303    84]
 [  119    28   622]]

Precision: 0.9693073745760374
Recall: 0.91784
F1 Score: 0.9372797444299578
8 92.562
-----------------------------------------


Train Accuracy: 91.57%
Confusion Matrix:
[[7442  233  101]
 [ 953 6585  238]
 [ 335  106 7335]]
Epoch: 695, Train Loss: 0.636414
-----------------------------------------
Valid Accuracy: 91.

Train Accuracy: 91.63%
Confusion Matrix:
[[7456  220  100]
 [ 957 6585  234]
 [ 330  111 7335]]
Epoch: 713, Train Loss: 0.635388
-----------------------------------------
Valid Accuracy: 92.54%
Confusion Matrix:
[[89651  5539  1292]
 [  373  2303    73]
 [  162    21   586]]

Precision: 0.9694578355877148
Recall: 0.9254
F1 Score: 0.941992946343105
13 93.114
-----------------------------------------


Train Accuracy: 91.63%
Confusion Matrix:
[[7456  220  100]
 [ 952 6585  239]
 [ 331  110 7335]]
Epoch: 714, Train Loss: 0.635374
-----------------------------------------
Valid Accuracy: 92.54%
Confusion Matrix:
[[89649  5537  1296]
 [  373  2303    73]
 [  159    24   586]]

Precision: 0.9694838646708864
Recall: 0.92538
F1 Score: 0.9419911054435822
14 93.114
-----------------------------------------


Train Accuracy: 91.63%
Confusion Matrix:
[[7456  219  101]
 [ 953 6585  238]
 [ 332  109 7335]]
Epoch: 715, Train Loss: 0.635368
-----------------------------------------
Valid Accuracy: 92.

-----------------------------------------
Valid Accuracy: 92.71%
Confusion Matrix:
[[89836  5368  1278]
 [  378  2298    73]
 [  162    34   573]]

Precision: 0.9695495357421572
Recall: 0.92707
F1 Score: 0.9430798652558278
33 93.114
-----------------------------------------


Train Accuracy: 91.68%
Confusion Matrix:
[[7468  207  101]
 [ 954 6585  237]
 [ 336  105 7335]]
Epoch: 734, Train Loss: 0.634854
-----------------------------------------
Valid Accuracy: 92.72%
Confusion Matrix:
[[89844  5360  1278]
 [  373  2303    73]
 [  162    34   573]]

Precision: 0.9696241587130279
Recall: 0.9272
F1 Score: 0.9431773727584465
34 93.114
-----------------------------------------


Train Accuracy: 91.69%
Confusion Matrix:
[[7469  206  101]
 [ 953 6585  238]
 [ 338  103 7335]]
Epoch: 735, Train Loss: 0.634831
-----------------------------------------
Valid Accuracy: 92.63%
Confusion Matrix:
[[89755  5449  1278]
 [  362  2303    84]
 [  160    36   573]]

Precision: 0.9696475130946034
Recall: 0.9

Train Accuracy: 91.73%
Confusion Matrix:
[[7478  199   99]
 [ 954 6585  237]
 [ 339  102 7335]]
Epoch: 754, Train Loss: 0.634414
-----------------------------------------
Valid Accuracy: 92.36%
Confusion Matrix:
[[89477  5702  1303]
 [  362  2303    84]
 [  157    36   576]]

Precision: 0.9693857548896821
Recall: 0.92356
F1 Score: 0.9408689938063789
54 93.114
-----------------------------------------


Train Accuracy: 91.73%
Confusion Matrix:
[[7478  198  100]
 [ 952 6585  239]
 [ 338  103 7335]]
Epoch: 755, Train Loss: 0.634375
-----------------------------------------
Valid Accuracy: 92.52%
Confusion Matrix:
[[89660  5526  1296]
 [  362  2303    84]
 [  174    36   559]]

Precision: 0.9693529393485868
Recall: 0.92522
F1 Score: 0.9418954218836343
55 93.114
-----------------------------------------


Train Accuracy: 91.73%
Confusion Matrix:
[[7478  198  100]
 [ 956 6585  235]
 [ 346   95 7335]]
Epoch: 756, Train Loss: 0.634343
-----------------------------------------
Valid Accuracy: 9

-----------------------------------------
Valid Accuracy: 92.37%
Confusion Matrix:
[[89454  5716  1312]
 [  362  2303    84]
 [  120    33   616]]

Precision: 0.9698661464960624
Recall: 0.92373
F1 Score: 0.94108105294265
74 93.114
-----------------------------------------


Train Accuracy: 91.78%
Confusion Matrix:
[[7490  186  100]
 [ 954 6585  237]
 [ 337  104 7335]]
Epoch: 775, Train Loss: 0.633846
-----------------------------------------
Valid Accuracy: 92.31%
Confusion Matrix:
[[89390  5769  1323]
 [  362  2303    84]
 [  117    33   619]]

Precision: 0.9698382020003986
Recall: 0.92312
F1 Score: 0.94069345601073
75 93.114
-----------------------------------------


Train Accuracy: 91.78%
Confusion Matrix:
[[7491  186   99]
 [ 952 6585  239]
 [ 338  103 7335]]
Epoch: 776, Train Loss: 0.63381
-----------------------------------------
Valid Accuracy: 92.49%
Confusion Matrix:
[[89579  5594  1309]
 [  362  2303    84]
 [  127    33   609]]

Precision: 0.9699045745646234
Recall: 0.92491

-----------------------------------------
Valid Accuracy: 92.42%
Confusion Matrix:
[[89477  5679  1326]
 [  362  2303    84]
 [  101    28   640]]

Precision: 0.9701578104112079
Recall: 0.9242
F1 Score: 0.9414300367394254
5 93.369
-----------------------------------------


Train Accuracy: 91.80%
Confusion Matrix:
[[7496  180  100]
 [ 951 6585  240]
 [ 334  107 7335]]
Epoch: 795, Train Loss: 0.633508
-----------------------------------------
Valid Accuracy: 93.38%
Confusion Matrix:
[[90516  4699  1267]
 [  367  2298    84]
 [  177    24   568]]

Precision: 0.970329810584537
Recall: 0.93382
F1 Score: 0.9475107283044006
6 93.369
-----------------------------------------


##############################################
saved 93.382
##############################################


Train Accuracy: 91.81%
Confusion Matrix:
[[7497  179  100]
 [ 955 6585  236]
 [ 354   87 7335]]
Epoch: 796, Train Loss: 0.633431
-----------------------------------------
Valid Accuracy: 93.15%
Confusion Matrix:


-----------------------------------------
Valid Accuracy: 93.33%
Confusion Matrix:
[[90455  4756  1271]
 [  368  2308    73]
 [  174    30   565]]

Precision: 0.9702930264173384
Recall: 0.93328
F1 Score: 0.9471506985676936
18 93.382
-----------------------------------------


Train Accuracy: 91.97%
Confusion Matrix:
[[7504  172  100]
 [ 922 6615  239]
 [ 349   92 7335]]
Epoch: 815, Train Loss: 0.631901
-----------------------------------------
Valid Accuracy: 93.09%
Confusion Matrix:
[[90200  4990  1292]
 [  357  2308    84]
 [  160    30   579]]

Precision: 0.9702570985088702
Recall: 0.93087
F1 Score: 0.9456396056856223
19 93.382
-----------------------------------------


Train Accuracy: 91.97%
Confusion Matrix:
[[7504  172  100]
 [ 921 6615  240]
 [ 339  102 7335]]
Epoch: 816, Train Loss: 0.631831
-----------------------------------------
Valid Accuracy: 93.40%
Confusion Matrix:
[[90531  4697  1254]
 [  368  2308    73]
 [  177    30   562]]

Precision: 0.9703531227888144
Recall: 0.

Train Accuracy: 92.00%
Confusion Matrix:
[[7511  164  101]
 [ 925 6615  236]
 [ 358   83 7335]]
Epoch: 834, Train Loss: 0.631519
-----------------------------------------
Valid Accuracy: 93.30%
Confusion Matrix:
[[90414  4801  1267]
 [  352  2313    84]
 [  171    30   568]]

Precision: 0.970447625616996
Recall: 0.93295
F1 Score: 0.9469943463256125
5 93.647
-----------------------------------------


Train Accuracy: 92.00%
Confusion Matrix:
[[7512  165   99]
 [ 922 6615  239]
 [ 346   95 7335]]
Epoch: 835, Train Loss: 0.631527
-----------------------------------------
Valid Accuracy: 92.74%
Confusion Matrix:
[[89838  5340  1304]
 [  352  2313    84]
 [  145    31   593]]

Precision: 0.9700886663826299
Recall: 0.92744
F1 Score: 0.9434457415827655
6 93.647
-----------------------------------------


Train Accuracy: 92.00%
Confusion Matrix:
[[7511  165  100]
 [ 926 6615  235]
 [ 343   98 7335]]
Epoch: 836, Train Loss: 0.631566
-----------------------------------------
Valid Accuracy: 93.1

-----------------------------------------
Valid Accuracy: 92.80%
Confusion Matrix:
[[89885  5294  1303]
 [  352  2313    84]
 [  132    31   606]]

Precision: 0.970315593447853
Recall: 0.92804
F1 Score: 0.9438742283737105
25 93.647
-----------------------------------------


Train Accuracy: 92.02%
Confusion Matrix:
[[7516  160  100]
 [ 920 6615  241]
 [ 333  108 7335]]
Epoch: 855, Train Loss: 0.631377
-----------------------------------------
Valid Accuracy: 93.38%
Confusion Matrix:
[[90503  4719  1260]
 [  352  2313    84]
 [  174    27   568]]

Precision: 0.9705369425786988
Recall: 0.93384
F1 Score: 0.9475733854173165
26 93.647
-----------------------------------------


Train Accuracy: 92.03%
Confusion Matrix:
[[7518  158  100]
 [ 925 6615  236]
 [ 357   84 7335]]
Epoch: 856, Train Loss: 0.631242
-----------------------------------------
Valid Accuracy: 92.90%
Confusion Matrix:
[[89998  5181  1303]
 [  352  2313    84]
 [  149    31   589]]

Precision: 0.9702207444535551
Recall: 0.9

-----------------------------------------
Valid Accuracy: 93.32%
Confusion Matrix:
[[90396  4803  1283]
 [  363  2313    73]
 [  130    27   612]]

Precision: 0.9708796607703777
Recall: 0.93321
F1 Score: 0.9472378104659679
2 93.747
-----------------------------------------


Train Accuracy: 92.06%
Confusion Matrix:
[[7525  153   98]
 [ 927 6615  234]
 [ 336  105 7335]]
Epoch: 875, Train Loss: 0.630811
-----------------------------------------
Valid Accuracy: 93.68%
Confusion Matrix:
[[90783  4445  1254]
 [  363  2313    73]
 [  157    27   585]]

Precision: 0.9710492043479769
Recall: 0.93681
F1 Score: 0.9495618130002971
3 93.747
-----------------------------------------


Train Accuracy: 92.06%
Confusion Matrix:
[[7525  154   97]
 [ 923 6615  238]
 [ 346   95 7335]]
Epoch: 876, Train Loss: 0.630923
-----------------------------------------
Valid Accuracy: 93.32%
Confusion Matrix:
[[90414  4811  1257]
 [  363  2313    73]
 [  145    28   596]]

Precision: 0.9706994510641818
Recall: 0.93

Train Accuracy: 92.06%
Confusion Matrix:
[[7526  151   99]
 [ 918 6615  243]
 [ 343   98 7335]]
Epoch: 895, Train Loss: 0.630744
-----------------------------------------
Valid Accuracy: 93.63%
Confusion Matrix:
[[90739  4503  1240]
 [  363  2313    73]
 [  160    27   582]]

Precision: 0.9709445234613822
Recall: 0.93634
F1 Score: 0.9492367433381301
23 93.747
-----------------------------------------


Train Accuracy: 92.06%
Confusion Matrix:
[[7525  154   97]
 [ 923 6615  238]
 [ 349   92 7335]]
Epoch: 896, Train Loss: 0.63077
-----------------------------------------
Valid Accuracy: 93.27%
Confusion Matrix:
[[90341  4851  1290]
 [  363  2313    73]
 [  130    27   612]]

Precision: 0.970808597605818
Recall: 0.93266
F1 Score: 0.9468737187168462
24 93.747
-----------------------------------------


Train Accuracy: 92.06%
Confusion Matrix:
[[7526  151   99]
 [ 919 6615  242]
 [ 342   99 7335]]
Epoch: 897, Train Loss: 0.630711
-----------------------------------------
Valid Accuracy: 93.

Train Accuracy: 92.07%
Confusion Matrix:
[[7527  151   98]
 [ 926 6615  235]
 [ 339  102 7335]]
Epoch: 915, Train Loss: 0.630674
-----------------------------------------
Valid Accuracy: 93.71%
Confusion Matrix:
[[90801  4441  1240]
 [  363  2313    73]
 [  150    23   596]]

Precision: 0.9711828991679109
Recall: 0.9371
F1 Score: 0.9497702596935486
14 93.799
-----------------------------------------


Train Accuracy: 92.07%
Confusion Matrix:
[[7528  151   97]
 [ 920 6615  241]
 [ 348   93 7335]]
Epoch: 916, Train Loss: 0.630773
-----------------------------------------
Valid Accuracy: 93.17%
Confusion Matrix:
[[90260  5004  1218]
 [  363  2313    73]
 [  145    28   596]]

Precision: 0.9705058790747986
Recall: 0.93169
F1 Score: 0.946192841867535
15 93.799
-----------------------------------------


Train Accuracy: 92.07%
Confusion Matrix:
[[7527  151   98]
 [ 924 6615  237]
 [ 341  100 7335]]
Epoch: 917, Train Loss: 0.630795
-----------------------------------------
Valid Accuracy: 93.

-----------------------------------------
Valid Accuracy: 93.41%
Confusion Matrix:
[[90481  4771  1230]
 [  363  2313    73]
 [  130    20   619]]

Precision: 0.9710186609332964
Recall: 0.93413
F1 Score: 0.947840338502848
34 93.799
-----------------------------------------


Train Accuracy: 92.09%
Confusion Matrix:
[[7533  148   95]
 [ 922 6615  239]
 [ 337  104 7335]]
Epoch: 936, Train Loss: 0.630444
-----------------------------------------
Valid Accuracy: 93.69%
Confusion Matrix:
[[90755  4503  1224]
 [  363  2313    73]
 [  134    16   619]]

Precision: 0.971356395870096
Recall: 0.93687
F1 Score: 0.949651760459174
35 93.799
-----------------------------------------


Train Accuracy: 92.09%
Confusion Matrix:
[[7533  147   96]
 [ 921 6615  240]
 [ 347   94 7335]]
Epoch: 937, Train Loss: 0.63056
-----------------------------------------
Valid Accuracy: 93.56%
Confusion Matrix:
[[90636  4622  1224]
 [  363  2313    73]
 [  144    17   608]]

Precision: 0.9710535475537709
Recall: 0.9355

-----------------------------------------
Valid Accuracy: 93.43%
Confusion Matrix:
[[90480  4765  1237]
 [  363  2313    73]
 [  110    20   639]]

Precision: 0.9712817802726194
Recall: 0.93432
F1 Score: 0.9480202880655324
14 93.834
-----------------------------------------


Train Accuracy: 92.09%
Confusion Matrix:
[[7533  148   95]
 [ 924 6615  237]
 [ 341  100 7335]]
Epoch: 956, Train Loss: 0.630436
-----------------------------------------
Valid Accuracy: 93.77%
Confusion Matrix:
[[90860  4415  1207]
 [  363  2313    73]
 [  158    16   595]]

Precision: 0.9711877520812408
Recall: 0.93768
F1 Score: 0.9501281384341161
15 93.834
-----------------------------------------


Train Accuracy: 92.09%
Confusion Matrix:
[[7533  147   96]
 [ 924 6615  237]
 [ 347   94 7335]]
Epoch: 957, Train Loss: 0.630551
-----------------------------------------
Valid Accuracy: 93.22%
Confusion Matrix:
[[90291  4954  1237]
 [  363  2313    73]
 [  130    20   619]]

Precision: 0.9707739551401202
Recall: 0.

Train Accuracy: 92.11%
Confusion Matrix:
[[7537  147   92]
 [ 935 6615  226]
 [ 350   91 7335]]
Epoch: 976, Train Loss: 0.630193
-----------------------------------------
Valid Accuracy: 93.42%
Confusion Matrix:
[[90525  4784  1173]
 [  370  2313    66]
 [  157    27   585]]

Precision: 0.9706274568739731
Recall: 0.93423
F1 Score: 0.9478115846904578
35 93.834
-----------------------------------------


Train Accuracy: 92.11%
Confusion Matrix:
[[7538  147   91]
 [ 936 6615  225]
 [ 343   98 7335]]
Epoch: 977, Train Loss: 0.63014
-----------------------------------------
Valid Accuracy: 93.82%
Confusion Matrix:
[[90913  4390  1179]
 [  370  2313    66]
 [  158    19   592]]

Precision: 0.9711862808983924
Recall: 0.93818
F1 Score: 0.9504382618059176
36 93.834
-----------------------------------------


Train Accuracy: 92.11%
Confusion Matrix:
[[7538  146   92]
 [ 937 6615  224]
 [ 359   82 7335]]
Epoch: 978, Train Loss: 0.630181
-----------------------------------------
Valid Accuracy: 93

Train Accuracy: 92.12%
Confusion Matrix:
[[7539  145   92]
 [ 936 6615  225]
 [ 355   86 7335]]
Epoch: 996, Train Loss: 0.630272
-----------------------------------------
Valid Accuracy: 92.83%
Confusion Matrix:
[[89910  5387  1185]
 [  370  2313    66]
 [  133    33   603]]

Precision: 0.9701759474590929
Recall: 0.92826
F1 Score: 0.9439640814976455
3 93.931
-----------------------------------------


Train Accuracy: 92.12%
Confusion Matrix:
[[7539  146   91]
 [ 934 6615  227]
 [ 346   95 7335]]
Epoch: 997, Train Loss: 0.630126
-----------------------------------------
Valid Accuracy: 93.98%
Confusion Matrix:
[[91070  4239  1173]
 [  370  2313    66]
 [  158    16   595]]

Precision: 0.9714342513502446
Recall: 0.93978
F1 Score: 0.9515134655717145
4 93.931
-----------------------------------------


##############################################
saved 93.978
##############################################


Train Accuracy: 92.12%
Confusion Matrix:
[[7539  145   92]
 [ 934 6615  227]
 [ 3

Train Accuracy: 92.13%
Confusion Matrix:
[[7542  143   91]
 [ 935 6615  226]
 [ 352   89 7335]]
Epoch: 1016, Train Loss: 0.629899
-----------------------------------------
Valid Accuracy: 93.95%
Confusion Matrix:
[[91046  4257  1179]
 [  370  2313    66]
 [  158    16   595]]

Precision: 0.9713981997257007
Recall: 0.93954
F1 Score: 0.951352041440611
7 94.204
-----------------------------------------


Train Accuracy: 92.13%
Confusion Matrix:
[[7543  141   92]
 [ 937 6615  224]
 [ 345   96 7335]]
Epoch: 1017, Train Loss: 0.630074
-----------------------------------------
Valid Accuracy: 93.53%
Confusion Matrix:
[[90618  4679  1185]
 [  370  2313    66]
 [  140    26   603]]

Precision: 0.9709816624459023
Recall: 0.93534
F1 Score: 0.9485964416548435
8 94.204
-----------------------------------------


Train Accuracy: 92.13%
Confusion Matrix:
[[7542  143   91]
 [ 936 6615  225]
 [ 338  103 7335]]
Epoch: 1018, Train Loss: 0.629967
-----------------------------------------
Valid Accuracy: 9

-----------------------------------------
Valid Accuracy: 94.11%
Confusion Matrix:
[[91216  4102  1164]
 [  370  2313    66]
 [  167    16   586]]

Precision: 0.971541858857214
Recall: 0.94115
F1 Score: 0.9524153943585708
27 94.204
-----------------------------------------


Train Accuracy: 92.14%
Confusion Matrix:
[[7544  140   92]
 [ 937 6615  224]
 [ 353   88 7335]]
Epoch: 1037, Train Loss: 0.630062
-----------------------------------------
Valid Accuracy: 93.61%
Confusion Matrix:
[[90715  4598  1169]
 [  370  2313    66]
 [  158    26   585]]

Precision: 0.9708745933342473
Recall: 0.93613
F1 Score: 0.9490709320328679
28 94.204
-----------------------------------------


Train Accuracy: 92.13%
Confusion Matrix:
[[7543  142   91]
 [ 936 6615  225]
 [ 337  104 7335]]
Epoch: 1038, Train Loss: 0.629958
-----------------------------------------
Valid Accuracy: 94.00%
Confusion Matrix:
[[91084  4219  1179]
 [  370  2313    66]
 [  151    16   602]]

Precision: 0.9715495569505765
Recall: 0

-----------------------------------------
Valid Accuracy: 93.78%
Confusion Matrix:
[[90864  4426  1192]
 [  370  2313    66]
 [  154    16   599]]

Precision: 0.9711813662154142
Recall: 0.93776
F1 Score: 0.9501660961837614
9 94.216
-----------------------------------------


Train Accuracy: 92.15%
Confusion Matrix:
[[7546  140   90]
 [ 937 6615  224]
 [ 341  100 7335]]
Epoch: 1057, Train Loss: 0.629973
-----------------------------------------
Valid Accuracy: 93.04%
Confusion Matrix:
[[90135  5151  1196]
 [  370  2313    66]
 [  152    28   589]]

Precision: 0.9701985742213656
Recall: 0.93037
F1 Score: 0.9452811315632772
10 94.216
-----------------------------------------


Train Accuracy: 92.15%
Confusion Matrix:
[[7547  138   91]
 [ 939 6615  222]
 [ 333  108 7335]]
Epoch: 1058, Train Loss: 0.629889
-----------------------------------------
Valid Accuracy: 93.99%
Confusion Matrix:
[[91094  4246  1142]
 [  370  2313    66]
 [  174    16   579]]

Precision: 0.9712546789461322
Recall: 0

Train Accuracy: 92.16%
Confusion Matrix:
[[7549  136   91]
 [ 946 6615  215]
 [ 356   85 7335]]
Epoch: 1077, Train Loss: 0.629623
-----------------------------------------
Valid Accuracy: 93.43%
Confusion Matrix:
[[90529  4772  1181]
 [  370  2313    66]
 [  154    23   592]]

Precision: 0.9706885519978563
Recall: 0.93434
F1 Score: 0.9478900072662769
30 94.216
-----------------------------------------


Train Accuracy: 92.16%
Confusion Matrix:
[[7549  137   90]
 [ 950 6615  211]
 [ 346   95 7335]]
Epoch: 1078, Train Loss: 0.629595
-----------------------------------------
Valid Accuracy: 93.72%
Confusion Matrix:
[[90778  4511  1193]
 [  370  2313    66]
 [  130    13   626]]

Precision: 0.9713887906011325
Recall: 0.93717
F1 Score: 0.9498340190795226
31 94.216
-----------------------------------------


Train Accuracy: 92.16%
Confusion Matrix:
[[7549  136   91]
 [ 949 6615  212]
 [ 344   97 7335]]
Epoch: 1079, Train Loss: 0.62954
-----------------------------------------
Valid Accuracy:

Train Accuracy: 92.16%
Confusion Matrix:
[[7549  136   91]
 [ 949 6615  212]
 [ 357   84 7335]]
Epoch: 1097, Train Loss: 0.629593
-----------------------------------------
Valid Accuracy: 93.60%
Confusion Matrix:
[[90673  4634  1175]
 [  370  2313    66]
 [  146    13   610]]

Precision: 0.9710304286072863
Recall: 0.93596
F1 Score: 0.9489819270498393
13 94.287
-----------------------------------------


Train Accuracy: 92.16%
Confusion Matrix:
[[7548  137   91]
 [ 958 6615  203]
 [ 345   96 7335]]
Epoch: 1098, Train Loss: 0.629731
-----------------------------------------
Valid Accuracy: 93.51%
Confusion Matrix:
[[90537  4737  1208]
 [  370  2313    66]
 [   95    13   661]]

Precision: 0.9715193633677298
Recall: 0.93511
F1 Score: 0.9485534193478201
14 94.287
-----------------------------------------


Train Accuracy: 92.16%
Confusion Matrix:
[[7549  136   91]
 [ 946 6615  215]
 [ 338  103 7335]]
Epoch: 1099, Train Loss: 0.62954
-----------------------------------------
Valid Accuracy:

Train Accuracy: 92.17%
Confusion Matrix:
[[7552  134   90]
 [ 950 6615  211]
 [ 339  102 7335]]
Epoch: 1117, Train Loss: 0.629418
-----------------------------------------
Valid Accuracy: 94.21%
Confusion Matrix:
[[91299  4037  1146]
 [  370  2313    66]
 [  157    13   599]]

Precision: 0.9718191330404309
Recall: 0.94211
F1 Score: 0.9530910544094003
1 94.517
-----------------------------------------


Train Accuracy: 92.17%
Confusion Matrix:
[[7552  134   90]
 [ 949 6615  212]
 [ 347   94 7335]]
Epoch: 1118, Train Loss: 0.629372
-----------------------------------------
Valid Accuracy: 94.01%
Confusion Matrix:
[[91065  4236  1181]
 [  370  2313    66]
 [  126    13   630]]

Precision: 0.9718642938389466
Recall: 0.94008
F1 Score: 0.9518011056796771
2 94.517
-----------------------------------------


Train Accuracy: 92.17%
Confusion Matrix:
[[7552  134   90]
 [ 952 6615  209]
 [ 347   94 7335]]
Epoch: 1119, Train Loss: 0.629374
-----------------------------------------
Valid Accuracy: 

-----------------------------------------
Valid Accuracy: 93.97%
Confusion Matrix:
[[91068  4250  1164]
 [  370  2313    66]
 [  157    20   592]]

Precision: 0.9714263133751627
Recall: 0.93973
F1 Score: 0.9514843848059971
21 94.517
-----------------------------------------


Train Accuracy: 92.19%
Confusion Matrix:
[[7555  131   90]
 [ 950 6615  211]
 [ 341  100 7335]]
Epoch: 1138, Train Loss: 0.629263
-----------------------------------------
Valid Accuracy: 94.22%
Confusion Matrix:
[[91307  4011  1164]
 [  370  2313    66]
 [  164     6   599]]

Precision: 0.9717735635346788
Recall: 0.94219
F1 Score: 0.9531244954349866
22 94.517
-----------------------------------------


Train Accuracy: 92.19%
Confusion Matrix:
[[7555  131   90]
 [ 950 6615  211]
 [ 346   95 7335]]
Epoch: 1139, Train Loss: 0.629242
-----------------------------------------
Valid Accuracy: 93.92%
Confusion Matrix:
[[90965  4335  1182]
 [  370  2313    66]
 [  112    13   644]]

Precision: 0.9718979104165522
Recall: 

Train Accuracy: 92.19%
Confusion Matrix:
[[7555  131   90]
 [ 951 6615  210]
 [ 340  101 7335]]
Epoch: 1158, Train Loss: 0.629154
-----------------------------------------
Valid Accuracy: 94.07%
Confusion Matrix:
[[91149  4159  1174]
 [  370  2313    66]
 [  152    13   604]]

Precision: 0.9716497360108873
Recall: 0.94066
F1 Score: 0.9521233595816511
42 94.517
-----------------------------------------


Train Accuracy: 92.19%
Confusion Matrix:
[[7555  131   90]
 [ 950 6615  211]
 [ 344   97 7335]]
Epoch: 1159, Train Loss: 0.629126
-----------------------------------------
Valid Accuracy: 94.47%
Confusion Matrix:
[[91558  3777  1147]
 [  370  2313    66]
 [  162     6   601]]

Precision: 0.9722245723397341
Recall: 0.94472
F1 Score: 0.9548606422717658
43 94.517
-----------------------------------------


Train Accuracy: 92.19%
Confusion Matrix:
[[7555  131   90]
 [ 948 6615  213]
 [ 347   94 7335]]
Epoch: 1160, Train Loss: 0.629284
-----------------------------------------
Valid Accuracy

Train Accuracy: 92.19%
Confusion Matrix:
[[7557  129   90]
 [ 951 6615  210]
 [ 346   95 7335]]
Epoch: 1178, Train Loss: 0.629127
-----------------------------------------
Valid Accuracy: 93.97%
Confusion Matrix:
[[91021  4282  1179]
 [  370  2313    66]
 [  118    13   638]]

Precision: 0.9719026651632111
Recall: 0.93972
F1 Score: 0.9515789187360031
9 94.548
-----------------------------------------


Train Accuracy: 92.19%
Confusion Matrix:
[[7557  129   90]
 [ 953 6615  208]
 [ 336  105 7335]]
Epoch: 1179, Train Loss: 0.629325
-----------------------------------------
Valid Accuracy: 94.07%
Confusion Matrix:
[[91072  4203  1207]
 [  370  2313    66]
 [   79     7   683]]

Precision: 0.9725195428906924
Recall: 0.94068
F1 Score: 0.9523221958098842
10 94.548
-----------------------------------------


Train Accuracy: 92.19%
Confusion Matrix:
[[7557  129   90]
 [ 945 6615  216]
 [ 335  106 7335]]
Epoch: 1180, Train Loss: 0.629185
-----------------------------------------
Valid Accuracy:

Train Accuracy: 92.21%
Confusion Matrix:
[[7561  125   90]
 [ 950 6615  211]
 [ 356   85 7335]]
Epoch: 1198, Train Loss: 0.629067
-----------------------------------------
Valid Accuracy: 94.12%
Confusion Matrix:
[[91166  4138  1178]
 [  370  2313    66]
 [  114    13   642]]

Precision: 0.9721792137413398
Recall: 0.94121
F1 Score: 0.9525973515498779
0 94.594
-----------------------------------------


Train Accuracy: 92.21%
Confusion Matrix:
[[7561  125   90]
 [ 956 6615  205]
 [ 338  103 7335]]
Epoch: 1199, Train Loss: 0.629026
-----------------------------------------
Valid Accuracy: 94.15%
Confusion Matrix:
[[91214  4096  1172]
 [  370  2313    66]
 [  141     6   622]]

Precision: 0.9719284166356159
Recall: 0.94149
F1 Score: 0.9527104416279547
1 94.594
-----------------------------------------


Train Accuracy: 92.21%
Confusion Matrix:
[[7561  125   90]
 [ 945 6615  216]
 [ 340  101 7335]]
Epoch: 1200, Train Loss: 0.629037
-----------------------------------------
Valid Accuracy: 

Train Accuracy: 92.22%
Confusion Matrix:
[[7564  123   89]
 [ 955 6615  206]
 [ 346   95 7335]]
Epoch: 1218, Train Loss: 0.628834
-----------------------------------------
Valid Accuracy: 93.98%
Confusion Matrix:
[[90975  4282  1225]
 [  370  2313    66]
 [   66     6   697]]

Precision: 0.9725468080336522
Recall: 0.93985
F1 Score: 0.951792197198118
9 94.613
-----------------------------------------


Train Accuracy: 92.22%
Confusion Matrix:
[[7564  123   89]
 [ 949 6615  212]
 [ 342   99 7335]]
Epoch: 1219, Train Loss: 0.628926
-----------------------------------------
Valid Accuracy: 94.40%
Confusion Matrix:
[[91437  3867  1178]
 [  370  2313    66]
 [  112     6   651]]

Precision: 0.9726812703701577
Recall: 0.94401
F1 Score: 0.9545067431652743
10 94.613
-----------------------------------------


Train Accuracy: 92.22%
Confusion Matrix:
[[7564  123   89]
 [ 949 6615  212]
 [ 335  106 7335]]
Epoch: 1220, Train Loss: 0.628826
-----------------------------------------
Valid Accuracy: 

Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 950 6615  211]
 [ 356   85 7335]]
Epoch: 1238, Train Loss: 0.628889
-----------------------------------------
Valid Accuracy: 94.31%
Confusion Matrix:
[[91323  3981  1178]
 [  370  2313    66]
 [   90     3   676]]

Precision: 0.9727895808549525
Recall: 0.94312
F1 Score: 0.9539482193406023
7 94.704
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 948 6615  213]
 [ 343   98 7335]]
Epoch: 1239, Train Loss: 0.628798
-----------------------------------------
Valid Accuracy: 94.22%
Confusion Matrix:
[[91278  4052  1152]
 [  370  2313    66]
 [  126    13   630]]

Precision: 0.9721964706195276
Recall: 0.94221
F1 Score: 0.9532429879484204
8 94.704
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 955 6615  206]
 [ 336  105 7335]]
Epoch: 1240, Train Loss: 0.628868
-----------------------------------------
Valid Accuracy: 

Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 948 6615  213]
 [ 351   90 7335]]
Epoch: 1258, Train Loss: 0.628933
-----------------------------------------
Valid Accuracy: 94.16%
Confusion Matrix:
[[91157  4136  1189]
 [  370  2313    66]
 [   77     3   689]]

Precision: 0.9726924738528233
Recall: 0.94159
F1 Score: 0.952938646086721
7 94.721
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 953 6615  208]
 [ 348   93 7335]]
Epoch: 1259, Train Loss: 0.628929
-----------------------------------------
Valid Accuracy: 94.20%
Confusion Matrix:
[[91194  4109  1179]
 [  370  2313    66]
 [   77     3   689]]

Precision: 0.9727498813224058
Recall: 0.94196
F1 Score: 0.9531893576442405
8 94.721
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 952 6615  209]
 [ 339  102 7335]]
Epoch: 1260, Train Loss: 0.628768
-----------------------------------------
Valid Accuracy: 9

Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 948 6615  213]
 [ 350   91 7335]]
Epoch: 1278, Train Loss: 0.628842
-----------------------------------------
Valid Accuracy: 94.22%
Confusion Matrix:
[[91219  4071  1192]
 [  370  2313    66]
 [   77     3   689]]

Precision: 0.9727917520726788
Recall: 0.94221
F1 Score: 0.9533603573169929
15 94.909
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 948 6615  213]
 [ 351   90 7335]]
Epoch: 1279, Train Loss: 0.628902
-----------------------------------------
Valid Accuracy: 94.40%
Confusion Matrix:
[[91407  3902  1173]
 [  370  2313    66]
 [   87     3   679]]

Precision: 0.9729684941065179
Recall: 0.94399
F1 Score: 0.9545501707284572
16 94.909
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 954 6615  207]
 [ 342   99 7335]]
Epoch: 1280, Train Loss: 0.628912
-----------------------------------------
Valid Accuracy

-----------------------------------------
Valid Accuracy: 94.38%
Confusion Matrix:
[[91388  3925  1169]
 [  370  2313    66]
 [   90     3   676]]

Precision: 0.9728963588316722
Recall: 0.94377
F1 Score: 0.9543917085987809
35 94.909
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 954 6615  207]
 [ 352   89 7335]]
Epoch: 1299, Train Loss: 0.628781
-----------------------------------------
Valid Accuracy: 94.33%
Confusion Matrix:
[[91335  3925  1222]
 [  370  2313    66]
 [   79     3   687]]

Precision: 0.9729632996546372
Recall: 0.94335
F1 Score: 0.9541379678231191
36 94.909
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [ 953 6615  208]
 [ 354   87 7335]]
Epoch: 1300, Train Loss: 0.628932
-----------------------------------------
Valid Accuracy: 94.04%
Confusion Matrix:
[[91037  4234  1211]
 [  370  2313    66]
 [   79     3   687]]

Precision: 0.9724822747896376
Recall: 

Train Accuracy: 92.23%
Confusion Matrix:
[[7566  122   88]
 [ 950 6615  211]
 [ 332  109 7335]]
Epoch: 1319, Train Loss: 0.62877
-----------------------------------------
Valid Accuracy: 94.39%
Confusion Matrix:
[[91387  3899  1196]
 [  370  2313    66]
 [   79     4   686]]

Precision: 0.9730400759156096
Recall: 0.94386
F1 Score: 0.9544843523095656
56 94.909
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7566  122   88]
 [ 948 6615  213]
 [ 335  106 7335]]
Epoch: 1320, Train Loss: 0.628748
-----------------------------------------
Valid Accuracy: 94.14%
Confusion Matrix:
[[91139  4158  1185]
 [  370  2313    66]
 [   79     4   686]]

Precision: 0.9726335159642644
Recall: 0.94138
F1 Score: 0.9527921149321931
57 94.909
-----------------------------------------


Train Accuracy: 92.23%
Confusion Matrix:
[[7566  122   88]
 [ 954 6615  207]
 [ 334  107 7335]]
Epoch: 1321, Train Loss: 0.628727
-----------------------------------------
Valid Accuracy:

-----------------------------------------
Valid Accuracy: 94.12%
Confusion Matrix:
[[91114  4190  1178]
 [  370  2313    66]
 [   73     3   693]]

Precision: 0.9726761418103993
Recall: 0.9412
F1 Score: 0.9526833346520619
76 94.909
-----------------------------------------


Train Accuracy: 92.24%
Confusion Matrix:
[[7568  121   87]
 [ 951 6615  210]
 [ 352   89 7335]]
Epoch: 1340, Train Loss: 0.62873
-----------------------------------------
Valid Accuracy: 94.21%
Confusion Matrix:
[[91224  4094  1164]
 [  370  2313    66]
 [   96     3   670]]

Precision: 0.9725477494833918
Recall: 0.94207
F1 Score: 0.9532165740377205
77 94.909
-----------------------------------------


Train Accuracy: 92.24%
Confusion Matrix:
[[7568  121   87]
 [ 954 6615  207]
 [ 339  102 7335]]
Epoch: 1341, Train Loss: 0.628667
-----------------------------------------
Valid Accuracy: 94.38%
Confusion Matrix:
[[91368  3919  1195]
 [  370  2313    66]
 [   72     0   697]]

Precision: 0.9731154113389345
Recall: 0.

Train Accuracy: 92.25%
Confusion Matrix:
[[7569  121   86]
 [ 951 6615  210]
 [ 340  101 7335]]
Epoch: 1360, Train Loss: 0.628648
-----------------------------------------
Valid Accuracy: 93.96%
Confusion Matrix:
[[90989  4355  1138]
 [  370  2313    66]
 [  104     7   658]]

Precision: 0.9720631612764529
Recall: 0.9396
F1 Score: 0.9515288653008784
97 94.909
-----------------------------------------


Train Accuracy: 92.25%
Confusion Matrix:
[[7569  121   86]
 [ 952 6615  209]
 [ 328  113 7335]]
Epoch: 1361, Train Loss: 0.628837
-----------------------------------------
Valid Accuracy: 93.96%
Confusion Matrix:
[[90940  4325  1217]
 [  370  2313    66]
 [   64     2   703]]

Precision: 0.9725354337788019
Recall: 0.93956
F1 Score: 0.9515965226879721
98 94.909
-----------------------------------------


Train Accuracy: 92.25%
Confusion Matrix:
[[7569  121   86]
 [ 943 6615  218]
 [ 338  103 7335]]
Epoch: 1362, Train Loss: 0.628731
-----------------------------------------
Valid Accuracy:

<All keys matched successfully>

In [131]:
Cf.load_state_dict(torch.load('cnn10.pt'))

<All keys matched successfully>

In [132]:
valid_latents = []
VR,VL = [], []
valid_loss = 0.0
for j, (inp, lab) in enumerate(train_loader):
    probability = 0.0
    coin_toss = random.random()  

    if coin_toss < probability:
        continue
    inp = inp.to(device)
    lab = lab.to(device)

    with torch.no_grad():
        # Forward pass
        outp = Cf(inp)

    VR.append(outp)
    VL.append(lab)

VR = torch.cat(VR, dim=0)
VL = torch.cat(VL, dim=0)
_, vpre = torch.max(VR.data, 1)
_, vlbl = torch.max(VL.data, 1)
total = vlbl.size(0)
correct = (vpre == vlbl).sum().item()

vaccuracy = 100 * correct / total
print('-----------------------------------------')
print(f'Train Accuracy: {vaccuracy:.2f}%')
lb = vlbl.cpu().detach().numpy()
pre = vpre.cpu().detach().numpy()
conf_matrix = confusion_matrix(lb,pre)
precision = precision_score(lb, pre,average=avg)
recall = recall_score(lb, pre,average=avg)
f1 = f1_score(lb, pre,average=avg)
print('Confusion Matrix:')
print(conf_matrix)
print()
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print(epochs_without_improvement, best_loss)
print('-----------------------------------------')
print()
print()

valid_latents = []
VR,VL = [], []
valid_loss = 0.0
for j, (inp, lab) in enumerate(valid_loader):
    probability = 0.0
    coin_toss = random.random()  

    if coin_toss < probability:
        continue
    inp = inp.to(device)
    lab = lab.to(device)

    with torch.no_grad():
        # Forward pass
        outp = Cf(inp)

    VR.append(outp)
    VL.append(lab)

VR = torch.cat(VR, dim=0)
VL = torch.cat(VL, dim=0)
_, vpre = torch.max(VR.data, 1)
_, vlbl = torch.max(VL.data, 1)
total = vlbl.size(0)
correct = (vpre == vlbl).sum().item()

vaccuracy = 100 * correct / total
print('-----------------------------------------')
print(f'Valid Accuracy: {vaccuracy:.2f}%')
lb = vlbl.cpu().detach().numpy()
pre = vpre.cpu().detach().numpy()
conf_matrix = confusion_matrix(lb,pre)
precision = precision_score(lb, pre,average=avg)
recall = recall_score(lb, pre,average=avg)
f1 = f1_score(lb, pre,average=avg)
print('Confusion Matrix:')
print(conf_matrix)
print()
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print(epochs_without_improvement, best_loss)
print('-----------------------------------------')
print()
print()

valid_latents = []
VR,VL = [], []
valid_loss = 0.0
for j, (inp, lab) in enumerate(test_loader):
    probability = 0.0
    coin_toss = random.random()  

    if coin_toss < probability:
        continue
    inp = inp.to(device)
    lab = lab.to(device)

    with torch.no_grad():
        # Forward pass
        outp = Cf(inp)

    VR.append(outp)
    VL.append(lab)

VR = torch.cat(VR, dim=0)
VL = torch.cat(VL, dim=0)
_, vpre = torch.max(VR.data, 1)
_, vlbl = torch.max(VL.data, 1)
total = vlbl.size(0)
correct = (vpre == vlbl).sum().item()

vaccuracy = 100 * correct / total
print('-----------------------------------------')
print(f'Test Accuracy: {vaccuracy:.2f}%')
lb = vlbl.cpu().detach().numpy()
pre = vpre.cpu().detach().numpy()
conf_matrix = confusion_matrix(lb,pre)
precision = precision_score(lb, pre,average=avg)
recall = recall_score(lb, pre,average=avg)
f1 = f1_score(lb, pre,average=avg)
print('Confusion Matrix:')
print(conf_matrix)
print()
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print(epochs_without_improvement, best_loss)
print('-----------------------------------------')
print()
print()

-----------------------------------------
Train Accuracy: 92.23%
Confusion Matrix:
[[7565  122   89]
 [1000 6615  161]
 [ 441    0 7335]]

Precision: 0.9296422729625746
Recall: 0.9222822359396433
F1 Score: 0.9227245485641565
100 94.909
-----------------------------------------


-----------------------------------------
Valid Accuracy: 94.91%
Confusion Matrix:
[[91971  3359  1152]
 [  370  2313    66]
 [  141     3   625]]

Precision: 0.9733011187691218
Recall: 0.94909
F1 Score: 0.9579546046267547
100 94.909
-----------------------------------------


-----------------------------------------
Test Accuracy: 95.84%
Confusion Matrix:
[[153556   4537   1506]
 [   541   2913     57]
 [   177      7    788]]

Precision: 0.9784957801373904
Recall: 0.9584049438695287
F1 Score: 0.9659019124394538
100 94.909
-----------------------------------------


