In [1]:
seed=197

In [2]:
# importing required libraries
import torch.nn as nn
import torch
import torch.nn.functional as F
import math,copy,re
import warnings
import pandas as pd
import numpy as np
import random
import pickle
import torch.nn.init as init
from torchviz import make_dot
import plotly.graph_objects as go
import pickle
# import seaborn as sns
# import torchtext
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import torch.nn.functional as F
import torch.optim as optim
from IPython.display import display
import matplotlib.pyplot as plt
import os 
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

warnings.simplefilter("ignore")
print(torch.__version__)

1.13.1+cu117


In [3]:
# Check if CUDA is available
if torch.cuda.is_available():
    # CUDA is available, so PyTorch can use a GPU
    device = torch.device("cuda")
    print("PyTorch is using GPU.")
else:
    # CUDA is not available, PyTorch will use CPU
    device = torch.device("cpu")
    print("PyTorch is using CPU.")

# Create a tensor and move it to the device
tensor = torch.randn(3, 4).to(device)

# Check the device of the tensor
print("Tensor device:", tensor.device)

PyTorch is using GPU.
Tensor device: cuda:0


In [4]:
def reset_random_seeds(seed):
    os.environ['PYTHONHASHSEED']=str(seed)
#     tf.random.set_seed(seed)
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

In [5]:
# pickle_file_path = '/media/terminator/Data/NatureData/Auto Ten Minutes.pkl'
pickle_file_path = '/media/terminator/NatureData/Thirty Minutes.pkl'

In [6]:
# Load data from the pickle file
with open(pickle_file_path, "rb") as f:
    loaded_data_dict = pickle.load(f)


In [7]:
# Retrieve data and labels
X_train = loaded_data_dict["X_train"]
y_train = loaded_data_dict["y_train"]
X_test = loaded_data_dict["X_test"]
y_test = loaded_data_dict["y_test"]

In [8]:
X_train.shape,y_train.shape

(torch.Size([23328, 144, 13]), torch.Size([23328, 3]))

In [9]:
features=13

In [10]:
def reconstructData(packets):
    # Take the first packet
    first_packet = packets[0]
    
    # Concatenate the last index of every packet
    reconstructed_data = np.concatenate([packet[-1:] for packet in packets[1:]])
    
    # Combine the first packet with the concatenated data
    reconstructed_data = np.concatenate([first_packet, reconstructed_data])
    
    return reconstructed_data

In [11]:
Valid,Test = X_test[:100000],X_test[100000:]
Valid_label,Test_label = y_test[:100000],y_test[100000:]

In [12]:
num_epochs = 500
# Define batch size
batch_size = 256
# Create DataLoader for training set
train_dataset = torch.utils.data.TensorDataset(X_train.float(), y_train.float())
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
valid_dataset = torch.utils.data.TensorDataset(Valid.float(), Valid_label.float())
valid_loader = torch.utils.data.DataLoader(valid_dataset, batch_size=batch_size, shuffle=False)
test_dataset = torch.utils.data.TensorDataset(Test.float(), Test_label.float())
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [13]:
print(X_train.dtype)
print(y_train.dtype)

torch.float64
torch.float64


In [14]:
X_train.shape, y_train.shape

(torch.Size([23328, 144, 13]), torch.Size([23328, 3]))

In [15]:
import torch
import torch.nn as nn

class TimeSeriesEncoder(nn.Module):
    def __init__(self, input_channels):
        super(TimeSeriesEncoder, self).__init__()
        
        self.encoder = nn.Sequential(
            nn.Conv1d(input_channels, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2, stride=1),  # Reduce sequence length to 36 / 4 = 9
            nn.Conv1d(128, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2, stride=1)  # Reduce sequence length to 9 / 2 = 4.5 (rounded to 4)
        )
        self.classifier = nn.Sequential(
            nn.Linear(64*142, 1024),
            nn.ReLU(), 
            nn.Linear(1024, 3), 
            nn.Softmax(dim=1)  
        )
        
    
    def forward(self, x):
        x = x.permute(0,2,1)
        x = self.encoder(x)
#         print(x.shape)
        x = torch.reshape(x,(x.shape[0],-1))
        x = self.classifier(x)
#         x = x.permute(0,2,1)
        return x

# Create the autoencoder model
input_channels = 13  # Number of input features
# encoder = TimeSeriesEncoder(input_channels).to(device)





In [16]:
train = 1
avg = 'weighted'
seq_length = 144
num_epochs = 5000
reset_random_seeds(seed)
src_vocab_size = features+5
target_vocab_size = features
num_layers = 2
latent_dim = 8
embed_dim = 128
n_heads = 8
expansion_factor = 2

Cf = TimeSeriesEncoder(input_channels).to(device)

criterion = nn.CrossEntropyLoss()
optimizer_cf = optim.Adam(Cf.parameters(), lr=0.00001)

# Define early stopping parameters
patience = 100
best_loss = 0
epochs_without_improvement = 0

if train:
    # Step 4: Training loop
    for epoch in range(num_epochs):
        running_loss = 0.0
        latents = []
        PR, PL = [], []
        train_input,train_output = [], []

        # Iterate over mini-batches
        for i, (inputs, labels) in enumerate(train_loader):
            
            probability = 0.0
            coin_toss = random.random()  

            if coin_toss < probability:
                continue
            
            # Clear gradients
            optimizer_cf.zero_grad()
            inputs = inputs.to(device)
            labels = labels.to(device)
            
            # Forward pass
            
            prediction = Cf(inputs)
            
            
            # Calculate loss
            loss = criterion(prediction, labels)
            loss = loss.float()

            # Backpropagation
            loss.backward()
            
            optimizer_cf.step()
            
            # Update running loss
            running_loss += loss.item()
            
            
            PR.append(prediction)
            PL.append(labels)
            

        # Calculate average loss per epoch
        PR = torch.cat(PR, dim=0)
        PL = torch.cat(PL, dim=0)
        _, predicted = torch.max(PR.data, 1)
        _, lbl = torch.max(PL.data, 1)
        total = lbl.size(0)
        correct = (predicted == lbl).sum().item()

        accuracy = 100 * correct / total
        print(f'Train Accuracy: {accuracy:.2f}%')
        conf_matrix = confusion_matrix(lbl.cpu().detach().numpy(),predicted.cpu().detach().numpy())
        print('Confusion Matrix:')
        print(conf_matrix)
        # Calculate average loss per epoch
        epoch_loss = running_loss / len(train_loader)
        print(f"Epoch: {epoch+1}, Train Loss: {round(epoch_loss,6)}")
        
        if epoch%1==0:
            valid_latents = []
            VR,VL = [], []
            valid_loss = 0.0
            for j, (inp, lab) in enumerate(valid_loader):
                probability = 0.0
                coin_toss = random.random()  

                if coin_toss < probability:
                    continue
                inp = inp.to(device)
                lab = lab.to(device)
                
                with torch.no_grad():
                    # Forward pass
                    outp = Cf(inp)
                    
                VR.append(outp)
                VL.append(lab)
            
            VR = torch.cat(VR, dim=0)
            VL = torch.cat(VL, dim=0)
            _, vpre = torch.max(VR.data, 1)
            _, vlbl = torch.max(VL.data, 1)
            total = vlbl.size(0)
            correct = (vpre == vlbl).sum().item()

            vaccuracy = 100 * correct / total
            print('-----------------------------------------')
            print(f'Valid Accuracy: {vaccuracy:.2f}%')
            lb = vlbl.cpu().detach().numpy()
            pre = vpre.cpu().detach().numpy()
            conf_matrix = confusion_matrix(lb,pre)
            precision = precision_score(lb, pre,average=avg)
            recall = recall_score(lb, pre,average=avg)
            f1 = f1_score(lb, pre,average=avg)
            print('Confusion Matrix:')
            print(conf_matrix)
            print()
            print("Precision:", precision)
            print("Recall:", recall)
            print("F1 Score:", f1)
            print(epochs_without_improvement, best_loss)
            print('-----------------------------------------')
            print()
            print()
            
                
                    
        # Check for early stopping and save the best weights
        th = (conf_matrix[0][0]> conf_matrix[0][1]+conf_matrix[0][2] and conf_matrix[1][1]>conf_matrix[1][0]+conf_matrix[1][2] and conf_matrix[2][2]>conf_matrix[2][0]+conf_matrix[2][1])
        if th and vaccuracy > best_loss:
            best_loss = vaccuracy
            epochs_without_improvement = 0
            # Save the model weights
            torch.save(Cf.state_dict(), 'cnn30.pt')
            print('##############################################')
            print('saved', best_loss)
            print('##############################################')
            print()
            print()
            
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                print("Early stopping triggered. Training stopped.")
                break

# Recover the best weights
Cf.load_state_dict(torch.load('cnn30.pt'))


Train Accuracy: 48.70%
Confusion Matrix:
[[4328   11 3437]
 [2149   20 5607]
 [ 751   13 7012]]
Epoch: 1, Train Loss: 1.078529
-----------------------------------------
Valid Accuracy: 51.84%
Confusion Matrix:
[[51102     0 45380]
 [  666     0  2083]
 [   26     0   743]]

Precision: 0.9520479318397514
Recall: 0.51845
F1 Score: 0.6652665335517525
0 0
-----------------------------------------


Train Accuracy: 50.87%
Confusion Matrix:
[[4329    3 3444]
 [1834   15 5927]
 [ 253    0 7523]]
Epoch: 2, Train Loss: 1.024517
-----------------------------------------
Valid Accuracy: 52.23%
Confusion Matrix:
[[51484    25 44973]
 [  684     1  2064]
 [   26     0   743]]

Precision: 0.9528723513531063
Recall: 0.52228
F1 Score: 0.6684570905748074
1 0
-----------------------------------------


Train Accuracy: 53.91%
Confusion Matrix:
[[4331  289 3156]
 [1831  732 5213]
 [ 254    8 7514]]
Epoch: 3, Train Loss: 0.990923
-----------------------------------------
Valid Accuracy: 52.84%
Confusion Ma

Train Accuracy: 74.72%
Confusion Matrix:
[[5308 2010  458]
 [2409 4698  669]
 [ 103  248 7425]]
Epoch: 19, Train Loss: 0.802987
-----------------------------------------
Valid Accuracy: 67.86%
Confusion Matrix:
[[65519 24749  6214]
 [  882  1606   261]
 [   11    23   735]]

Precision: 0.9543043131347378
Recall: 0.6786
F1 Score: 0.7805853744264426
0 67.715
-----------------------------------------


##############################################
saved 67.86
##############################################


Train Accuracy: 74.90%
Confusion Matrix:
[[5340 1986  450]
 [2407 4706  663]
 [ 102  248 7426]]
Epoch: 20, Train Loss: 0.799173
-----------------------------------------
Valid Accuracy: 67.95%
Confusion Matrix:
[[65613 24700  6169]
 [  885  1603   261]
 [   11    23   735]]

Precision: 0.9542848110608722
Recall: 0.67951
F1 Score: 0.7812441202420065
0 67.86
-----------------------------------------


##############################################
saved 67.951
##########################

Train Accuracy: 79.63%
Confusion Matrix:
[[5334 2082  360]
 [1516 5823  437]
 [ 107  250 7419]]
Epoch: 39, Train Loss: 0.758911
-----------------------------------------
Valid Accuracy: 67.15%
Confusion Matrix:
[[64384 27501  4597]
 [  546  2033   170]
 [   11    24   734]]

Precision: 0.9594615651658583
Recall: 0.67151
F1 Score: 0.7749023530945374
18 67.951
-----------------------------------------


Train Accuracy: 79.77%
Confusion Matrix:
[[5338 2081  357]
 [1490 5854  432]
 [ 108  251 7417]]
Epoch: 40, Train Loss: 0.757745
-----------------------------------------
Valid Accuracy: 67.18%
Confusion Matrix:
[[64410 27514  4558]
 [  546  2040   163]
 [   11    24   734]]

Precision: 0.9594787568583902
Recall: 0.67184
F1 Score: 0.7751122324971956
19 67.951
-----------------------------------------


Train Accuracy: 79.93%
Confusion Matrix:
[[5338 2081  357]
 [1472 5884  420]
 [ 110  243 7423]]
Epoch: 41, Train Loss: 0.756625
-----------------------------------------
Valid Accuracy: 67.1

Train Accuracy: 81.67%
Confusion Matrix:
[[5450 2008  318]
 [1255 6136  385]
 [ 129  180 7467]]
Epoch: 59, Train Loss: 0.741217
-----------------------------------------
Valid Accuracy: 68.04%
Confusion Matrix:
[[65151 27206  4125]
 [  440  2153   156]
 [   11    20   738]]

Precision: 0.961332379092295
Recall: 0.68042
F1 Score: 0.781280121007476
0 67.98
-----------------------------------------


##############################################
saved 68.042
##############################################


Train Accuracy: 81.83%
Confusion Matrix:
[[5462 1997  317]
 [1245 6151  380]
 [ 131  169 7476]]
Epoch: 60, Train Loss: 0.740348
-----------------------------------------
Valid Accuracy: 68.09%
Confusion Matrix:
[[65176 27191  4115]
 [  429  2175   145]
 [   11    19   739]]

Precision: 0.9615217708081711
Recall: 0.6809
F1 Score: 0.7815571545996275
0 68.042
-----------------------------------------


##############################################
saved 68.09
############################

-----------------------------------------
Valid Accuracy: 69.62%
Confusion Matrix:
[[66681 25775  4026]
 [  431  2198   120]
 [   11    19   739]]

Precision: 0.9617886520525872
Recall: 0.69618
F1 Score: 0.7924107212422351
0 69.436
-----------------------------------------


##############################################
saved 69.618
##############################################


Train Accuracy: 83.29%
Confusion Matrix:
[[5661 1821  294]
 [1186 6275  315]
 [ 173  110 7493]]
Epoch: 76, Train Loss: 0.728704
-----------------------------------------
Valid Accuracy: 69.75%
Confusion Matrix:
[[66808 25644  4030]
 [  431  2198   120]
 [   11    19   739]]

Precision: 0.9618098477092543
Recall: 0.69745
F1 Score: 0.7933128329982782
0 69.618
-----------------------------------------


##############################################
saved 69.745
##############################################


Train Accuracy: 83.36%
Confusion Matrix:
[[5674 1809  293]
 [1181 6280  315]
 [ 176  107 7493]]
Epoch:

Train Accuracy: 84.07%
Confusion Matrix:
[[5793 1699  284]
 [1144 6317  315]
 [ 194   80 7502]]
Epoch: 92, Train Loss: 0.719048
-----------------------------------------
Valid Accuracy: 70.76%
Confusion Matrix:
[[67817 24779  3886]
 [  422  2207   120]
 [   13    16   740]]

Precision: 0.9621166952888509
Recall: 0.70764
F1 Score: 0.8005283043659208
1 70.762
-----------------------------------------


##############################################
saved 70.764
##############################################


Train Accuracy: 84.12%
Confusion Matrix:
[[5803 1689  284]
 [1143 6318  315]
 [ 199   75 7502]]
Epoch: 93, Train Loss: 0.71853
-----------------------------------------
Valid Accuracy: 70.78%
Confusion Matrix:
[[67835 24764  3883]
 [  422  2207   120]
 [   13    16   740]]

Precision: 0.9621203238584114
Recall: 0.70782
F1 Score: 0.8006555172449072
0 70.764
-----------------------------------------


##############################################
saved 70.782
########################

Train Accuracy: 84.85%
Confusion Matrix:
[[5926 1571  279]
 [1117 6344  315]
 [ 228   25 7523]]
Epoch: 110, Train Loss: 0.710223
-----------------------------------------
Valid Accuracy: 71.25%
Confusion Matrix:
[[68283 24341  3858]
 [  400  2228   121]
 [   13    15   741]]

Precision: 0.9625307036225036
Recall: 0.71252
F1 Score: 0.8039469437343411
0 71.194
-----------------------------------------


##############################################
saved 71.252
##############################################


Train Accuracy: 84.88%
Confusion Matrix:
[[5931 1565  280]
 [1115 6346  315]
 [ 230   23 7523]]
Epoch: 111, Train Loss: 0.709826
-----------------------------------------
Valid Accuracy: 71.32%
Confusion Matrix:
[[68347 24275  3860]
 [  400  2228   121]
 [   13    15   741]]

Precision: 0.9625413254316328
Recall: 0.71316
F1 Score: 0.8043940194332354
0 71.252
-----------------------------------------


##############################################
saved 71.316
#####################

Train Accuracy: 85.33%
Confusion Matrix:
[[6013 1501  262]
 [1091 6370  315]
 [ 233   20 7523]]
Epoch: 126, Train Loss: 0.704459
-----------------------------------------
Valid Accuracy: 72.08%
Confusion Matrix:
[[69110 23633  3739]
 [  398  2230   121]
 [   14    14   741]]

Precision: 0.9627097942506354
Recall: 0.72081
F1 Score: 0.809743873270599
0 72.051
-----------------------------------------


##############################################
saved 72.081
##############################################


Train Accuracy: 85.37%
Confusion Matrix:
[[6020 1495  261]
 [1090 6371  315]
 [ 233   20 7523]]
Epoch: 127, Train Loss: 0.704131
-----------------------------------------
Valid Accuracy: 72.11%
Confusion Matrix:
[[69135 23615  3732]
 [  398  2230   121]
 [   12    16   741]]

Precision: 0.9627427846564806
Recall: 0.72106
F1 Score: 0.8099283119148749
0 72.081
-----------------------------------------


##############################################
saved 72.106
######################

Train Accuracy: 85.82%
Confusion Matrix:
[[6088 1446  242]
 [1074 6410  292]
 [ 227   26 7523]]
Epoch: 143, Train Loss: 0.698366
-----------------------------------------
Valid Accuracy: 72.79%
Confusion Matrix:
[[69794 23384  3304]
 [  382  2254   113]
 [   12    16   741]]

Precision: 0.9631897414828856
Recall: 0.72789
F1 Score: 0.8147237837102201
0 72.727
-----------------------------------------


##############################################
saved 72.789
##############################################


Train Accuracy: 85.89%
Confusion Matrix:
[[6095 1440  241]
 [1068 6418  290]
 [ 227   26 7523]]
Epoch: 144, Train Loss: 0.698038
-----------------------------------------
Valid Accuracy: 72.86%
Confusion Matrix:
[[69869 23301  3312]
 [  382  2254   113]
 [   12    16   741]]

Precision: 0.9632007307478302
Recall: 0.72864
F1 Score: 0.8152373008102852
0 72.789
-----------------------------------------


##############################################
saved 72.864
#####################

Train Accuracy: 86.27%
Confusion Matrix:
[[6162 1380  234]
 [1061 6441  274]
 [ 219   34 7523]]
Epoch: 159, Train Loss: 0.69382
-----------------------------------------
Valid Accuracy: 73.94%
Confusion Matrix:
[[70940 22253  3289]
 [  377  2259   113]
 [   12    16   741]]

Precision: 0.963465454012846
Recall: 0.7394
F1 Score: 0.8226045901634109
0 73.875
-----------------------------------------


##############################################
saved 73.94
##############################################


Train Accuracy: 86.31%
Confusion Matrix:
[[6169 1373  234]
 [1060 6442  274]
 [ 219   34 7523]]
Epoch: 160, Train Loss: 0.693571
-----------------------------------------
Valid Accuracy: 74.07%
Confusion Matrix:
[[71067 22126  3289]
 [  377  2259   113]
 [   12    16   741]]

Precision: 0.9634879830580058
Recall: 0.74067
F1 Score: 0.8234682620320338
0 73.94
-----------------------------------------


##############################################
saved 74.067
##########################

Train Accuracy: 86.65%
Confusion Matrix:
[[6238 1306  232]
 [1054 6453  269]
 [ 218   35 7523]]
Epoch: 175, Train Loss: 0.690096
-----------------------------------------
Valid Accuracy: 75.38%
Confusion Matrix:
[[72375 20968  3139]
 [  383  2260   106]
 [   13    15   741]]

Precision: 0.9636722388478138
Recall: 0.75376
F1 Score: 0.8323188810956902
0 75.231
-----------------------------------------


##############################################
saved 75.376
##############################################


Train Accuracy: 86.68%
Confusion Matrix:
[[6242 1302  232]
 [1052 6456  268]
 [ 218   35 7523]]
Epoch: 176, Train Loss: 0.689864
-----------------------------------------
Valid Accuracy: 75.46%
Confusion Matrix:
[[72458 20890  3134]
 [  383  2260   106]
 [   13    15   741]]

Precision: 0.9636890160386241
Recall: 0.75459
F1 Score: 0.8328771627140089
0 75.376
-----------------------------------------


##############################################
saved 75.459
#####################

Train Accuracy: 86.96%
Confusion Matrix:
[[6296 1253  227]
 [1040 6468  268]
 [ 224   29 7523]]
Epoch: 191, Train Loss: 0.68672
-----------------------------------------
Valid Accuracy: 76.75%
Confusion Matrix:
[[73750 19736  2996]
 [  380  2263   106]
 [   13    15   741]]

Precision: 0.9640146004757355
Recall: 0.76754
F1 Score: 0.8415523420478135
0 76.661
-----------------------------------------


##############################################
saved 76.754
##############################################


Train Accuracy: 86.98%
Confusion Matrix:
[[6300 1250  226]
 [1041 6468  267]
 [ 224   29 7523]]
Epoch: 192, Train Loss: 0.686528
-----------------------------------------
Valid Accuracy: 76.83%
Confusion Matrix:
[[73825 19671  2986]
 [  380  2263   106]
 [   13    15   741]]

Precision: 0.9640320056080389
Recall: 0.76829
F1 Score: 0.8420522982612393
0 76.754
-----------------------------------------


##############################################
saved 76.829
######################

Train Accuracy: 87.18%
Confusion Matrix:
[[6338 1218  220]
 [1039 6477  260]
 [ 212   41 7523]]
Epoch: 207, Train Loss: 0.683821
-----------------------------------------
Valid Accuracy: 77.86%
Confusion Matrix:
[[74853 18750  2879]
 [  377  2266   106]
 [   13    15   741]]

Precision: 0.9643104000459416
Recall: 0.7786
F1 Score: 0.8488828604816809
0 77.833
-----------------------------------------


##############################################
saved 77.86
##############################################


Train Accuracy: 87.19%
Confusion Matrix:
[[6339 1217  220]
 [1039 6477  260]
 [ 212   41 7523]]
Epoch: 208, Train Loss: 0.683645
-----------------------------------------
Valid Accuracy: 77.89%
Confusion Matrix:
[[74886 18727  2869]
 [  380  2266   103]
 [   13    15   741]]

Precision: 0.9642829390932419
Recall: 0.77893
F1 Score: 0.8490897323421779
0 77.86
-----------------------------------------


##############################################
saved 77.893
########################

Train Accuracy: 87.41%
Confusion Matrix:
[[6380 1183  213]
 [1024 6488  264]
 [ 212   41 7523]]
Epoch: 223, Train Loss: 0.681113
-----------------------------------------
Valid Accuracy: 78.77%
Confusion Matrix:
[[75759 17895  2828]
 [  374  2269   106]
 [   24     4   741]]

Precision: 0.9644211225181386
Recall: 0.78769
F1 Score: 0.8547900221184376
0 78.689
-----------------------------------------


##############################################
saved 78.769
##############################################


Train Accuracy: 87.43%
Confusion Matrix:
[[6385 1178  213]
 [1024 6488  264]
 [ 212   41 7523]]
Epoch: 224, Train Loss: 0.680957
-----------------------------------------
Valid Accuracy: 78.86%
Confusion Matrix:
[[75852 17804  2826]
 [  374  2269   106]
 [   25     3   741]]

Precision: 0.9644297023201979
Recall: 0.78862
F1 Score: 0.8553912298343179
0 78.769
-----------------------------------------


##############################################
saved 78.862
#####################

Train Accuracy: 87.65%
Confusion Matrix:
[[6437 1130  209]
 [1024 6488  264]
 [ 207   46 7523]]
Epoch: 239, Train Loss: 0.678413
-----------------------------------------
Valid Accuracy: 79.89%
Confusion Matrix:
[[76888 16776  2818]
 [  377  2266   106]
 [   27     1   741]]

Precision: 0.9646028787325254
Recall: 0.79895
F1 Score: 0.8620752875588095
0 79.836
-----------------------------------------


##############################################
saved 79.895
##############################################


Train Accuracy: 87.67%
Confusion Matrix:
[[6440 1127  209]
 [1024 6488  264]
 [ 207   46 7523]]
Epoch: 240, Train Loss: 0.678234
-----------------------------------------
Valid Accuracy: 79.92%
Confusion Matrix:
[[76915 16749  2818]
 [  377  2266   106]
 [   27     1   741]]

Precision: 0.964609284330803
Recall: 0.79922
F1 Score: 0.8622495133177113
0 79.895
-----------------------------------------


##############################################
saved 79.922
######################

-----------------------------------------
Valid Accuracy: 80.16%
Confusion Matrix:
[[77154 16496  2832]
 [  374  2269   106]
 [   27     1   741]]

Precision: 0.9647040643599432
Recall: 0.80164
F1 Score: 0.8638075296721118
4 80.173
-----------------------------------------


Train Accuracy: 87.92%
Confusion Matrix:
[[6496 1073  207]
 [1022 6490  264]
 [ 208   45 7523]]
Epoch: 257, Train Loss: 0.675258
-----------------------------------------
Valid Accuracy: 80.17%
Confusion Matrix:
[[77155 16495  2832]
 [  374  2269   106]
 [   27     1   741]]

Precision: 0.9647043058115289
Recall: 0.80165
F1 Score: 0.8638139713577955
5 80.173
-----------------------------------------


Train Accuracy: 87.94%
Confusion Matrix:
[[6501 1068  207]
 [1022 6490  264]
 [ 209   44 7523]]
Epoch: 258, Train Loss: 0.675099
-----------------------------------------
Valid Accuracy: 80.19%
Confusion Matrix:
[[77185 16451  2846]
 [  374  2269   106]
 [   27     1   741]]

Precision: 0.9647081754287691
Recall: 0.80

Train Accuracy: 88.18%
Confusion Matrix:
[[6555 1018  203]
 [1026 6493  257]
 [ 198   55 7523]]
Epoch: 273, Train Loss: 0.672807
-----------------------------------------
Valid Accuracy: 80.50%
Confusion Matrix:
[[77485 16137  2860]
 [  374  2269   106]
 [   13    15   741]]

Precision: 0.9649483809805686
Recall: 0.80495
F1 Score: 0.8659939703453238
0 80.469
-----------------------------------------


##############################################
saved 80.495
##############################################


Train Accuracy: 88.19%
Confusion Matrix:
[[6557 1016  203]
 [1026 6493  257]
 [ 198   55 7523]]
Epoch: 274, Train Loss: 0.672652
-----------------------------------------
Valid Accuracy: 80.51%
Confusion Matrix:
[[77502 16124  2856]
 [  374  2269   106]
 [   13    15   741]]

Precision: 0.9649534792557001
Recall: 0.80512
F1 Score: 0.8661043896612471
0 80.495
-----------------------------------------


##############################################
saved 80.512
#####################

-----------------------------------------
Valid Accuracy: 80.89%
Confusion Matrix:
[[77873 15765  2844]
 [  369  2274   106]
 [   13    15   741]]

Precision: 0.9651166025821566
Recall: 0.80888
F1 Score: 0.8685253586265681
0 80.84
-----------------------------------------


##############################################
saved 80.888
##############################################


Train Accuracy: 88.45%
Confusion Matrix:
[[6610  965  201]
 [1020 6500  256]
 [ 201   52 7523]]
Epoch: 290, Train Loss: 0.670047
-----------------------------------------
Valid Accuracy: 80.94%
Confusion Matrix:
[[77923 15715  2844]
 [  369  2274   106]
 [   13    15   741]]

Precision: 0.9651292258538275
Recall: 0.80938
F1 Score: 0.8688458335418071
0 80.888
-----------------------------------------


##############################################
saved 80.938
##############################################


Train Accuracy: 88.47%
Confusion Matrix:
[[6614  961  201]
 [1020 6501  255]
 [ 200   53 7523]]
Epoch:

Train Accuracy: 88.62%
Confusion Matrix:
[[6647  932  197]
 [1018 6503  255]
 [ 200   53 7523]]
Epoch: 306, Train Loss: 0.667717
-----------------------------------------
Valid Accuracy: 81.36%
Confusion Matrix:
[[78347 15327  2808]
 [  369  2274   106]
 [   13    15   741]]

Precision: 0.9652462555187925
Recall: 0.81362
F1 Score: 0.871569225725779
0 81.35
-----------------------------------------


##############################################
saved 81.362
##############################################


Train Accuracy: 88.63%
Confusion Matrix:
[[6650  929  197]
 [1019 6503  254]
 [ 199   54 7523]]
Epoch: 307, Train Loss: 0.667579
-----------------------------------------
Valid Accuracy: 81.38%
Confusion Matrix:
[[78364 15314  2804]
 [  369  2274   106]
 [   13    15   741]]

Precision: 0.9652515949082293
Recall: 0.81379
F1 Score: 0.87167897427725
0 81.362
-----------------------------------------


##############################################
saved 81.379
#########################

Train Accuracy: 88.83%
Confusion Matrix:
[[6695  886  195]
 [1014 6504  258]
 [ 206   47 7523]]
Epoch: 322, Train Loss: 0.665336
-----------------------------------------
Valid Accuracy: 82.32%
Confusion Matrix:
[[79302 14386  2794]
 [  369  2274   106]
 [   13    15   741]]

Precision: 0.9655086101234029
Recall: 0.82317
F1 Score: 0.8776578900220326
0 82.271
-----------------------------------------


##############################################
saved 82.317
##############################################


Train Accuracy: 88.85%
Confusion Matrix:
[[6700  881  195]
 [1013 6504  259]
 [ 203   50 7523]]
Epoch: 323, Train Loss: 0.665188
-----------------------------------------
Valid Accuracy: 82.39%
Confusion Matrix:
[[79377 14311  2794]
 [  369  2274   106]
 [   13    15   741]]

Precision: 0.9655298970564977
Recall: 0.82392
F1 Score: 0.8781343530546782
0 82.317
-----------------------------------------


##############################################
saved 82.392
#####################

-----------------------------------------
Valid Accuracy: 83.03%
Confusion Matrix:
[[80016 13659  2807]
 [  369  2277   103]
 [   13    15   741]]

Precision: 0.9657207271325529
Recall: 0.83034
F1 Score: 0.8821929484555829
0 82.914
-----------------------------------------


##############################################
saved 83.034
##############################################


Train Accuracy: 89.12%
Confusion Matrix:
[[6751  828  197]
 [1008 6517  251]
 [ 197   56 7523]]
Epoch: 339, Train Loss: 0.662398
-----------------------------------------
Valid Accuracy: 83.12%
Confusion Matrix:
[[80103 13584  2795]
 [  369  2277   103]
 [   13    15   741]]

Precision: 0.965749367459879
Recall: 0.83121
F1 Score: 0.8827464275855994
0 83.034
-----------------------------------------


##############################################
saved 83.121
##############################################


Train Accuracy: 89.12%
Confusion Matrix:
[[6750  829  197]
 [1008 6517  251]
 [ 196   57 7523]]
Epoch:

-----------------------------------------
Valid Accuracy: 84.07%
Confusion Matrix:
[[81047 12662  2773]
 [  366  2280   103]
 [   27     1   741]]

Precision: 0.9659339651026081
Recall: 0.84068
F1 Score: 0.8886730648829556
0 84.045
-----------------------------------------


##############################################
saved 84.068
##############################################


Train Accuracy: 89.40%
Confusion Matrix:
[[6807  776  193]
 [1000 6525  251]
 [ 199   54 7523]]
Epoch: 355, Train Loss: 0.659996
-----------------------------------------
Valid Accuracy: 84.08%
Confusion Matrix:
[[81062 12648  2772]
 [  366  2280   103]
 [   27     1   741]]

Precision: 0.9659391915740677
Recall: 0.84083
F1 Score: 0.8887678380002281
0 84.068
-----------------------------------------


##############################################
saved 84.083
##############################################


Train Accuracy: 89.41%
Confusion Matrix:
[[6809  774  193]
 [1000 6525  251]
 [ 200   53 7523]]
Epoch

Train Accuracy: 89.62%
Confusion Matrix:
[[6842  744  190]
 [ 984 6542  250]
 [ 206   47 7523]]
Epoch: 371, Train Loss: 0.657526
-----------------------------------------
Valid Accuracy: 84.60%
Confusion Matrix:
[[81570 12182  2730]
 [  360  2286   103]
 [   15    13   741]]

Precision: 0.9663387523166186
Recall: 0.84597
F1 Score: 0.8920762327418584
0 84.585
-----------------------------------------


##############################################
saved 84.597
##############################################


Train Accuracy: 89.63%
Confusion Matrix:
[[6843  743  190]
 [ 985 6542  249]
 [ 207   46 7523]]
Epoch: 372, Train Loss: 0.657374
-----------------------------------------
Valid Accuracy: 84.60%
Confusion Matrix:
[[81577 12178  2727]
 [  360  2286   103]
 [   15    13   741]]

Precision: 0.9663416679234954
Recall: 0.84604
F1 Score: 0.8921208334245195
0 84.597
-----------------------------------------


##############################################
saved 84.604
#####################

Train Accuracy: 89.92%
Confusion Matrix:
[[6891  699  186]
 [ 986 6563  227]
 [ 199   54 7523]]
Epoch: 388, Train Loss: 0.654544
-----------------------------------------
Valid Accuracy: 85.00%
Confusion Matrix:
[[81966 11841  2675]
 [  360  2293    96]
 [   13    15   741]]

Precision: 0.9665268893684054
Recall: 0.85
F1 Score: 0.894609851017732
0 84.946
-----------------------------------------


##############################################
saved 85.0
##############################################


Train Accuracy: 89.93%
Confusion Matrix:
[[6892  698  186]
 [ 987 6563  226]
 [ 199   54 7523]]
Epoch: 389, Train Loss: 0.654428
-----------------------------------------
Valid Accuracy: 85.02%
Confusion Matrix:
[[81989 11815  2678]
 [  360  2293    96]
 [   13    15   741]]

Precision: 0.9665349267236915
Recall: 0.85023
F1 Score: 0.894753894193903
0 85.0
-----------------------------------------


##############################################
saved 85.023
##############################

Train Accuracy: 90.08%
Confusion Matrix:
[[6929  662  185]
 [ 982 6563  231]
 [ 207   46 7523]]
Epoch: 407, Train Loss: 0.652462
-----------------------------------------
Valid Accuracy: 85.09%
Confusion Matrix:
[[82053 11682  2747]
 [  354  2293   102]
 [   13    15   741]]

Precision: 0.9666168019253201
Recall: 0.85087
F1 Score: 0.8951710027909723
12 85.21
-----------------------------------------


Train Accuracy: 90.10%
Confusion Matrix:
[[6932  659  185]
 [ 982 6563  231]
 [ 206   47 7523]]
Epoch: 408, Train Loss: 0.652351
-----------------------------------------
Valid Accuracy: 85.10%
Confusion Matrix:
[[82065 11662  2755]
 [  354  2293   102]
 [   13    15   741]]

Precision: 0.9666203486333812
Recall: 0.85099
F1 Score: 0.8952452864227739
13 85.21
-----------------------------------------


Train Accuracy: 90.10%
Confusion Matrix:
[[6933  658  185]
 [ 982 6563  231]
 [ 205   48 7523]]
Epoch: 409, Train Loss: 0.65224
-----------------------------------------
Valid Accuracy: 85.1

Train Accuracy: 90.26%
Confusion Matrix:
[[6969  622  185]
 [ 986 6563  227]
 [ 207   46 7523]]
Epoch: 424, Train Loss: 0.650565
-----------------------------------------
Valid Accuracy: 85.93%
Confusion Matrix:
[[82899 10781  2802]
 [  354  2293   102]
 [   17    11   741]]

Precision: 0.9669019865082293
Recall: 0.85933
F1 Score: 0.90046565936633
0 85.927
-----------------------------------------


##############################################
saved 85.933
##############################################


Train Accuracy: 90.26%
Confusion Matrix:
[[6970  621  185]
 [ 985 6563  228]
 [ 212   41 7523]]
Epoch: 425, Train Loss: 0.650466
-----------------------------------------
Valid Accuracy: 85.95%
Confusion Matrix:
[[82915 10765  2802]
 [  354  2293   102]
 [   17    11   741]]

Precision: 0.9669087100174483
Recall: 0.85949
F1 Score: 0.9005662515676749
0 85.933
-----------------------------------------


##############################################
saved 85.949
#######################

-----------------------------------------
Valid Accuracy: 86.68%
Confusion Matrix:
[[83642 10085  2755]
 [  360  2293    96]
 [   28     0   741]]

Precision: 0.9670438932516194
Recall: 0.86676
F1 Score: 0.9050649022316585
1 86.671
-----------------------------------------


##############################################
saved 86.676
##############################################


Train Accuracy: 90.43%
Confusion Matrix:
[[7008  582  186]
 [ 983 6564  229]
 [ 207   46 7523]]
Epoch: 441, Train Loss: 0.648855
-----------------------------------------
Valid Accuracy: 86.68%
Confusion Matrix:
[[83642 10085  2755]
 [  360  2293    96]
 [   27     1   741]]

Precision: 0.9670549108434627
Recall: 0.86676
F1 Score: 0.9050693045875334
0 86.676
-----------------------------------------


Train Accuracy: 90.44%
Confusion Matrix:
[[7010  580  186]
 [ 983 6564  229]
 [ 207   46 7523]]
Epoch: 442, Train Loss: 0.648767
-----------------------------------------
Valid Accuracy: 86.70%
Confusion Matrix

Train Accuracy: 90.54%
Confusion Matrix:
[[7034  556  186]
 [ 989 6564  223]
 [ 214   38 7524]]
Epoch: 459, Train Loss: 0.647427
-----------------------------------------
Valid Accuracy: 86.74%
Confusion Matrix:
[[83708 10051  2723]
 [  360  2293    96]
 [   14    14   741]]

Precision: 0.967229796106598
Recall: 0.86742
F1 Score: 0.9055430839225995
0 86.732
-----------------------------------------


##############################################
saved 86.742
##############################################


Train Accuracy: 90.55%
Confusion Matrix:
[[7035  555  186]
 [ 989 6564  223]
 [ 213   39 7524]]
Epoch: 460, Train Loss: 0.647348
-----------------------------------------
Valid Accuracy: 86.76%
Confusion Matrix:
[[83726 10036  2720]
 [  360  2293    96]
 [   14    14   741]]

Precision: 0.9672382633341046
Recall: 0.8676
F1 Score: 0.9056563776655667
0 86.742
-----------------------------------------


##############################################
saved 86.76
########################

-----------------------------------------
Valid Accuracy: 87.03%
Confusion Matrix:
[[83988  9804  2690]
 [  370  2293    86]
 [   10    14   745]]

Precision: 0.967306221858607
Recall: 0.87026
F1 Score: 0.9072929371616282
0 87.022
-----------------------------------------


##############################################
saved 87.026
##############################################


Train Accuracy: 90.70%
Confusion Matrix:
[[7060  530  186]
 [ 988 6564  224]
 [ 200   41 7535]]
Epoch: 476, Train Loss: 0.645757
-----------------------------------------
Valid Accuracy: 87.08%
Confusion Matrix:
[[84046  9755  2681]
 [  370  2293    86]
 [   10    14   745]]

Precision: 0.9673345204011297
Recall: 0.87084
F1 Score: 0.9076579653376619
0 87.026
-----------------------------------------


##############################################
saved 87.084
##############################################


Train Accuracy: 90.71%
Confusion Matrix:
[[7061  529  186]
 [ 988 6564  224]
 [ 198   43 7535]]
Epoch:

Train Accuracy: 90.77%
Confusion Matrix:
[[7076  514  186]
 [ 988 6564  224]
 [ 189   52 7535]]
Epoch: 492, Train Loss: 0.644669
-----------------------------------------
Valid Accuracy: 87.36%
Confusion Matrix:
[[84317  9441  2724]
 [  360  2293    96]
 [   10    14   745]]

Precision: 0.9675772571619145
Recall: 0.87355
F1 Score: 0.9094045396603252
0 87.331
-----------------------------------------


##############################################
saved 87.355
##############################################


Train Accuracy: 90.78%
Confusion Matrix:
[[7077  513  186]
 [ 988 6564  224]
 [ 190   51 7535]]
Epoch: 493, Train Loss: 0.644609
-----------------------------------------
Valid Accuracy: 87.37%
Confusion Matrix:
[[84335  9423  2724]
 [  360  2293    96]
 [   10    14   745]]

Precision: 0.9675863865203743
Recall: 0.87373
F1 Score: 0.9095178323636962
0 87.355
-----------------------------------------


##############################################
saved 87.373
#####################

-----------------------------------------
Valid Accuracy: 87.90%
Confusion Matrix:
[[84866  8898  2718]
 [  364  2293    92]
 [   24     0   745]]

Precision: 0.9676731617369723
Recall: 0.87904
F1 Score: 0.9127854304760328
0 87.831
-----------------------------------------


##############################################
saved 87.904
##############################################


Train Accuracy: 90.90%
Confusion Matrix:
[[7106  485  185]
 [ 986 6564  226]
 [ 184   57 7535]]
Epoch: 509, Train Loss: 0.643807
-----------------------------------------
Valid Accuracy: 88.01%
Confusion Matrix:
[[84968  8785  2729]
 [  370  2293    86]
 [   24     0   745]]

Precision: 0.9676660925825036
Recall: 0.88006
F1 Score: 0.9134034804945649
0 87.904
-----------------------------------------


##############################################
saved 88.006
##############################################


Train Accuracy: 90.89%
Confusion Matrix:
[[7104  487  185]
 [ 988 6564  224]
 [ 182   59 7535]]
Epoch

-----------------------------------------
Valid Accuracy: 88.75%
Confusion Matrix:
[[85707  8048  2727]
 [  366  2293    90]
 [   24     0   745]]

Precision: 0.9681535601734303
Recall: 0.88745
F1 Score: 0.9180962544159861
0 88.714
-----------------------------------------


##############################################
saved 88.745
##############################################


Train Accuracy: 90.96%
Confusion Matrix:
[[7121  471  184]
 [ 987 6564  225]
 [ 188   53 7535]]
Epoch: 525, Train Loss: 0.642796
-----------------------------------------
Valid Accuracy: 88.77%
Confusion Matrix:
[[85728  8049  2705]
 [  366  2293    90]
 [   24     0   745]]

Precision: 0.968164032086545
Recall: 0.88766
F1 Score: 0.9182267710288426
0 88.745
-----------------------------------------


##############################################
saved 88.766
##############################################


Train Accuracy: 90.97%
Confusion Matrix:
[[7122  470  184]
 [ 987 6564  225]
 [ 187   54 7535]]
Epoch:

-----------------------------------------
Valid Accuracy: 88.97%
Confusion Matrix:
[[85933  7826  2723]
 [  364  2293    92]
 [   24     0   745]]

Precision: 0.9683218899336389
Recall: 0.88971
F1 Score: 0.9195392938041207
0 88.964
-----------------------------------------


##############################################
saved 88.971
##############################################


Train Accuracy: 91.09%
Confusion Matrix:
[[7151  441  184]
 [ 985 6564  227]
 [ 192   49 7535]]
Epoch: 542, Train Loss: 0.641515
-----------------------------------------
Valid Accuracy: 88.99%
Confusion Matrix:
[[85954  7804  2724]
 [  364  2293    92]
 [   24     0   745]]

Precision: 0.9683360656517858
Recall: 0.88992
F1 Score: 0.9196729151529669
0 88.971
-----------------------------------------


##############################################
saved 88.992
##############################################


Train Accuracy: 91.10%
Confusion Matrix:
[[7152  440  184]
 [ 984 6564  228]
 [ 193   48 7535]]
Epoch

Train Accuracy: 91.15%
Confusion Matrix:
[[7165  430  181]
 [ 984 6564  228]
 [ 182   59 7535]]
Epoch: 559, Train Loss: 0.640519
-----------------------------------------
Valid Accuracy: 89.10%
Confusion Matrix:
[[86065  7712  2705]
 [  370  2293    86]
 [   24     0   745]]

Precision: 0.968343757838197
Recall: 0.89103
F1 Score: 0.9203496804117864
0 89.096
-----------------------------------------


##############################################
saved 89.103
##############################################


Train Accuracy: 91.16%
Confusion Matrix:
[[7167  427  182]
 [ 986 6564  226]
 [ 183   58 7535]]
Epoch: 560, Train Loss: 0.640475
-----------------------------------------
Valid Accuracy: 89.11%
Confusion Matrix:
[[86067  7710  2705]
 [  370  2293    86]
 [   24     0   745]]

Precision: 0.9683451192266025
Recall: 0.89105
F1 Score: 0.9203624017981455
0 89.103
-----------------------------------------


##############################################
saved 89.105
######################

Train Accuracy: 91.24%
Confusion Matrix:
[[7186  409  181]
 [ 987 6564  225]
 [ 182   59 7535]]
Epoch: 579, Train Loss: 0.639552
-----------------------------------------
Valid Accuracy: 89.13%
Confusion Matrix:
[[86089  7676  2717]
 [  360  2293    96]
 [   23     1   745]]

Precision: 0.9684792517241632
Recall: 0.89127
F1 Score: 0.9205519747217251
16 89.117
-----------------------------------------


##############################################
saved 89.127
##############################################


Train Accuracy: 91.24%
Confusion Matrix:
[[7186  409  181]
 [ 987 6564  225]
 [ 181   60 7535]]
Epoch: 580, Train Loss: 0.639503
-----------------------------------------
Valid Accuracy: 89.22%
Confusion Matrix:
[[86185  7568  2729]
 [  364  2293    92]
 [   24     0   745]]

Precision: 0.9684947878306058
Recall: 0.89223
F1 Score: 0.9211437498510974
0 89.127
-----------------------------------------


##############################################
saved 89.223
####################

Train Accuracy: 91.31%
Confusion Matrix:
[[7201  397  178]
 [ 985 6564  227]
 [ 176   65 7535]]
Epoch: 597, Train Loss: 0.638642
-----------------------------------------
Valid Accuracy: 89.73%
Confusion Matrix:
[[86695  7098  2689]
 [  370  2293    86]
 [   24     0   745]]

Precision: 0.9687948535273506
Recall: 0.89733
F1 Score: 0.9243663985430575
9 89.751
-----------------------------------------


Train Accuracy: 91.31%
Confusion Matrix:
[[7201  397  178]
 [ 983 6564  229]
 [ 180   61 7535]]
Epoch: 598, Train Loss: 0.638593
-----------------------------------------
Valid Accuracy: 89.73%
Confusion Matrix:
[[86694  7096  2692]
 [  370  2293    86]
 [   23     1   745]]

Precision: 0.9688051609646772
Recall: 0.89732
F1 Score: 0.9243648037076097
10 89.751
-----------------------------------------


Train Accuracy: 91.31%
Confusion Matrix:
[[7202  395  179]
 [ 984 6564  228]
 [ 178   63 7535]]
Epoch: 599, Train Loss: 0.638547
-----------------------------------------
Valid Accuracy: 89

Train Accuracy: 91.41%
Confusion Matrix:
[[7222  377  177]
 [ 984 6566  226]
 [ 180   61 7535]]
Epoch: 616, Train Loss: 0.637685
-----------------------------------------
Valid Accuracy: 90.13%
Confusion Matrix:
[[87091  6759  2632]
 [  369  2294    86]
 [   24     0   745]]

Precision: 0.9691060220209574
Recall: 0.9013
F1 Score: 0.9269014275094675
0 90.097
-----------------------------------------


##############################################
saved 90.13
##############################################


Train Accuracy: 91.42%
Confusion Matrix:
[[7225  375  176]
 [ 984 6566  226]
 [ 181   60 7535]]
Epoch: 617, Train Loss: 0.637617
-----------------------------------------
Valid Accuracy: 90.12%
Confusion Matrix:
[[87085  6766  2631]
 [  369  2294    86]
 [   24     0   745]]

Precision: 0.9691008205835941
Recall: 0.90124
F1 Score: 0.9268625907384751
0 90.13
-----------------------------------------


Train Accuracy: 91.43%
Confusion Matrix:
[[7228  372  176]
 [ 984 6566  226]
 [ 183 

-----------------------------------------
Valid Accuracy: 90.15%
Confusion Matrix:
[[87115  6747  2620]
 [  369  2294    86]
 [   24     0   745]]

Precision: 0.9691222090674744
Recall: 0.90154
F1 Score: 0.927052549812227
1 90.151
-----------------------------------------


##############################################
saved 90.154
##############################################


Train Accuracy: 91.49%
Confusion Matrix:
[[7242  358  176]
 [ 984 6566  226]
 [ 177   64 7535]]
Epoch: 636, Train Loss: 0.636673
-----------------------------------------
Valid Accuracy: 90.19%
Confusion Matrix:
[[87150  6723  2609]
 [  369  2294    86]
 [   24     0   745]]

Precision: 0.969147815178956
Recall: 0.90189
F1 Score: 0.9272747010710167
0 90.154
-----------------------------------------


##############################################
saved 90.189
##############################################


Train Accuracy: 91.50%
Confusion Matrix:
[[7243  358  175]
 [ 981 6566  229]
 [ 177   64 7535]]
Epoch: 

-----------------------------------------
Valid Accuracy: 89.94%
Confusion Matrix:
[[86902  6986  2594]
 [  359  2294    96]
 [   24     0   745]]

Precision: 0.969049768882596
Recall: 0.89941
F1 Score: 0.9257224330676983
13 90.225
-----------------------------------------


Train Accuracy: 91.57%
Confusion Matrix:
[[7260  340  176]
 [ 983 6566  227]
 [ 193   48 7535]]
Epoch: 655, Train Loss: 0.635815
-----------------------------------------
Valid Accuracy: 89.94%
Confusion Matrix:
[[86905  6952  2625]
 [  359  2294    96]
 [   24     0   745]]

Precision: 0.9690599859162013
Recall: 0.89944
F1 Score: 0.9257488066277183
14 90.225
-----------------------------------------


Train Accuracy: 91.56%
Confusion Matrix:
[[7259  341  176]
 [ 986 6566  224]
 [ 191   50 7535]]
Epoch: 656, Train Loss: 0.635788
-----------------------------------------
Valid Accuracy: 90.02%
Confusion Matrix:
[[86982  6852  2648]
 [  359  2294    96]
 [   24     0   745]]

Precision: 0.9691273939778723
Recall: 0.9

Train Accuracy: 91.64%
Confusion Matrix:
[[7276  323  177]
 [ 985 6566  225]
 [ 193   48 7535]]
Epoch: 675, Train Loss: 0.635052
-----------------------------------------
Valid Accuracy: 89.73%
Confusion Matrix:
[[86687  7161  2634]
 [  356  2294    99]
 [   13    11   745]]

Precision: 0.9690396445382062
Recall: 0.89726
F1 Score: 0.9244133019522073
34 90.225
-----------------------------------------


Train Accuracy: 91.64%
Confusion Matrix:
[[7276  323  177]
 [ 985 6566  225]
 [ 190   51 7535]]
Epoch: 676, Train Loss: 0.635027
-----------------------------------------
Valid Accuracy: 89.64%
Confusion Matrix:
[[86604  7244  2634]
 [  345  2294   110]
 [   13    11   745]]

Precision: 0.9690941669829278
Recall: 0.89643
F1 Score: 0.9239305847402883
35 90.225
-----------------------------------------


Train Accuracy: 91.65%
Confusion Matrix:
[[7278  321  177]
 [ 987 6566  223]
 [ 192   49 7535]]
Epoch: 677, Train Loss: 0.635002
-----------------------------------------
Valid Accuracy: 8

-----------------------------------------
Valid Accuracy: 89.24%
Confusion Matrix:
[[86201  7745  2536]
 [  363  2294    92]
 [    9    15   745]]

Precision: 0.968645053260886
Recall: 0.8924
F1 Score: 0.9212891564283312
54 90.225
-----------------------------------------


Train Accuracy: 91.71%
Confusion Matrix:
[[7292  306  178]
 [ 981 6566  229]
 [ 185   56 7535]]
Epoch: 696, Train Loss: 0.634765
-----------------------------------------
Valid Accuracy: 89.04%
Confusion Matrix:
[[86005  7932  2545]
 [  363  2294    92]
 [    9    15   745]]

Precision: 0.9685165935606405
Recall: 0.89044
F1 Score: 0.9200470054204406
55 90.225
-----------------------------------------


Train Accuracy: 91.70%
Confusion Matrix:
[[7291  307  178]
 [ 981 6566  229]
 [ 186   55 7535]]
Epoch: 697, Train Loss: 0.634731
-----------------------------------------
Valid Accuracy: 89.44%
Confusion Matrix:
[[86397  7463  2622]
 [  359  2294    96]
 [   10    14   745]]

Precision: 0.968825159252605
Recall: 0.894

Train Accuracy: 91.77%
Confusion Matrix:
[[7307  294  175]
 [ 985 6566  225]
 [ 181   60 7535]]
Epoch: 716, Train Loss: 0.633552
-----------------------------------------
Valid Accuracy: 90.16%
Confusion Matrix:
[[87124  6761  2597]
 [  362  2294    93]
 [   22     2   745]]

Precision: 0.9692168491459551
Recall: 0.90163
F1 Score: 0.92714277546357
75 90.225
-----------------------------------------


Train Accuracy: 91.77%
Confusion Matrix:
[[7306  294  176]
 [ 985 6566  225]
 [ 184   57 7535]]
Epoch: 717, Train Loss: 0.633538
-----------------------------------------
Valid Accuracy: 90.12%
Confusion Matrix:
[[87080  6808  2594]
 [  366  2294    89]
 [   21     3   745]]

Precision: 0.9691484716145023
Recall: 0.90119
F1 Score: 0.9268461594065838
76 90.225
-----------------------------------------


Train Accuracy: 91.77%
Confusion Matrix:
[[7308  293  175]
 [ 982 6566  228]
 [ 184   57 7535]]
Epoch: 718, Train Loss: 0.633528
-----------------------------------------
Valid Accuracy: 90.

-----------------------------------------
Valid Accuracy: 90.46%
Confusion Matrix:
[[87420  6438  2624]
 [  345  2298   106]
 [   23     1   745]]

Precision: 0.9696546039672651
Recall: 0.90463
F1 Score: 0.929145091238083
0 90.496
-----------------------------------------


Train Accuracy: 91.89%
Confusion Matrix:
[[7332  269  175]
 [ 977 6569  230]
 [ 180   61 7535]]
Epoch: 736, Train Loss: 0.632337
-----------------------------------------
Valid Accuracy: 90.50%
Confusion Matrix:
[[87459  6363  2660]
 [  354  2298    97]
 [   23     1   745]]

Precision: 0.9696078487573488
Recall: 0.90502
F1 Score: 0.9293702155266439
1 90.496
-----------------------------------------


##############################################
saved 90.502
##############################################


Train Accuracy: 91.90%
Confusion Matrix:
[[7334  268  174]
 [ 975 6569  232]
 [ 178   63 7535]]
Epoch: 737, Train Loss: 0.632308
-----------------------------------------
Valid Accuracy: 90.48%
Confusion Matrix:

Train Accuracy: 91.93%
Confusion Matrix:
[[7340  261  175]
 [ 982 6570  224]
 [ 185   56 7535]]
Epoch: 754, Train Loss: 0.631779
-----------------------------------------
Valid Accuracy: 90.77%
Confusion Matrix:
[[87719  6304  2459]
 [  365  2302    82]
 [   24     0   745]]

Precision: 0.9696569967846849
Recall: 0.90766
F1 Score: 0.930955850619705
0 90.741
-----------------------------------------


##############################################
saved 90.766
##############################################


Train Accuracy: 91.93%
Confusion Matrix:
[[7340  261  175]
 [ 981 6570  225]
 [ 188   53 7535]]
Epoch: 755, Train Loss: 0.631766
-----------------------------------------
Valid Accuracy: 90.77%
Confusion Matrix:
[[87722  6295  2465]
 [  365  2302    82]
 [   24     0   745]]

Precision: 0.9696616621023256
Recall: 0.90769
F1 Score: 0.930976974864951
0 90.766
-----------------------------------------


##############################################
saved 90.769
#######################

Train Accuracy: 91.96%
Confusion Matrix:
[[7348  253  175]
 [ 982 6570  224]
 [ 182   59 7535]]
Epoch: 773, Train Loss: 0.631464
-----------------------------------------
Valid Accuracy: 90.57%
Confusion Matrix:
[[87525  6466  2491]
 [  365  2302    82]
 [   24     0   745]]

Precision: 0.969494921686667
Recall: 0.90572
F1 Score: 0.9297115449455224
11 90.989
-----------------------------------------


Train Accuracy: 91.97%
Confusion Matrix:
[[7349  253  174]
 [ 981 6570  225]
 [ 187   54 7535]]
Epoch: 774, Train Loss: 0.63145
-----------------------------------------
Valid Accuracy: 90.50%
Confusion Matrix:
[[87448  6550  2484]
 [  365  2302    82]
 [   13    11   745]]

Precision: 0.9695377749358632
Recall: 0.90495
F1 Score: 0.9292576023368323
12 90.989
-----------------------------------------


Train Accuracy: 91.97%
Confusion Matrix:
[[7349  253  174]
 [ 981 6571  224]
 [ 186   55 7535]]
Epoch: 775, Train Loss: 0.631418
-----------------------------------------
Valid Accuracy: 90.

-----------------------------------------
Valid Accuracy: 90.76%
Confusion Matrix:
[[87711  6269  2502]
 [  365  2302    82]
 [   23     1   745]]

Precision: 0.9696741590018848
Recall: 0.90758
F1 Score: 0.9309207537780406
31 90.989
-----------------------------------------


Train Accuracy: 92.01%
Confusion Matrix:
[[7358  246  172]
 [ 980 6571  225]
 [ 186   55 7535]]
Epoch: 794, Train Loss: 0.630894
-----------------------------------------
Valid Accuracy: 90.69%
Confusion Matrix:
[[87645  6335  2502]
 [  365  2302    82]
 [   11    13   745]]

Precision: 0.969735358871665
Recall: 0.90692
F1 Score: 0.9305416340520963
32 90.989
-----------------------------------------


Train Accuracy: 92.01%
Confusion Matrix:
[[7358  246  172]
 [ 980 6571  225]
 [ 184   57 7535]]
Epoch: 795, Train Loss: 0.630912
-----------------------------------------
Valid Accuracy: 90.67%
Confusion Matrix:
[[87618  6363  2501]
 [  365  2302    82]
 [   11    13   745]]

Precision: 0.9697110064597139
Recall: 0.9

Train Accuracy: 92.03%
Confusion Matrix:
[[7363  240  173]
 [ 979 6571  226]
 [ 180   61 7535]]
Epoch: 813, Train Loss: 0.631267
-----------------------------------------
Valid Accuracy: 90.43%
Confusion Matrix:
[[87379  6596  2507]
 [  365  2302    82]
 [    9    15   745]]

Precision: 0.9695263087117832
Recall: 0.90426
F1 Score: 0.9288352083262995
8 91.104
-----------------------------------------


Train Accuracy: 92.03%
Confusion Matrix:
[[7363  241  172]
 [ 981 6571  224]
 [ 178   63 7535]]
Epoch: 814, Train Loss: 0.630841
-----------------------------------------
Valid Accuracy: 90.64%
Confusion Matrix:
[[87594  6353  2535]
 [  365  2302    82]
 [   11    13   745]]

Precision: 0.9697008852558855
Recall: 0.90641
F1 Score: 0.9302217048649347
9 91.104
-----------------------------------------


Train Accuracy: 92.03%
Confusion Matrix:
[[7363  240  173]
 [ 984 6571  221]
 [ 176   65 7535]]
Epoch: 815, Train Loss: 0.630822
-----------------------------------------
Valid Accuracy: 90.

-----------------------------------------
Valid Accuracy: 90.90%
Confusion Matrix:
[[87852  6089  2541]
 [  365  2302    82]
 [   23     1   745]]

Precision: 0.9698193661769007
Recall: 0.90899
F1 Score: 0.9318480178412434
28 91.104
-----------------------------------------


Train Accuracy: 92.06%
Confusion Matrix:
[[7370  234  172]
 [ 979 6571  226]
 [ 185   56 7535]]
Epoch: 834, Train Loss: 0.630282
-----------------------------------------
Valid Accuracy: 90.91%
Confusion Matrix:
[[87859  6082  2541]
 [  365  2302    82]
 [   23     1   745]]

Precision: 0.9698259978970521
Recall: 0.90906
F1 Score: 0.9318935051577144
29 91.104
-----------------------------------------


Train Accuracy: 92.06%
Confusion Matrix:
[[7370  234  172]
 [ 979 6571  226]
 [ 185   56 7535]]
Epoch: 835, Train Loss: 0.630275
-----------------------------------------
Valid Accuracy: 90.91%
Confusion Matrix:
[[87861  6080  2541]
 [  365  2302    82]
 [   23     1   745]]

Precision: 0.9698278945954428
Recall: 0.

-----------------------------------------
Valid Accuracy: 90.75%
Confusion Matrix:
[[87700  6229  2553]
 [  361  2306    82]
 [   22     2   745]]

Precision: 0.9697453345752491
Recall: 0.90751
F1 Score: 0.9309050252854536
3 91.175
-----------------------------------------


Train Accuracy: 92.10%
Confusion Matrix:
[[7375  232  169]
 [ 977 6575  224]
 [ 184   57 7535]]
Epoch: 854, Train Loss: 0.629868
-----------------------------------------
Valid Accuracy: 90.78%
Confusion Matrix:
[[87724  6196  2562]
 [  355  2306    88]
 [   22     2   745]]

Precision: 0.969833225634222
Recall: 0.90775
F1 Score: 0.9310895032935501
4 91.175
-----------------------------------------


Train Accuracy: 92.10%
Confusion Matrix:
[[7375  230  171]
 [ 977 6575  224]
 [ 176   65 7535]]
Epoch: 855, Train Loss: 0.629853
-----------------------------------------
Valid Accuracy: 90.77%
Confusion Matrix:
[[87720  6212  2550]
 [  361  2306    82]
 [   22     2   745]]

Precision: 0.9697626089198602
Recall: 0.907

-----------------------------------------
Valid Accuracy: 90.88%
Confusion Matrix:
[[87826  6095  2561]
 [  361  2306    82]
 [   20     4   745]]

Precision: 0.9698857239019757
Recall: 0.90877
F1 Score: 0.9317334963310357
2 91.561
-----------------------------------------


Train Accuracy: 92.10%
Confusion Matrix:
[[7376  229  171]
 [ 975 6575  226]
 [ 180   61 7535]]
Epoch: 874, Train Loss: 0.62977
-----------------------------------------
Valid Accuracy: 90.76%
Confusion Matrix:
[[87705  6234  2543]
 [  355  2306    88]
 [    9    15   745]]

Precision: 0.9699392025511537
Recall: 0.90756
F1 Score: 0.9310116381135009
3 91.561
-----------------------------------------


Train Accuracy: 92.10%
Confusion Matrix:
[[7376  231  169]
 [ 979 6575  222]
 [ 172   69 7535]]
Epoch: 875, Train Loss: 0.629797
-----------------------------------------
Valid Accuracy: 91.03%
Confusion Matrix:
[[87980  5903  2599]
 [  361  2306    82]
 [   13    11   745]]

Precision: 0.9701200859721115
Recall: 0.910

Train Accuracy: 92.12%
Confusion Matrix:
[[7380  227  169]
 [ 977 6575  224]
 [ 186   55 7535]]
Epoch: 894, Train Loss: 0.629667
-----------------------------------------
Valid Accuracy: 90.22%
Confusion Matrix:
[[87169  6728  2585]
 [  341  2306   102]
 [    9    15   745]]

Precision: 0.9696362697786224
Recall: 0.9022
F1 Score: 0.927625182264577
23 91.561
-----------------------------------------


Train Accuracy: 92.12%
Confusion Matrix:
[[7380  225  171]
 [ 976 6575  225]
 [ 176   65 7535]]
Epoch: 895, Train Loss: 0.629774
-----------------------------------------
Valid Accuracy: 90.83%
Confusion Matrix:
[[87782  6140  2560]
 [  361  2306    82]
 [    9    15   745]]

Precision: 0.9699540989226548
Recall: 0.90833
F1 Score: 0.9314908696092284
24 91.561
-----------------------------------------


Train Accuracy: 92.12%
Confusion Matrix:
[[7380  226  170]
 [ 978 6575  223]
 [ 180   61 7535]]
Epoch: 896, Train Loss: 0.629581
-----------------------------------------
Valid Accuracy: 90.

-----------------------------------------
Valid Accuracy: 91.49%
Confusion Matrix:
[[88438  5500  2544]
 [  361  2306    82]
 [   24     0   745]]

Precision: 0.9704584589454492
Recall: 0.91489
F1 Score: 0.935712462455013
43 91.561
-----------------------------------------


Train Accuracy: 92.14%
Confusion Matrix:
[[7385  223  168]
 [ 977 6575  224]
 [ 179   62 7535]]
Epoch: 915, Train Loss: 0.62949
-----------------------------------------
Valid Accuracy: 91.30%
Confusion Matrix:
[[88249  5662  2571]
 [  361  2306    82]
 [   22     2   745]]

Precision: 0.970290608584111
Recall: 0.913
F1 Score: 0.9344908184076568
44 91.561
-----------------------------------------


Train Accuracy: 92.15%
Confusion Matrix:
[[7386  221  169]
 [ 977 6575  224]
 [ 173   68 7535]]
Epoch: 916, Train Loss: 0.629368
-----------------------------------------
Valid Accuracy: 91.37%
Confusion Matrix:
[[88320  5617  2545]
 [  361  2306    82]
 [   23     1   745]]

Precision: 0.9703422889956747
Recall: 0.91371

Train Accuracy: 92.15%
Confusion Matrix:
[[7386  221  169]
 [ 977 6575  224]
 [ 174   67 7535]]
Epoch: 935, Train Loss: 0.629437
-----------------------------------------
Valid Accuracy: 91.01%
Confusion Matrix:
[[87961  5991  2530]
 [  341  2306   102]
 [   10    14   745]]

Precision: 0.9703092450899807
Recall: 0.91012
F1 Score: 0.9327257146462832
64 91.561
-----------------------------------------


Train Accuracy: 92.15%
Confusion Matrix:
[[7386  222  168]
 [ 976 6575  225]
 [ 179   62 7535]]
Epoch: 936, Train Loss: 0.629283
-----------------------------------------
Valid Accuracy: 91.00%
Confusion Matrix:
[[87954  5956  2572]
 [  361  2306    82]
 [   20     4   745]]

Precision: 0.9700131183617028
Recall: 0.91005
F1 Score: 0.9325705680991747
65 91.561
-----------------------------------------


Train Accuracy: 92.15%
Confusion Matrix:
[[7386  222  168]
 [ 976 6575  225]
 [ 171   70 7535]]
Epoch: 937, Train Loss: 0.629384
-----------------------------------------
Valid Accuracy: 9

Train Accuracy: 92.17%
Confusion Matrix:
[[7391  219  166]
 [ 975 6575  226]
 [ 182   59 7535]]
Epoch: 955, Train Loss: 0.629062
-----------------------------------------
Valid Accuracy: 91.42%
Confusion Matrix:
[[88372  5570  2540]
 [  355  2306    88]
 [   24     0   745]]

Precision: 0.9704471082656836
Recall: 0.91423
F1 Score: 0.9353024100997844
16 91.763
-----------------------------------------


Train Accuracy: 92.17%
Confusion Matrix:
[[7392  219  165]
 [ 976 6575  225]
 [ 194   47 7535]]
Epoch: 956, Train Loss: 0.629128
-----------------------------------------
Valid Accuracy: 90.80%
Confusion Matrix:
[[87748  6209  2525]
 [  341  2306   102]
 [    9    15   745]]

Precision: 0.9701175688683367
Recall: 0.90799
F1 Score: 0.9313446218184325
17 91.763
-----------------------------------------


Train Accuracy: 92.18%
Confusion Matrix:
[[7393  217  166]
 [ 974 6575  227]
 [ 174   67 7535]]
Epoch: 957, Train Loss: 0.629031
-----------------------------------------
Valid Accuracy: 9

Train Accuracy: 92.22%
Confusion Matrix:
[[7404  207  165]
 [ 976 6575  225]
 [ 176   65 7535]]
Epoch: 975, Train Loss: 0.629082
-----------------------------------------
Valid Accuracy: 92.74%
Confusion Matrix:
[[89692  4428  2362]
 [  361  2306    82]
 [   24     0   745]]

Precision: 0.9719064586579008
Recall: 0.92743
F1 Score: 0.9439778464490483
0 92.189
-----------------------------------------


##############################################
saved 92.743
##############################################


Train Accuracy: 92.23%
Confusion Matrix:
[[7405  205  166]
 [ 979 6575  222]
 [ 181   60 7535]]
Epoch: 976, Train Loss: 0.628764
-----------------------------------------
Valid Accuracy: 92.61%
Confusion Matrix:
[[89555  4486  2441]
 [  361  2306    82]
 [   24     0   745]]

Precision: 0.9717763608599769
Recall: 0.92606
F1 Score: 0.9431036139246027
0 92.743
-----------------------------------------


Train Accuracy: 92.22%
Confusion Matrix:
[[7404  208  164]
 [ 978 6575  223]
 [ 1

Train Accuracy: 92.26%
Confusion Matrix:
[[7412  200  164]
 [ 978 6575  223]
 [ 181   60 7535]]
Epoch: 995, Train Loss: 0.628202
-----------------------------------------
Valid Accuracy: 91.61%
Confusion Matrix:
[[88555  5362  2565]
 [  355  2306    88]
 [   24     0   745]]

Precision: 0.9706614180298515
Recall: 0.91606
F1 Score: 0.9365199646502017
19 92.743
-----------------------------------------


Train Accuracy: 92.26%
Confusion Matrix:
[[7412  198  166]
 [ 978 6575  223]
 [ 176   65 7535]]
Epoch: 996, Train Loss: 0.628218
-----------------------------------------
Valid Accuracy: 91.61%
Confusion Matrix:
[[88561  5404  2517]
 [  355  2306    88]
 [   24     0   745]]

Precision: 0.9706408184562998
Recall: 0.91612
F1 Score: 0.9365357525561068
20 92.743
-----------------------------------------


Train Accuracy: 92.26%
Confusion Matrix:
[[7412  199  165]
 [ 975 6575  226]
 [ 181   60 7535]]
Epoch: 997, Train Loss: 0.628264
-----------------------------------------
Valid Accuracy: 9

-----------------------------------------
Valid Accuracy: 91.28%
Confusion Matrix:
[[88225  5777  2480]
 [  361  2306    82]
 [    9    15   745]]

Precision: 0.970351113858023
Recall: 0.91276
F1 Score: 0.9343463109875996
39 92.743
-----------------------------------------


Train Accuracy: 92.28%
Confusion Matrix:
[[7417  194  165]
 [ 977 6575  224]
 [ 181   60 7535]]
Epoch: 1016, Train Loss: 0.62832
-----------------------------------------
Valid Accuracy: 91.70%
Confusion Matrix:
[[88651  5286  2545]
 [  355  2306    88]
 [   22     2   745]]

Precision: 0.9707779749410684
Recall: 0.91702
F1 Score: 0.9371518926670881
40 92.743
-----------------------------------------


Train Accuracy: 92.28%
Confusion Matrix:
[[7416  194  166]
 [ 978 6575  223]
 [ 178   63 7535]]
Epoch: 1017, Train Loss: 0.628055
-----------------------------------------
Valid Accuracy: 91.15%
Confusion Matrix:
[[88097  5830  2555]
 [  341  2306   102]
 [    9    15   745]]

Precision: 0.9704632632157248
Recall: 0.

Train Accuracy: 92.31%
Confusion Matrix:
[[7425  187  164]
 [ 978 6575  223]
 [ 191   50 7535]]
Epoch: 1036, Train Loss: 0.627701
-----------------------------------------
Valid Accuracy: 91.46%
Confusion Matrix:
[[88409  5487  2586]
 [  341  2306   102]
 [   24     0   745]]

Precision: 0.9706563699546424
Recall: 0.9146
F1 Score: 0.9356279580649371
60 92.743
-----------------------------------------


Train Accuracy: 92.32%
Confusion Matrix:
[[7427  185  164]
 [ 975 6575  226]
 [ 184   57 7535]]
Epoch: 1037, Train Loss: 0.627593
-----------------------------------------
Valid Accuracy: 91.79%
Confusion Matrix:
[[88741  5192  2549]
 [  341  2306   102]
 [   24     0   745]]

Precision: 0.9710093735891624
Recall: 0.91792
F1 Score: 0.9378030024922774
61 92.743
-----------------------------------------


Train Accuracy: 92.32%
Confusion Matrix:
[[7426  187  163]
 [ 980 6575  221]
 [ 187   54 7535]]
Epoch: 1038, Train Loss: 0.627687
-----------------------------------------
Valid Accuracy:

-----------------------------------------
Valid Accuracy: 91.56%
Confusion Matrix:
[[88505  5511  2466]
 [  341  2306   102]
 [   13    11   745]]

Precision: 0.9708036771035293
Recall: 0.91556
F1 Score: 0.9362454810391461
80 92.743
-----------------------------------------


Train Accuracy: 92.33%
Confusion Matrix:
[[7429  184  163]
 [ 977 6575  224]
 [ 184   57 7535]]
Epoch: 1057, Train Loss: 0.627562
-----------------------------------------
Valid Accuracy: 91.31%
Confusion Matrix:
[[88263  5749  2470]
 [  341  2306   102]
 [   10    14   745]]

Precision: 0.9705817592357272
Recall: 0.91314
F1 Score: 0.9346724955268676
81 92.743
-----------------------------------------


Train Accuracy: 92.33%
Confusion Matrix:
[[7429  186  161]
 [ 979 6575  222]
 [ 192   49 7535]]
Epoch: 1058, Train Loss: 0.627516
-----------------------------------------
Valid Accuracy: 91.30%
Confusion Matrix:
[[88249  5674  2559]
 [  341  2306   102]
 [   10    14   745]]

Precision: 0.9706097310389515
Recall: 

<All keys matched successfully>

In [20]:
Cf.load_state_dict(torch.load('cnn30.pt'))

<All keys matched successfully>

In [21]:
valid_latents = []
VR,VL = [], []
valid_loss = 0.0
for j, (inp, lab) in enumerate(train_loader):
    probability = 0.0
    coin_toss = random.random()  

    if coin_toss < probability:
        continue
    inp = inp.to(device)
    lab = lab.to(device)

    with torch.no_grad():
        # Forward pass
        outp = Cf(inp)

    VR.append(outp)
    VL.append(lab)

VR = torch.cat(VR, dim=0)
VL = torch.cat(VL, dim=0)
_, vpre = torch.max(VR.data, 1)
_, vlbl = torch.max(VL.data, 1)
total = vlbl.size(0)
correct = (vpre == vlbl).sum().item()

vaccuracy = 100 * correct / total
print('-----------------------------------------')
print(f'Train Accuracy: {vaccuracy:.2f}%')
lb = vlbl.cpu().detach().numpy()
pre = vpre.cpu().detach().numpy()
conf_matrix = confusion_matrix(lb,pre)
precision = precision_score(lb, pre,average=avg)
recall = recall_score(lb, pre,average=avg)
f1 = f1_score(lb, pre,average=avg)
print('Confusion Matrix:')
print(conf_matrix)
print()
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print(epochs_without_improvement, best_loss)
print('-----------------------------------------')
print()
print()

valid_latents = []
VR,VL = [], []
valid_loss = 0.0
for j, (inp, lab) in enumerate(valid_loader):
    probability = 0.0
    coin_toss = random.random()  

    if coin_toss < probability:
        continue
    inp = inp.to(device)
    lab = lab.to(device)

    with torch.no_grad():
        # Forward pass
        outp = Cf(inp)

    VR.append(outp)
    VL.append(lab)

VR = torch.cat(VR, dim=0)
VL = torch.cat(VL, dim=0)
_, vpre = torch.max(VR.data, 1)
_, vlbl = torch.max(VL.data, 1)
total = vlbl.size(0)
correct = (vpre == vlbl).sum().item()

vaccuracy = 100 * correct / total
print('-----------------------------------------')
print(f'Valid Accuracy: {vaccuracy:.2f}%')
lb = vlbl.cpu().detach().numpy()
pre = vpre.cpu().detach().numpy()
conf_matrix = confusion_matrix(lb,pre)
precision = precision_score(lb, pre,average=avg)
recall = recall_score(lb, pre,average=avg)
f1 = f1_score(lb, pre,average=avg)
print('Confusion Matrix:')
print(conf_matrix)
print()
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print(epochs_without_improvement, best_loss)
print('-----------------------------------------')
print()
print()

valid_latents = []
VR,VL = [], []
valid_loss = 0.0
for j, (inp, lab) in enumerate(test_loader):
    probability = 0.0
    coin_toss = random.random()  

    if coin_toss < probability:
        continue
    inp = inp.to(device)
    lab = lab.to(device)

    with torch.no_grad():
        # Forward pass
        outp = Cf(inp)

    VR.append(outp)
    VL.append(lab)

VR = torch.cat(VR, dim=0)
VL = torch.cat(VL, dim=0)
_, vpre = torch.max(VR.data, 1)
_, vlbl = torch.max(VL.data, 1)
total = vlbl.size(0)
correct = (vpre == vlbl).sum().item()

vaccuracy = 100 * correct / total
print('-----------------------------------------')
print(f'Test Accuracy: {vaccuracy:.2f}%')
lb = vlbl.cpu().detach().numpy()
pre = vpre.cpu().detach().numpy()
conf_matrix = confusion_matrix(lb,pre)
precision = precision_score(lb, pre,average=avg)
recall = recall_score(lb, pre,average=avg)
f1 = f1_score(lb, pre,average=avg)
print('Confusion Matrix:')
print(conf_matrix)
print()
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print(epochs_without_improvement, best_loss)
print('-----------------------------------------')
print()
print()

-----------------------------------------
Train Accuracy: 92.23%
Confusion Matrix:
[[7406  206  164]
 [1002 6575  199]
 [ 241    0 7535]]

Precision: 0.926647986843666
Recall: 0.9223251028806584
F1 Score: 0.9222021194645675
100 92.743
-----------------------------------------


-----------------------------------------
Valid Accuracy: 92.74%
Confusion Matrix:
[[89692  4428  2362]
 [  361  2306    82]
 [   24     0   745]]

Precision: 0.9719064586579008
Recall: 0.92743
F1 Score: 0.9439778464490483
100 92.743
-----------------------------------------


-----------------------------------------
Test Accuracy: 94.24%
Confusion Matrix:
[[150824   5887   2888]
 [   553   2868     90]
 [    33      0    939]]

Precision: 0.977343440994377
Recall: 0.9424007508440901
F1 Score: 0.9556837182313904
100 92.743
-----------------------------------------




In [19]:
 # Iterate over mini-batches
latents = []
train_label = []
for i, (inputs, labels, lbl) in enumerate(train_loader):

    inputs = inputs.to(device)
    lbl = lbl.to(device)
    
    with torch.no_grad():

        # Forward pass
        latent = Encoder(inputs)


    latents.append(latent)
    train_label.append(lbl)


ValueError: not enough values to unpack (expected 3, got 2)

In [ ]:
latents = torch.cat(latents,dim=0)

In [ ]:
train_label = torch.cat(train_label,dim=0)

In [ ]:
latents = latents.cpu().detach().numpy()

In [ ]:
rs = reconstructData(latents)

In [ ]:
torch.argmax(train_label,dim=1)

In [ ]:
labl = torch.argmax(train_label,dim=1).cpu().detach().numpy()

In [ ]:
rs.shape

In [ ]:
real_data_reshaped = np.reshape(latents, (latents.shape[0], -1))


# Perform tsne on real and fake data
perplexity = min(30, real_data_reshaped.shape[0] - 1)
tsne = TSNE(n_components=2, perplexity=perplexity, random_state=seed)
real_tsne = tsne.fit_transform(real_data_reshaped)
label_names = ['No-Movement', 'Small Movement',  'Large Movement']
# Plot the t-SNE visualization with labeled data
plt.figure(figsize=(20, 15))
for label in np.unique(labl):
    indices = np.where(labl == label)
    plt.scatter(real_tsne[indices, 0], real_tsne[indices, 1], label=label_names[int(label)], edgecolors='black')
    
plt.legend()
plt.show()

In [ ]:
-----------------------------------------
Train Accuracy: 92.23%
Confusion Matrix:
[[7406  206  164]
 [1002 6575  199]
 [ 241    0 7535]]

Precision: 0.926647986843666
Recall: 0.9223251028806584
F1 Score: 0.9222021194645675
100 92.743
-----------------------------------------


-----------------------------------------
Valid Accuracy: 92.74%
Confusion Matrix:
[[89692  4428  2362]
 [  361  2306    82]
 [   24     0   745]]

Precision: 0.9719064586579008
Recall: 0.92743
F1 Score: 0.9439778464490483
100 92.743
-----------------------------------------


-----------------------------------------
Test Accuracy: 94.24%
Confusion Matrix:
[[150824   5887   2888]
 [   553   2868     90]
 [    33      0    939]]

Precision: 0.977343440994377
Recall: 0.9424007508440901
F1 Score: 0.9556837182313904
100 92.743
-----------------------------------------

In [ ]:
-----------------------------------------
Train Accuracy: 88.61%
Confusion Matrix:
[[6682  954  140]
 [ 945 6710  121]
 [ 435   62 7279]]

Precision: 0.8875690656187784
Recall: 0.8861025377229081
F1 Score: 0.8866658095578258
100 80.479
-----------------------------------------


-----------------------------------------
Valid Accuracy: 80.48%
Confusion Matrix:
[[77819 17188  1475]
 [  763  1940    46]
 [   33    16   720]]

Precision: 0.9603073569758481
Recall: 0.80479
F1 Score: 0.8661478300003829
100 80.479
-----------------------------------------


-----------------------------------------
Test Accuracy: 84.33%
Confusion Matrix:
[[135089  22386   2124]
 [  1087   2374     50]
 [    47     23    902]]

Precision: 0.9683679846076022
Recall: 0.8432673906948964
F1 Score: 0.8945902175201007
100 80.479
-----------------------------------------