In [1]:
seed=197

In [2]:
# importing required libraries
import torch.nn as nn
import torch
import torch.nn.functional as F
import math,copy,re
import warnings
import pandas as pd
import numpy as np
import random
import pickle
import torch.nn.init as init
from torchviz import make_dot
import plotly.graph_objects as go
import pickle
# import seaborn as sns
# import torchtext
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import torch.nn.functional as F
import torch.optim as optim
from IPython.display import display
import matplotlib.pyplot as plt
import os 
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score

warnings.simplefilter("ignore")
print(torch.__version__)

1.13.1+cu117


In [3]:
# Check if CUDA is available
if torch.cuda.is_available():
    # CUDA is available, so PyTorch can use a GPU
    device = torch.device("cuda")
    print("PyTorch is using GPU.")
else:
    # CUDA is not available, PyTorch will use CPU
    device = torch.device("cpu")
    print("PyTorch is using CPU.")

# Create a tensor and move it to the device
tensor = torch.randn(3, 4).to(device)

# Check the device of the tensor
print("Tensor device:", tensor.device)

PyTorch is using GPU.
Tensor device: cuda:0


In [4]:
def reset_random_seeds(seed):
    os.environ['PYTHONHASHSEED']=str(seed)
#     tf.random.set_seed(seed)
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

In [5]:
# pickle_file_path = '/media/terminator/Data/NatureData/Auto Ten Minutes.pkl'
pickle_file_path = '/media/terminator/NatureData/Sixty Minutes.pkl'

In [6]:
# Load data from the pickle file
with open(pickle_file_path, "rb") as f:
    loaded_data_dict = pickle.load(f)


In [7]:
# Retrieve data and labels
X_train = loaded_data_dict["X_train"]
y_train = loaded_data_dict["y_train"]
X_test = loaded_data_dict["X_test"]
y_test = loaded_data_dict["y_test"]

In [8]:
X_train.shape,y_train.shape

(torch.Size([23328, 144, 13]), torch.Size([23328, 3]))

In [9]:
features=13

In [10]:
def reconstructData(packets):
    # Take the first packet
    first_packet = packets[0]
    
    # Concatenate the last index of every packet
    reconstructed_data = np.concatenate([packet[-1:] for packet in packets[1:]])
    
    # Combine the first packet with the concatenated data
    reconstructed_data = np.concatenate([first_packet, reconstructed_data])
    
    return reconstructed_data

In [11]:
Valid,Test = X_test[:100000],X_test[100000:]
Valid_label,Test_label = y_test[:100000],y_test[100000:]

In [12]:
num_epochs = 500
# Define batch size
batch_size = 256
# Create DataLoader for training set
train_dataset = torch.utils.data.TensorDataset(X_train.float(), y_train.float())
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
valid_dataset = torch.utils.data.TensorDataset(Valid.float(), Valid_label.float())
valid_loader = torch.utils.data.DataLoader(valid_dataset, batch_size=batch_size, shuffle=False)
test_dataset = torch.utils.data.TensorDataset(Test.float(), Test_label.float())
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [13]:
print(X_train.dtype)
print(y_train.dtype)

torch.float64
torch.float64


In [14]:
X_train.shape, y_train.shape

(torch.Size([23328, 144, 13]), torch.Size([23328, 3]))

In [15]:
import torch
import torch.nn as nn

class TimeSeriesEncoder(nn.Module):
    def __init__(self, input_channels):
        super(TimeSeriesEncoder, self).__init__()
        
        self.encoder = nn.Sequential(
            nn.Conv1d(input_channels, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2, stride=1),  # Reduce sequence length to 36 / 4 = 9
            nn.Conv1d(128, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2, stride=1)  # Reduce sequence length to 9 / 2 = 4.5 (rounded to 4)
        )
        self.classifier = nn.Sequential(
            nn.Linear(64*142, 1024),
            nn.ReLU(), 
            nn.Linear(1024, 3), 
            nn.Softmax(dim=1)  
        )
        
    
    def forward(self, x):
        x = x.permute(0,2,1)
        x = self.encoder(x)
        x = torch.reshape(x,(x.shape[0],-1))
        x = self.classifier(x)
#         x = x.permute(0,2,1)
        return x

# Create the autoencoder model
input_channels = 13  # Number of input features
# encoder = TimeSeriesEncoder(input_channels).to(device)





In [16]:
train = 1
avg = 'weighted'
seq_length = 144
num_epochs = 5000
reset_random_seeds(seed)
src_vocab_size = features+5
target_vocab_size = features
num_layers = 2
latent_dim = 8
embed_dim = 128
n_heads = 8
expansion_factor = 2

Cf = TimeSeriesEncoder(input_channels).to(device)

criterion = nn.CrossEntropyLoss()
optimizer_cf = optim.Adam(Cf.parameters(), lr=0.00001)

# Define early stopping parameters
patience = 100
best_loss = 0
epochs_without_improvement = 0

if train:
    # Step 4: Training loop
    for epoch in range(num_epochs):
        running_loss = 0.0
        latents = []
        PR, PL = [], []
        train_input,train_output = [], []

        # Iterate over mini-batches
        for i, (inputs, labels) in enumerate(train_loader):
            
            probability = 0.0
            coin_toss = random.random()  

            if coin_toss < probability:
                continue
            
            # Clear gradients
            optimizer_cf.zero_grad()
            inputs = inputs.to(device)
            labels = labels.to(device)
            
            # Forward pass
            
            prediction = Cf(inputs)
            
            
            # Calculate loss
            loss = criterion(prediction, labels)
            loss = loss.float()

            # Backpropagation
            loss.backward()
            
            optimizer_cf.step()
            
            # Update running loss
            running_loss += loss.item()
            
            
            PR.append(prediction)
            PL.append(labels)
            

        # Calculate average loss per epoch
        PR = torch.cat(PR, dim=0)
        PL = torch.cat(PL, dim=0)
        _, predicted = torch.max(PR.data, 1)
        _, lbl = torch.max(PL.data, 1)
        total = lbl.size(0)
        correct = (predicted == lbl).sum().item()

        accuracy = 100 * correct / total
        print(f'Train Accuracy: {accuracy:.2f}%')
        conf_matrix = confusion_matrix(lbl.cpu().detach().numpy(),predicted.cpu().detach().numpy())
        print('Confusion Matrix:')
        print(conf_matrix)
        # Calculate average loss per epoch
        epoch_loss = running_loss / len(train_loader)
        print(f"Epoch: {epoch+1}, Train Loss: {round(epoch_loss,6)}")
        
        if epoch%1==0:
            valid_latents = []
            VR,VL = [], []
            valid_loss = 0.0
            for j, (inp, lab) in enumerate(valid_loader):
                probability = 0.0
                coin_toss = random.random()  

                if coin_toss < probability:
                    continue
                inp = inp.to(device)
                lab = lab.to(device)
                
                with torch.no_grad():
                    # Forward pass
                    outp = Cf(inp)
                    
                VR.append(outp)
                VL.append(lab)
            
            VR = torch.cat(VR, dim=0)
            VL = torch.cat(VL, dim=0)
            _, vpre = torch.max(VR.data, 1)
            _, vlbl = torch.max(VL.data, 1)
            total = vlbl.size(0)
            correct = (vpre == vlbl).sum().item()

            vaccuracy = 100 * correct / total
            print('-----------------------------------------')
            print(f'Valid Accuracy: {vaccuracy:.2f}%')
            lb = vlbl.cpu().detach().numpy()
            pre = vpre.cpu().detach().numpy()
            conf_matrix = confusion_matrix(lb,pre)
            precision = precision_score(lb, pre,average=avg)
            recall = recall_score(lb, pre,average=avg)
            f1 = f1_score(lb, pre,average=avg)
            print('Confusion Matrix:')
            print(conf_matrix)
            print()
            print("Precision:", precision)
            print("Recall:", recall)
            print("F1 Score:", f1)
            print(epochs_without_improvement, best_loss)
            print('-----------------------------------------')
            print()
            print()
            
                
                    
        # Check for early stopping and save the best weights
        th = (conf_matrix[0][0]> conf_matrix[0][1]+conf_matrix[0][2] and conf_matrix[1][1]>conf_matrix[1][0]+conf_matrix[1][2] and conf_matrix[2][2]>conf_matrix[2][0]+conf_matrix[2][1])
        if th and vaccuracy > best_loss:
            best_loss = vaccuracy
            epochs_without_improvement = 0
            # Save the model weights
            torch.save(Cf.state_dict(), 'cnn60.pt')
            print('##############################################')
            print('saved', best_loss)
            print('##############################################')
            print()
            print()
            
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                print("Early stopping triggered. Training stopped.")
                break

# Recover the best weights
Cf.load_state_dict(torch.load('cnn60.pt'))


Train Accuracy: 47.47%
Confusion Matrix:
[[3520  827 3429]
 [1665  512 5599]
 [ 521  214 7041]]
Epoch: 1, Train Loss: 1.078274
-----------------------------------------
Valid Accuracy: 51.68%
Confusion Matrix:
[[50939     0 45544]
 [  666     0  2082]
 [   26     0   743]]

Precision: 0.9520167025483071
Recall: 0.51682
F1 Score: 0.6638764434776362
0 0
-----------------------------------------


Train Accuracy: 50.75%
Confusion Matrix:
[[4317    1 3458]
 [1836    0 5940]
 [ 254    0 7522]]
Epoch: 2, Train Loss: 1.025015
-----------------------------------------
Valid Accuracy: 52.11%
Confusion Matrix:
[[51354   150 44979]
 [  671    15  2062]
 [   26     0   743]]

Precision: 0.9545279931077726
Recall: 0.52112
F1 Score: 0.6676771278442654
1 0
-----------------------------------------


Train Accuracy: 52.88%
Confusion Matrix:
[[4315  159 3302]
 [1831  505 5440]
 [ 254    7 7515]]
Epoch: 3, Train Loss: 0.991741
-----------------------------------------
Valid Accuracy: 52.65%
Confusion Ma

Train Accuracy: 73.46%
Confusion Matrix:
[[5139 2172  465]
 [2288 4752  736]
 [ 263  268 7245]]
Epoch: 18, Train Loss: 0.816996
-----------------------------------------
Valid Accuracy: 63.66%
Confusion Matrix:
[[61259 29332  5892]
 [  783  1687   278]
 [   26    29   714]]

Precision: 0.9545450466135005
Recall: 0.6366
F1 Score: 0.7497368265948996
0 62.326
-----------------------------------------


##############################################
saved 63.66
##############################################


Train Accuracy: 73.63%
Confusion Matrix:
[[5196 2123  457]
 [2344 4736  696]
 [ 265  266 7245]]
Epoch: 19, Train Loss: 0.814426
-----------------------------------------
Valid Accuracy: 64.71%
Confusion Matrix:
[[62294 28553  5636]
 [  792  1701   255]
 [   26    29   714]]

Precision: 0.9546995998540554
Recall: 0.64709
F1 Score: 0.7575150003277835
0 63.66
-----------------------------------------


##############################################
saved 64.709
##########################

-----------------------------------------
Valid Accuracy: 66.66%
Confusion Matrix:
[[63934 27987  4562]
 [  570  1996   182]
 [   26    15   728]]

Precision: 0.9587703590569964
Recall: 0.66658
F1 Score: 0.7713609826699069
0 66.579
-----------------------------------------


##############################################
saved 66.658
##############################################


Train Accuracy: 78.67%
Confusion Matrix:
[[5306 2081  389]
 [1595 5698  483]
 [ 246  181 7349]]
Epoch: 36, Train Loss: 0.770315
-----------------------------------------
Valid Accuracy: 66.79%
Confusion Matrix:
[[64059 27898  4526]
 [  566  2000   182]
 [   26    15   728]]

Precision: 0.9588623775354503
Recall: 0.66787
F1 Score: 0.772308404470855
0 66.658
-----------------------------------------


##############################################
saved 66.787
##############################################


Train Accuracy: 78.80%
Confusion Matrix:
[[5312 2079  385]
 [1573 5721  482]
 [ 248  179 7349]]
Epoch: 

Train Accuracy: 80.29%
Confusion Matrix:
[[5369 2057  350]
 [1362 6011  403]
 [ 276  151 7349]]
Epoch: 52, Train Loss: 0.754759
-----------------------------------------
Valid Accuracy: 67.54%
Confusion Matrix:
[[64673 27553  4257]
 [  466  2137   145]
 [   29    12   728]]

Precision: 0.9605698120540743
Recall: 0.67538
F1 Score: 0.7775318656849562
0 67.46
-----------------------------------------


##############################################
saved 67.538
##############################################


Train Accuracy: 80.43%
Confusion Matrix:
[[5372 2055  349]
 [1343 6042  391]
 [ 276  151 7349]]
Epoch: 53, Train Loss: 0.754017
-----------------------------------------
Valid Accuracy: 67.57%
Confusion Matrix:
[[64694 27552  4237]
 [  466  2148   134]
 [   29    12   728]]

Precision: 0.9605883157644439
Recall: 0.6757
F1 Score: 0.7777097722698229
0 67.538
-----------------------------------------


##############################################
saved 67.57
##########################

Train Accuracy: 81.51%
Confusion Matrix:
[[5452 1999  325]
 [1206 6213  357]
 [ 292  135 7349]]
Epoch: 70, Train Loss: 0.743785
-----------------------------------------
Valid Accuracy: 67.79%
Confusion Matrix:
[[64863 27715  3905]
 [  423  2199   126]
 [   29    12   728]]

Precision: 0.9613487076424057
Recall: 0.6779
F1 Score: 0.7793033258414116
2 67.768
-----------------------------------------


##############################################
saved 67.79
##############################################


Train Accuracy: 81.52%
Confusion Matrix:
[[5453 2000  323]
 [1204 6215  357]
 [ 291  136 7349]]
Epoch: 71, Train Loss: 0.74326
-----------------------------------------
Valid Accuracy: 67.79%
Confusion Matrix:
[[64861 27727  3895]
 [  417  2205   126]
 [   29    12   728]]

Precision: 0.9614433018281631
Recall: 0.67794
F1 Score: 0.7793294438769844
0 67.79
-----------------------------------------


##############################################
saved 67.794
###########################

Train Accuracy: 82.45%
Confusion Matrix:
[[5565 1916  295]
 [1107 6321  348]
 [ 287  140 7349]]
Epoch: 88, Train Loss: 0.734682
-----------------------------------------
Valid Accuracy: 67.89%
Confusion Matrix:
[[64912 28119  3452]
 [  385  2251   112]
 [   17    24   728]]

Precision: 0.9622311334635851
Recall: 0.67891
F1 Score: 0.7801133985539753
3 67.951
-----------------------------------------


Train Accuracy: 82.50%
Confusion Matrix:
[[5570 1911  295]
 [1105 6327  344]
 [ 285  142 7349]]
Epoch: 89, Train Loss: 0.734127
-----------------------------------------
Valid Accuracy: 67.88%
Confusion Matrix:
[[64901 28161  3421]
 [  385  2251   112]
 [   17    24   728]]

Precision: 0.9622368143235682
Recall: 0.6788
F1 Score: 0.780043745547345
4 67.951
-----------------------------------------


Train Accuracy: 82.57%
Confusion Matrix:
[[5577 1906  293]
 [1104 6335  337]
 [ 283  144 7349]]
Epoch: 90, Train Loss: 0.733562
-----------------------------------------
Valid Accuracy: 67.92%
C

Train Accuracy: 83.38%
Confusion Matrix:
[[5681 1810  285]
 [1061 6420  295]
 [ 263  164 7349]]
Epoch: 106, Train Loss: 0.724819
-----------------------------------------
Valid Accuracy: 68.75%
Confusion Matrix:
[[65750 27409  3324]
 [  377  2267   104]
 [   11    30   728]]

Precision: 0.9626139730952602
Recall: 0.68745
F1 Score: 0.7863017168456095
0 68.706
-----------------------------------------


##############################################
saved 68.745
##############################################


Train Accuracy: 83.41%
Confusion Matrix:
[[5690 1802  284]
 [1061 6420  295]
 [ 262  165 7349]]
Epoch: 107, Train Loss: 0.724359
-----------------------------------------
Valid Accuracy: 68.80%
Confusion Matrix:
[[65806 27341  3336]
 [  377  2267   104]
 [   11    30   728]]

Precision: 0.9626196949010863
Recall: 0.68801
F1 Score: 0.786699946179064
0 68.745
-----------------------------------------


##############################################
saved 68.801
######################

Train Accuracy: 84.05%
Confusion Matrix:
[[5801 1703  272]
 [1023 6457  296]
 [ 245  182 7349]]
Epoch: 122, Train Loss: 0.718195
-----------------------------------------
Valid Accuracy: 69.87%
Confusion Matrix:
[[66868 26317  3298]
 [  372  2272   104]
 [   12    29   728]]

Precision: 0.9628581275991875
Recall: 0.69868
F1 Score: 0.7943234802888282
0 69.805
-----------------------------------------


##############################################
saved 69.868
##############################################


Train Accuracy: 84.07%
Confusion Matrix:
[[5806 1698  272]
 [1024 6456  296]
 [ 244  183 7349]]
Epoch: 123, Train Loss: 0.717826
-----------------------------------------
Valid Accuracy: 69.93%
Confusion Matrix:
[[66933 26252  3298]
 [  372  2272   104]
 [   12    29   728]]

Precision: 0.9628684134982487
Recall: 0.69933
F1 Score: 0.7947847644311256
0 69.868
-----------------------------------------


##############################################
saved 69.933
#####################

Train Accuracy: 84.52%
Confusion Matrix:
[[5885 1630  261]
 [ 997 6483  296]
 [ 233  194 7349]]
Epoch: 138, Train Loss: 0.712819
-----------------------------------------
Valid Accuracy: 71.49%
Confusion Matrix:
[[68484 24727  3272]
 [  366  2278   104]
 [   12    29   728]]

Precision: 0.9632135121199256
Recall: 0.7149
F1 Score: 0.8057445429479874
0 71.431
-----------------------------------------


##############################################
saved 71.49
##############################################


Train Accuracy: 84.53%
Confusion Matrix:
[[5886 1629  261]
 [ 996 6484  296]
 [ 233  194 7349]]
Epoch: 139, Train Loss: 0.712512
-----------------------------------------
Valid Accuracy: 71.58%
Confusion Matrix:
[[68570 24636  3277]
 [  366  2278   104]
 [   12    29   728]]

Precision: 0.9632262791082316
Recall: 0.71576
F1 Score: 0.8063427241808838
0 71.49
-----------------------------------------


##############################################
saved 71.576
########################

Train Accuracy: 84.90%
Confusion Matrix:
[[5967 1562  247]
 [ 988 6490  298]
 [ 230  197 7349]]
Epoch: 154, Train Loss: 0.708089
-----------------------------------------
Valid Accuracy: 72.99%
Confusion Matrix:
[[69979 23378  3126]
 [  357  2284   107]
 [   12    29   728]]

Precision: 0.9636255345823681
Recall: 0.72991
F1 Score: 0.8161970941287982
0 72.901
-----------------------------------------


##############################################
saved 72.991
##############################################


Train Accuracy: 84.93%
Confusion Matrix:
[[5972 1557  247]
 [ 986 6492  298]
 [ 230  197 7349]]
Epoch: 155, Train Loss: 0.707802
-----------------------------------------
Valid Accuracy: 73.05%
Confusion Matrix:
[[70041 23319  3123]
 [  357  2284   107]
 [   12    29   728]]

Precision: 0.9636366856669641
Recall: 0.73053
F1 Score: 0.8166239383820171
0 72.991
-----------------------------------------


##############################################
saved 73.053
#####################

Train Accuracy: 85.30%
Confusion Matrix:
[[6038 1500  238]
 [ 978 6512  286]
 [ 233  194 7349]]
Epoch: 170, Train Loss: 0.703441
-----------------------------------------
Valid Accuracy: 74.42%
Confusion Matrix:
[[71405 21992  3086]
 [  357  2284   107]
 [   12    29   728]]

Precision: 0.9638798174499522
Recall: 0.74417
F1 Score: 0.8259376365678267
0 74.325
-----------------------------------------


##############################################
saved 74.417
##############################################


Train Accuracy: 85.34%
Confusion Matrix:
[[6045 1493  238]
 [ 975 6515  286]
 [ 237  190 7349]]
Epoch: 171, Train Loss: 0.703155
-----------------------------------------
Valid Accuracy: 74.51%
Confusion Matrix:
[[71498 21903  3082]
 [  357  2284   107]
 [   12    29   728]]

Precision: 0.9638971852679564
Recall: 0.7451
F1 Score: 0.8265685910086598
0 74.417
-----------------------------------------


##############################################
saved 74.51
#######################

Train Accuracy: 85.83%
Confusion Matrix:
[[6152 1392  232]
 [ 971 6521  284]
 [ 234  193 7349]]
Epoch: 186, Train Loss: 0.69866
-----------------------------------------
Valid Accuracy: 76.01%
Confusion Matrix:
[[72997 20451  3035]
 [  356  2285   107]
 [   12    29   728]]

Precision: 0.9641952522675673
Recall: 0.7601
F1 Score: 0.8366620949883827
0 75.935
-----------------------------------------


##############################################
saved 76.01
##############################################


Train Accuracy: 85.88%
Confusion Matrix:
[[6163 1382  231]
 [ 969 6522  285]
 [ 232  195 7349]]
Epoch: 187, Train Loss: 0.698351
-----------------------------------------
Valid Accuracy: 76.09%
Confusion Matrix:
[[73078 20358  3047]
 [  356  2285   107]
 [   12    29   728]]

Precision: 0.9642074322487217
Recall: 0.76091
F1 Score: 0.8371983720249649
0 76.01
-----------------------------------------


##############################################
saved 76.091
#########################

Train Accuracy: 86.24%
Confusion Matrix:
[[6242 1304  230]
 [ 967 6527  282]
 [ 234  193 7349]]
Epoch: 202, Train Loss: 0.693947
-----------------------------------------
Valid Accuracy: 77.30%
Confusion Matrix:
[[74278 19228  2977]
 [  350  2291   107]
 [    8    33   728]]

Precision: 0.9645918409493033
Recall: 0.77297
F1 Score: 0.8452375198422181
0 77.254
-----------------------------------------


##############################################
saved 77.297
##############################################


Train Accuracy: 86.29%
Confusion Matrix:
[[6251 1296  229]
 [ 964 6530  282]
 [ 237  190 7349]]
Epoch: 203, Train Loss: 0.693677
-----------------------------------------
Valid Accuracy: 77.37%
Confusion Matrix:
[[74349 19165  2969]
 [  350  2291   107]
 [    8    33   728]]

Precision: 0.9646078918113267
Recall: 0.77368
F1 Score: 0.845708184675198
0 77.297
-----------------------------------------


##############################################
saved 77.368
######################

Train Accuracy: 86.66%
Confusion Matrix:
[[6331 1217  228]
 [ 957 6537  282]
 [ 247  180 7349]]
Epoch: 218, Train Loss: 0.689869
-----------------------------------------
Valid Accuracy: 77.73%
Confusion Matrix:
[[74705 18858  2920]
 [  347  2294   107]
 [    5    36   728]]

Precision: 0.964771295028043
Recall: 0.77727
F1 Score: 0.8481016418229245
0 77.682
-----------------------------------------


##############################################
saved 77.727
##############################################


Train Accuracy: 86.69%
Confusion Matrix:
[[6335 1213  228]
 [ 955 6539  282]
 [ 245  182 7349]]
Epoch: 219, Train Loss: 0.689628
-----------------------------------------
Valid Accuracy: 77.74%
Confusion Matrix:
[[74718 18845  2920]
 [  347  2294   107]
 [    5    36   728]]

Precision: 0.9647739051865057
Recall: 0.7774
F1 Score: 0.8481870495121554
0 77.727
-----------------------------------------


##############################################
saved 77.74
########################

Train Accuracy: 86.99%
Confusion Matrix:
[[6402 1149  225]
 [ 950 6543  283]
 [ 252  175 7349]]
Epoch: 235, Train Loss: 0.686092
-----------------------------------------
Valid Accuracy: 78.35%
Confusion Matrix:
[[75331 18286  2866]
 [  347  2294   107]
 [    5    36   728]]

Precision: 0.9649130236072304
Recall: 0.78353
F1 Score: 0.8522212202193313
0 78.296
-----------------------------------------


##############################################
saved 78.353
##############################################


Train Accuracy: 87.01%
Confusion Matrix:
[[6405 1146  225]
 [ 950 6543  283]
 [ 253  174 7349]]
Epoch: 236, Train Loss: 0.685883
-----------------------------------------
Valid Accuracy: 78.36%
Confusion Matrix:
[[75340 18287  2856]
 [  347  2294   107]
 [    5    36   728]]

Precision: 0.9649175070728516
Recall: 0.78362
F1 Score: 0.8522833388177152
0 78.353
-----------------------------------------


##############################################
saved 78.362
#####################

Train Accuracy: 87.32%
Confusion Matrix:
[[6476 1081  219]
 [ 948 6545  283]
 [ 263  164 7349]]
Epoch: 251, Train Loss: 0.682816
-----------------------------------------
Valid Accuracy: 79.25%
Confusion Matrix:
[[76226 17495  2762]
 [  348  2294   106]
 [    4    37   728]]

Precision: 0.9651314800715277
Recall: 0.79248
F1 Score: 0.8580832512601128
0 79.204
-----------------------------------------


##############################################
saved 79.248
##############################################


Train Accuracy: 87.33%
Confusion Matrix:
[[6478 1079  219]
 [ 948 6545  283]
 [ 263  164 7349]]
Epoch: 252, Train Loss: 0.682616
-----------------------------------------
Valid Accuracy: 79.34%
Confusion Matrix:
[[76314 17413  2756]
 [  348  2294   106]
 [    4    37   728]]

Precision: 0.965152378067429
Recall: 0.79336
F1 Score: 0.858655896520249
0 79.248
-----------------------------------------


##############################################
saved 79.336
#######################

Train Accuracy: 87.61%
Confusion Matrix:
[[6542 1016  218]
 [ 949 6546  281]
 [ 252  175 7349]]
Epoch: 267, Train Loss: 0.679677
-----------------------------------------
Valid Accuracy: 80.37%
Confusion Matrix:
[[77351 16391  2741]
 [  348  2294   106]
 [    4    37   728]]

Precision: 0.9653923311854671
Recall: 0.80373
F1 Score: 0.8653563798939404
0 80.333
-----------------------------------------


##############################################
saved 80.373
##############################################


Train Accuracy: 87.63%
Confusion Matrix:
[[6548 1010  218]
 [ 949 6546  281]
 [ 253  174 7349]]
Epoch: 268, Train Loss: 0.679486
-----------------------------------------
Valid Accuracy: 80.43%
Confusion Matrix:
[[77408 16317  2758]
 [  348  2294   106]
 [    4    37   728]]

Precision: 0.9654014853191297
Recall: 0.8043
F1 Score: 0.8657175713358156
0 80.373
-----------------------------------------


##############################################
saved 80.43
#######################

Train Accuracy: 87.84%
Confusion Matrix:
[[6596  963  217]
 [ 950 6546  280]
 [ 259  168 7349]]
Epoch: 283, Train Loss: 0.676752
-----------------------------------------
Valid Accuracy: 81.21%
Confusion Matrix:
[[78187 15545  2751]
 [  348  2294   106]
 [   10    31   728]]

Precision: 0.9655216508298827
Recall: 0.81209
F1 Score: 0.8706876232468295
0 81.188
-----------------------------------------


##############################################
saved 81.209
##############################################


Train Accuracy: 87.86%
Confusion Matrix:
[[6602  957  217]
 [ 950 6546  280]
 [ 259  168 7349]]
Epoch: 284, Train Loss: 0.676574
-----------------------------------------
Valid Accuracy: 81.22%
Confusion Matrix:
[[78203 15532  2748]
 [  348  2294   106]
 [   10    31   728]]

Precision: 0.9655264224784121
Recall: 0.81225
F1 Score: 0.8707908443505661
0 81.209
-----------------------------------------


##############################################
saved 81.225
#####################

Train Accuracy: 88.08%
Confusion Matrix:
[[6652  909  215]
 [ 951 6546  279]
 [ 267  160 7349]]
Epoch: 299, Train Loss: 0.674119
-----------------------------------------
Valid Accuracy: 82.03%
Confusion Matrix:
[[79013 14721  2749]
 [  348  2294   106]
 [   10    31   728]]

Precision: 0.9657388133871541
Recall: 0.82035
F1 Score: 0.875958240791828
0 82.011
-----------------------------------------


##############################################
saved 82.035
##############################################


Train Accuracy: 88.10%
Confusion Matrix:
[[6658  902  216]
 [ 951 6546  279]
 [ 269  158 7349]]
Epoch: 300, Train Loss: 0.673962
-----------------------------------------
Valid Accuracy: 82.06%
Confusion Matrix:
[[79043 14691  2749]
 [  348  2294   106]
 [   10    31   728]]

Precision: 0.9657469776925517
Recall: 0.82065
F1 Score: 0.876149161122995
0 82.035
-----------------------------------------


##############################################
saved 82.065
#######################

Train Accuracy: 88.34%
Confusion Matrix:
[[6709  855  212]
 [ 950 6546  280]
 [ 252  170 7354]]
Epoch: 315, Train Loss: 0.671397
-----------------------------------------
Valid Accuracy: 82.79%
Confusion Matrix:
[[79768 13902  2813]
 [  348  2294   106]
 [   14    26   729]]

Precision: 0.965893988837001
Recall: 0.82791
F1 Score: 0.880723578158157
0 82.74
-----------------------------------------


##############################################
saved 82.791
##############################################


Train Accuracy: 88.37%
Confusion Matrix:
[[6715  850  211]
 [ 949 6546  281]
 [ 251  171 7354]]
Epoch: 316, Train Loss: 0.671223
-----------------------------------------
Valid Accuracy: 82.85%
Confusion Matrix:
[[79825 13848  2810]
 [  348  2294   106]
 [   14    26   729]]

Precision: 0.9659113310816694
Recall: 0.82848
F1 Score: 0.8810856637492048
0 82.791
-----------------------------------------


##############################################
saved 82.848
########################

Train Accuracy: 88.64%
Confusion Matrix:
[[6777  792  207]
 [ 947 6546  283]
 [ 263  159 7354]]
Epoch: 331, Train Loss: 0.66866
-----------------------------------------
Valid Accuracy: 83.62%
Confusion Matrix:
[[80595 13106  2782]
 [  348  2294   106]
 [   18    22   729]]

Precision: 0.9661058136062628
Recall: 0.83618
F1 Score: 0.8859460008540533
0 83.572
-----------------------------------------


##############################################
saved 83.618
##############################################


Train Accuracy: 88.65%
Confusion Matrix:
[[6781  788  207]
 [ 947 6546  283]
 [ 265  157 7354]]
Epoch: 332, Train Loss: 0.668499
-----------------------------------------
Valid Accuracy: 83.64%
Confusion Matrix:
[[80616 13087  2780]
 [  348  2294   106]
 [   18    22   729]]

Precision: 0.9661128443281879
Recall: 0.83639
F1 Score: 0.8860790600289293
0 83.618
-----------------------------------------


##############################################
saved 83.639
######################

-----------------------------------------
Valid Accuracy: 84.34%
Confusion Matrix:
[[81313 12421  2749]
 [  348  2294   106]
 [   19    21   729]]

Precision: 0.9663369558172824
Recall: 0.84336
F1 Score: 0.890477162476249
0 84.279
-----------------------------------------


##############################################
saved 84.336
##############################################


Train Accuracy: 88.89%
Confusion Matrix:
[[6837  734  205]
 [ 945 6546  285]
 [ 262  160 7354]]
Epoch: 348, Train Loss: 0.666103
-----------------------------------------
Valid Accuracy: 84.37%
Confusion Matrix:
[[81345 12392  2746]
 [  348  2294   106]
 [   19    21   729]]

Precision: 0.9663483993066968
Recall: 0.84368
F1 Score: 0.8906792918324249
0 84.336
-----------------------------------------


##############################################
saved 84.368
##############################################


Train Accuracy: 88.90%
Confusion Matrix:
[[6839  733  204]
 [ 945 6546  285]
 [ 264  158 7354]]
Epoch:

-----------------------------------------
Valid Accuracy: 84.89%
Confusion Matrix:
[[81872 11909  2702]
 [  348  2294   106]
 [   32     8   729]]

Precision: 0.9663934353255952
Recall: 0.84895
F1 Score: 0.893945142987221
0 84.865
-----------------------------------------


##############################################
saved 84.895
##############################################


Train Accuracy: 89.02%
Confusion Matrix:
[[6866  708  202]
 [ 946 6546  284]
 [ 263  159 7354]]
Epoch: 364, Train Loss: 0.664096
-----------------------------------------
Valid Accuracy: 84.93%
Confusion Matrix:
[[81909 11887  2687]
 [  348  2294   106]
 [   32     8   729]]

Precision: 0.9664090677288736
Recall: 0.84932
F1 Score: 0.894180338661716
0 84.895
-----------------------------------------


##############################################
saved 84.932
##############################################


Train Accuracy: 89.02%
Confusion Matrix:
[[6867  708  201]
 [ 946 6546  284]
 [ 264  158 7354]]
Epoch: 

Train Accuracy: 89.37%
Confusion Matrix:
[[6922  658  196]
 [ 921 6573  282]
 [ 249  173 7354]]
Epoch: 382, Train Loss: 0.660725
-----------------------------------------
Valid Accuracy: 84.86%
Confusion Matrix:
[[81820 12073  2590]
 [  336  2306   106]
 [    4    36   729]]

Precision: 0.9668701047485921
Recall: 0.84855
F1 Score: 0.893858254477794
10 85.047
-----------------------------------------


Train Accuracy: 89.39%
Confusion Matrix:
[[6926  654  196]
 [ 922 6573  281]
 [ 248  174 7354]]
Epoch: 383, Train Loss: 0.660571
-----------------------------------------
Valid Accuracy: 84.90%
Confusion Matrix:
[[81867 12034  2582]
 [  336  2306   106]
 [    4    36   729]]

Precision: 0.9668881454226355
Recall: 0.84902
F1 Score: 0.8941552690660083
11 85.047
-----------------------------------------


Train Accuracy: 89.40%
Confusion Matrix:
[[6928  652  196]
 [ 920 6573  283]
 [ 250  172 7354]]
Epoch: 384, Train Loss: 0.660423
-----------------------------------------
Valid Accuracy: 84

-----------------------------------------
Valid Accuracy: 85.50%
Confusion Matrix:
[[82469 11501  2513]
 [  336  2306   106]
 [    8    32   729]]

Precision: 0.9670755994245449
Recall: 0.85504
F1 Score: 0.8979306766938908
0 85.481
-----------------------------------------


##############################################
saved 85.504
##############################################


Train Accuracy: 89.60%
Confusion Matrix:
[[6974  608  194]
 [ 921 6573  282]
 [ 244  178 7354]]
Epoch: 400, Train Loss: 0.658291
-----------------------------------------
Valid Accuracy: 85.59%
Confusion Matrix:
[[82551 11447  2485]
 [  336  2306   106]
 [    8    32   729]]

Precision: 0.9671116230921573
Recall: 0.85586
F1 Score: 0.8984506591129162
0 85.504
-----------------------------------------


##############################################
saved 85.586
##############################################


Train Accuracy: 89.61%
Confusion Matrix:
[[6977  606  193]
 [ 920 6573  283]
 [ 241  181 7354]]
Epoch

-----------------------------------------
Valid Accuracy: 86.10%
Confusion Matrix:
[[83064 10916  2503]
 [  336  2306   106]
 [   16    24   729]]

Precision: 0.9672220498873007
Recall: 0.86099
F1 Score: 0.9016277628613667
0 86.049
-----------------------------------------


##############################################
saved 86.099
##############################################


Train Accuracy: 89.77%
Confusion Matrix:
[[7015  572  189]
 [ 918 6573  285]
 [ 255  167 7354]]
Epoch: 416, Train Loss: 0.656391
-----------------------------------------
Valid Accuracy: 86.13%
Confusion Matrix:
[[83096 10884  2503]
 [  336  2306   106]
 [   16    24   729]]

Precision: 0.9672351964490341
Recall: 0.86131
F1 Score: 0.9018283749067588
0 86.099
-----------------------------------------


##############################################
saved 86.131
##############################################


Train Accuracy: 89.79%
Confusion Matrix:
[[7019  568  189]
 [ 918 6573  285]
 [ 258  164 7354]]
Epoch

-----------------------------------------
Valid Accuracy: 86.86%
Confusion Matrix:
[[83823 10196  2464]
 [  336  2306   106]
 [   37     3   729]]

Precision: 0.9673224580535124
Recall: 0.86858
F1 Score: 0.9062986700319751
0 86.829
-----------------------------------------


##############################################
saved 86.858
##############################################


Train Accuracy: 89.89%
Confusion Matrix:
[[7042  547  187]
 [ 918 6573  285]
 [ 247  175 7354]]
Epoch: 432, Train Loss: 0.654825
-----------------------------------------
Valid Accuracy: 86.89%
Confusion Matrix:
[[83850 10169  2464]
 [  336  2306   106]
 [   37     3   729]]

Precision: 0.9673347933706542
Recall: 0.86885
F1 Score: 0.9064679620722866
0 86.858
-----------------------------------------


##############################################
saved 86.885
##############################################


Train Accuracy: 89.89%
Confusion Matrix:
[[7042  546  188]
 [ 919 6573  284]
 [ 242  180 7354]]
Epoch

-----------------------------------------
Valid Accuracy: 87.51%
Confusion Matrix:
[[84478  9559  2446]
 [  351  2306    91]
 [   37     3   729]]

Precision: 0.9674748308516573
Recall: 0.87513
F1 Score: 0.9103454535215241
0 87.472
-----------------------------------------


##############################################
saved 87.513
##############################################


Train Accuracy: 89.97%
Confusion Matrix:
[[7061  531  184]
 [ 923 6573  280]
 [ 239  183 7354]]
Epoch: 448, Train Loss: 0.653642
-----------------------------------------
Valid Accuracy: 87.53%
Confusion Matrix:
[[84499  9545  2439]
 [  351  2306    91]
 [   37     3   729]]

Precision: 0.9674859150344188
Recall: 0.87534
F1 Score: 0.9104779435870863
0 87.513
-----------------------------------------


##############################################
saved 87.534
##############################################


Train Accuracy: 89.97%
Confusion Matrix:
[[7062  530  184]
 [ 923 6573  280]
 [ 239  183 7354]]
Epoch

-----------------------------------------
Valid Accuracy: 88.02%
Confusion Matrix:
[[84987  9046  2450]
 [  350  2306    92]
 [   31     9   729]]

Precision: 0.9678155416562302
Recall: 0.88022
F1 Score: 0.9135733140637635
0 87.979
-----------------------------------------


##############################################
saved 88.022
##############################################


Train Accuracy: 90.09%
Confusion Matrix:
[[7088  503  185]
 [ 921 6575  280]
 [ 227  195 7354]]
Epoch: 464, Train Loss: 0.65227
-----------------------------------------
Valid Accuracy: 88.07%
Confusion Matrix:
[[85033  9000  2450]
 [  350  2306    92]
 [   31     9   729]]

Precision: 0.9678405365092646
Recall: 0.88068
F1 Score: 0.9138626286530488
0 88.022
-----------------------------------------


##############################################
saved 88.068
##############################################


Train Accuracy: 90.11%
Confusion Matrix:
[[7093  498  185]
 [ 921 6575  280]
 [ 226  196 7354]]
Epoch:

Train Accuracy: 90.25%
Confusion Matrix:
[[7122  471  183]
 [ 915 6578  283]
 [ 218  204 7354]]
Epoch: 482, Train Loss: 0.650569
-----------------------------------------
Valid Accuracy: 88.03%
Confusion Matrix:
[[84995  9071  2417]
 [  336  2309   103]
 [   15    25   729]]

Precision: 0.9681508940663174
Recall: 0.88033
F1 Score: 0.913766246210916
11 88.195
-----------------------------------------


Train Accuracy: 90.26%
Confusion Matrix:
[[7123  470  183]
 [ 915 6578  283]
 [ 219  203 7354]]
Epoch: 483, Train Loss: 0.650492
-----------------------------------------
Valid Accuracy: 88.01%
Confusion Matrix:
[[84976  9093  2414]
 [  336  2309   103]
 [   15    25   729]]

Precision: 0.9681408940435791
Recall: 0.88014
F1 Score: 0.9136470206634334
12 88.195
-----------------------------------------


Train Accuracy: 90.26%
Confusion Matrix:
[[7124  469  183]
 [ 914 6578  284]
 [ 220  202 7354]]
Epoch: 484, Train Loss: 0.650418
-----------------------------------------
Valid Accuracy: 88

-----------------------------------------
Valid Accuracy: 88.20%
Confusion Matrix:
[[85165  8959  2359]
 [  336  2309   103]
 [    6    34   729]]

Precision: 0.9683419825247926
Recall: 0.88203
F1 Score: 0.9148774028963395
31 88.195
-----------------------------------------


##############################################
saved 88.203
##############################################


Train Accuracy: 90.41%
Confusion Matrix:
[[7158  436  182]
 [ 918 6578  280]
 [ 228  194 7354]]
Epoch: 503, Train Loss: 0.64882
-----------------------------------------
Valid Accuracy: 88.22%
Confusion Matrix:
[[85183  8941  2359]
 [  336  2309   103]
 [    6    34   729]]

Precision: 0.968351750311246
Recall: 0.88221
F1 Score: 0.9149905212304943
0 88.203
-----------------------------------------


##############################################
saved 88.221
##############################################


Train Accuracy: 90.41%
Confusion Matrix:
[[7158  436  182]
 [ 919 6578  279]
 [ 230  192 7354]]
Epoch:

-----------------------------------------
Valid Accuracy: 88.90%
Confusion Matrix:
[[85860  8285  2338]
 [  348  2309    91]
 [   15    25   729]]

Precision: 0.9685184931426536
Recall: 0.88898
F1 Score: 0.919164199498042
0 88.823
-----------------------------------------


##############################################
saved 88.898
##############################################


Train Accuracy: 90.48%
Confusion Matrix:
[[7176  417  183]
 [ 919 6578  279]
 [ 243  179 7354]]
Epoch: 519, Train Loss: 0.647814
-----------------------------------------
Valid Accuracy: 88.94%
Confusion Matrix:
[[85899  8249  2335]
 [  348  2309    91]
 [   19    21   729]]

Precision: 0.9685000613022333
Recall: 0.88937
F1 Score: 0.9193933113705847
0 88.898
-----------------------------------------


##############################################
saved 88.937
##############################################


Train Accuracy: 90.48%
Confusion Matrix:
[[7175  418  183]
 [ 916 6578  282]
 [ 243  179 7354]]
Epoch:

Train Accuracy: 90.61%
Confusion Matrix:
[[7205  393  178]
 [ 915 6578  283]
 [ 239  183 7354]]
Epoch: 536, Train Loss: 0.646623
-----------------------------------------
Valid Accuracy: 89.03%
Confusion Matrix:
[[85997  8163  2323]
 [  334  2309   105]
 [   16    24   729]]

Precision: 0.9687401715691244
Recall: 0.89035
F1 Score: 0.9200840237226499
7 89.181
-----------------------------------------


Train Accuracy: 90.61%
Confusion Matrix:
[[7206  392  178]
 [ 916 6578  282]
 [ 237  185 7354]]
Epoch: 537, Train Loss: 0.646536
-----------------------------------------
Valid Accuracy: 88.99%
Confusion Matrix:
[[85956  8193  2334]
 [  334  2309   105]
 [   16    24   729]]

Precision: 0.9687149183587476
Recall: 0.88994
F1 Score: 0.919825148795638
8 89.181
-----------------------------------------


Train Accuracy: 90.62%
Confusion Matrix:
[[7207  391  178]
 [ 918 6578  280]
 [ 236  186 7354]]
Epoch: 538, Train Loss: 0.646454
-----------------------------------------
Valid Accuracy: 88.9

-----------------------------------------
Valid Accuracy: 89.40%
Confusion Matrix:
[[86361  7782  2340]
 [  334  2309   105]
 [   16    24   729]]

Precision: 0.9689747846267289
Recall: 0.89399
F1 Score: 0.9223862303040196
0 89.334
-----------------------------------------


##############################################
saved 89.399
##############################################


Train Accuracy: 90.72%
Confusion Matrix:
[[7230  369  177]
 [ 917 6578  281]
 [ 242  180 7354]]
Epoch: 556, Train Loss: 0.64529
-----------------------------------------
Valid Accuracy: 89.42%
Confusion Matrix:
[[86382  7761  2340]
 [  334  2309   105]
 [   16    24   729]]

Precision: 0.9689887781765714
Recall: 0.8942
F1 Score: 0.9225192731767106
0 89.399
-----------------------------------------


##############################################
saved 89.42
##############################################


Train Accuracy: 90.72%
Confusion Matrix:
[[7230  369  177]
 [ 917 6578  281]
 [ 237  185 7354]]
Epoch: 5

-----------------------------------------
Valid Accuracy: 89.78%
Confusion Matrix:
[[86741  7405  2337]
 [  335  2309   104]
 [   20    20   729]]

Precision: 0.9691843716041779
Recall: 0.89779
F1 Score: 0.9247767996329299
0 89.77
-----------------------------------------


##############################################
saved 89.779
##############################################


Train Accuracy: 90.81%
Confusion Matrix:
[[7252  347  177]
 [ 913 6578  285]
 [ 221  201 7354]]
Epoch: 573, Train Loss: 0.644209
-----------------------------------------
Valid Accuracy: 89.79%
Confusion Matrix:
[[86749  7397  2337]
 [  335  2309   104]
 [   26    14   729]]

Precision: 0.9691279364854031
Recall: 0.89787
F1 Score: 0.9248027728799593
0 89.779
-----------------------------------------


##############################################
saved 89.787
##############################################


Train Accuracy: 90.81%
Confusion Matrix:
[[7253  346  177]
 [ 915 6578  283]
 [ 224  198 7354]]
Epoch:

Train Accuracy: 90.87%
Confusion Matrix:
[[7265  335  176]
 [ 919 6578  279]
 [ 239  183 7354]]
Epoch: 589, Train Loss: 0.643403
-----------------------------------------
Valid Accuracy: 90.06%
Confusion Matrix:
[[87024  7138  2321]
 [  338  2309   101]
 [   38     2   729]]

Precision: 0.9691735008431492
Recall: 0.90062
F1 Score: 0.9264905977262674
0 90.038
-----------------------------------------


##############################################
saved 90.062
##############################################


Train Accuracy: 90.87%
Confusion Matrix:
[[7265  336  175]
 [ 919 6578  279]
 [ 243  179 7354]]
Epoch: 590, Train Loss: 0.643363
-----------------------------------------
Valid Accuracy: 90.09%
Confusion Matrix:
[[87057  7109  2317]
 [  338  2309   101]
 [   38     2   729]]

Precision: 0.9691980017495421
Recall: 0.90095
F1 Score: 0.9267006946260136
0 90.062
-----------------------------------------


##############################################
saved 90.095
#####################

Train Accuracy: 90.91%
Confusion Matrix:
[[7276  324  176]
 [ 915 6578  283]
 [ 234  188 7354]]
Epoch: 607, Train Loss: 0.642705
-----------------------------------------
Valid Accuracy: 90.28%
Confusion Matrix:
[[87239  6929  2315]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9692144095846249
Recall: 0.90277
F1 Score: 0.9278127792630125
0 90.255
-----------------------------------------


##############################################
saved 90.277
##############################################


Train Accuracy: 90.93%
Confusion Matrix:
[[7279  321  176]
 [ 915 6578  283]
 [ 236  186 7354]]
Epoch: 608, Train Loss: 0.64267
-----------------------------------------
Valid Accuracy: 90.30%
Confusion Matrix:
[[87263  6905  2315]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9692334661070632
Recall: 0.90301
F1 Score: 0.9279663530456241
0 90.277
-----------------------------------------


##############################################
saved 90.301
######################

Train Accuracy: 91.01%
Confusion Matrix:
[[7298  299  179]
 [ 916 6578  282]
 [ 248  174 7354]]
Epoch: 626, Train Loss: 0.641795
-----------------------------------------
Valid Accuracy: 90.16%
Confusion Matrix:
[[87123  7052  2308]
 [  338  2309   101]
 [   35     5   729]]

Precision: 0.9692780153689659
Recall: 0.90161
F1 Score: 0.9271332406924535
14 90.318
-----------------------------------------


Train Accuracy: 91.01%
Confusion Matrix:
[[7298  300  178]
 [ 916 6578  282]
 [ 248  174 7354]]
Epoch: 627, Train Loss: 0.641757
-----------------------------------------
Valid Accuracy: 90.21%
Confusion Matrix:
[[87168  7007  2308]
 [  338  2309   101]
 [   38     2   729]]

Precision: 0.9692821056773493
Recall: 0.90206
F1 Score: 0.9274084283131107
15 90.318
-----------------------------------------


Train Accuracy: 91.01%
Confusion Matrix:
[[7298  300  178]
 [ 916 6578  282]
 [ 247  175 7354]]
Epoch: 628, Train Loss: 0.641725
-----------------------------------------
Valid Accuracy: 9

Train Accuracy: 91.03%
Confusion Matrix:
[[7303  296  177]
 [ 915 6578  283]
 [ 244  178 7354]]
Epoch: 643, Train Loss: 0.641403
-----------------------------------------
Valid Accuracy: 90.53%
Confusion Matrix:
[[87495  6697  2291]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9694175564147359
Recall: 0.90533
F1 Score: 0.9294492909878211
0 90.531
-----------------------------------------


##############################################
saved 90.533
##############################################


Train Accuracy: 91.03%
Confusion Matrix:
[[7304  294  178]
 [ 916 6578  282]
 [ 242  180 7354]]
Epoch: 644, Train Loss: 0.641373
-----------------------------------------
Valid Accuracy: 90.52%
Confusion Matrix:
[[87479  6720  2284]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9694029039222891
Recall: 0.90517
F1 Score: 0.9293454372881106
0 90.533
-----------------------------------------


Train Accuracy: 91.03%
Confusion Matrix:
[[7304  294  178]
 [ 916 6578  282]
 [ 2

-----------------------------------------
Valid Accuracy: 90.42%
Confusion Matrix:
[[87383  6779  2321]
 [  349  2309    90]
 [   23    17   729]]

Precision: 0.9694942105562521
Recall: 0.90421
F1 Score: 0.9288010216920067
11 90.842
-----------------------------------------


Train Accuracy: 91.10%
Confusion Matrix:
[[7320  281  175]
 [ 916 6578  282]
 [ 247  175 7354]]
Epoch: 663, Train Loss: 0.64058
-----------------------------------------
Valid Accuracy: 90.44%
Confusion Matrix:
[[87406  6763  2314]
 [  349  2309    90]
 [   23    17   729]]

Precision: 0.9695115389543609
Recall: 0.90444
F1 Score: 0.9289472635338991
12 90.842
-----------------------------------------


Train Accuracy: 91.11%
Confusion Matrix:
[[7322  279  175]
 [ 915 6578  283]
 [ 240  182 7354]]
Epoch: 664, Train Loss: 0.64055
-----------------------------------------
Valid Accuracy: 90.45%
Confusion Matrix:
[[87410  6759  2314]
 [  349  2309    90]
 [   23    17   729]]

Precision: 0.9695147989625308
Recall: 0.90

Train Accuracy: 91.18%
Confusion Matrix:
[[7338  263  175]
 [ 915 6578  283]
 [ 239  183 7354]]
Epoch: 683, Train Loss: 0.639812
-----------------------------------------
Valid Accuracy: 90.55%
Confusion Matrix:
[[87512  6650  2321]
 [  335  2309   104]
 [   29    11   729]]

Precision: 0.969684635228399
Recall: 0.9055
F1 Score: 0.9296636672725526
32 90.842
-----------------------------------------


Train Accuracy: 91.18%
Confusion Matrix:
[[7338  263  175]
 [ 917 6578  281]
 [ 241  181 7354]]
Epoch: 684, Train Loss: 0.639787
-----------------------------------------
Valid Accuracy: 90.56%
Confusion Matrix:
[[87526  6636  2321]
 [  335  2309   104]
 [   29    11   729]]

Precision: 0.9696963294669582
Recall: 0.90564
F1 Score: 0.9297535935813015
33 90.842
-----------------------------------------


Train Accuracy: 91.18%
Confusion Matrix:
[[7339  263  174]
 [ 916 6578  282]
 [ 235  187 7354]]
Epoch: 685, Train Loss: 0.639769
-----------------------------------------
Valid Accuracy: 90.

Train Accuracy: 91.23%
Confusion Matrix:
[[7351  253  172]
 [ 915 6578  283]
 [ 233  189 7354]]
Epoch: 702, Train Loss: 0.639179
-----------------------------------------
Valid Accuracy: 91.00%
Confusion Matrix:
[[87965  6271  2247]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9698158142243608
Recall: 0.91003
F1 Score: 0.9324665290812331
0 90.979
-----------------------------------------


##############################################
saved 91.003
##############################################


Train Accuracy: 91.24%
Confusion Matrix:
[[7353  251  172]
 [ 914 6578  284]
 [ 235  187 7354]]
Epoch: 703, Train Loss: 0.639135
-----------------------------------------
Valid Accuracy: 91.00%
Confusion Matrix:
[[87960  6283  2240]
 [  349  2309    90]
 [   38     2   729]]

Precision: 0.9698194460873494
Recall: 0.90998
F1 Score: 0.9324366467235772
0 91.003
-----------------------------------------


Train Accuracy: 91.25%
Confusion Matrix:
[[7354  250  172]
 [ 914 6578  284]
 [ 2

Train Accuracy: 91.28%
Confusion Matrix:
[[7362  245  169]
 [ 917 6578  281]
 [ 248  174 7354]]
Epoch: 721, Train Loss: 0.638619
-----------------------------------------
Valid Accuracy: 91.15%
Confusion Matrix:
[[88108  6143  2232]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9699436202514906
Recall: 0.91146
F1 Score: 0.9333878264969658
9 91.296
-----------------------------------------


Train Accuracy: 91.29%
Confusion Matrix:
[[7363  244  169]
 [ 915 6578  283]
 [ 235  187 7354]]
Epoch: 722, Train Loss: 0.638591
-----------------------------------------
Valid Accuracy: 91.18%
Confusion Matrix:
[[88143  6096  2244]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9699800639856203
Recall: 0.91181
F1 Score: 0.9336175432430396
10 91.296
-----------------------------------------


Train Accuracy: 91.29%
Confusion Matrix:
[[7364  243  169]
 [ 917 6578  281]
 [ 235  187 7354]]
Epoch: 723, Train Loss: 0.638559
-----------------------------------------
Valid Accuracy: 91

Train Accuracy: 91.35%
Confusion Matrix:
[[7378  231  167]
 [ 912 6578  286]
 [ 244  178 7354]]
Epoch: 741, Train Loss: 0.637641
-----------------------------------------
Valid Accuracy: 91.20%
Confusion Matrix:
[[88165  6090  2228]
 [  348  2309    91]
 [   37     3   729]]

Precision: 0.9700262595752458
Recall: 0.91203
F1 Score: 0.9337681558576297
11 91.853
-----------------------------------------


Train Accuracy: 91.35%
Confusion Matrix:
[[7379  230  167]
 [ 914 6578  284]
 [ 241  181 7354]]
Epoch: 742, Train Loss: 0.637629
-----------------------------------------
Valid Accuracy: 91.20%
Confusion Matrix:
[[88165  6090  2228]
 [  349  2309    90]
 [   37     3   729]]

Precision: 0.9700160148170387
Recall: 0.91203
F1 Score: 0.9337639565307644
12 91.853
-----------------------------------------


Train Accuracy: 91.35%
Confusion Matrix:
[[7379  230  167]
 [ 914 6578  284]
 [ 239  183 7354]]
Epoch: 743, Train Loss: 0.637623
-----------------------------------------
Valid Accuracy: 9

-----------------------------------------
Valid Accuracy: 91.42%
Confusion Matrix:
[[88381  5885  2217]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.970202028002782
Recall: 0.91419
F1 Score: 0.9351557075519961
31 91.853
-----------------------------------------


Train Accuracy: 91.38%
Confusion Matrix:
[[7384  225  167]
 [ 917 6578  281]
 [ 247  175 7354]]
Epoch: 762, Train Loss: 0.637418
-----------------------------------------
Valid Accuracy: 91.43%
Confusion Matrix:
[[88396  5870  2217]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9702169385724044
Recall: 0.91434
F1 Score: 0.9352533221828934
32 91.853
-----------------------------------------


Train Accuracy: 91.38%
Confusion Matrix:
[[7385  223  168]
 [ 916 6578  282]
 [ 243  179 7354]]
Epoch: 763, Train Loss: 0.637415
-----------------------------------------
Valid Accuracy: 91.43%
Confusion Matrix:
[[88391  5876  2216]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9702116240324478
Recall: 0.9

Train Accuracy: 91.40%
Confusion Matrix:
[[7389  222  165]
 [ 916 6578  282]
 [ 241  181 7354]]
Epoch: 782, Train Loss: 0.637023
-----------------------------------------
Valid Accuracy: 91.30%
Confusion Matrix:
[[88263  6027  2193]
 [  349  2309    90]
 [   34     6   729]]

Precision: 0.9701288710344075
Recall: 0.91301
F1 Score: 0.934402398961604
52 91.853
-----------------------------------------


Train Accuracy: 91.40%
Confusion Matrix:
[[7389  222  165]
 [ 917 6578  281]
 [ 240  182 7354]]
Epoch: 783, Train Loss: 0.637021
-----------------------------------------
Valid Accuracy: 91.37%
Confusion Matrix:
[[88335  5973  2175]
 [  349  2309    90]
 [   34     6   729]]

Precision: 0.9701930019183879
Recall: 0.91373
F1 Score: 0.9348650994849834
53 91.853
-----------------------------------------


Train Accuracy: 91.40%
Confusion Matrix:
[[7389  223  164]
 [ 917 6578  281]
 [ 238  184 7354]]
Epoch: 784, Train Loss: 0.637014
-----------------------------------------
Valid Accuracy: 91

-----------------------------------------
Valid Accuracy: 91.63%
Confusion Matrix:
[[88588  5779  2116]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9703768436211324
Recall: 0.91626
F1 Score: 0.9364757353880597
72 91.853
-----------------------------------------


Train Accuracy: 91.45%
Confusion Matrix:
[[7402  215  159]
 [ 915 6578  283]
 [ 244  178 7354]]
Epoch: 803, Train Loss: 0.636535
-----------------------------------------
Valid Accuracy: 91.61%
Confusion Matrix:
[[88570  5797  2116]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9703585759020193
Recall: 0.91608
F1 Score: 0.9363584825880885
73 91.853
-----------------------------------------


Train Accuracy: 91.45%
Confusion Matrix:
[[7402  216  158]
 [ 916 6578  282]
 [ 238  184 7354]]
Epoch: 804, Train Loss: 0.63649
-----------------------------------------
Valid Accuracy: 91.58%
Confusion Matrix:
[[88540  5827  2116]
 [  349  2309    90]
 [   39     1   729]]

Precision: 0.9703283001692055
Recall: 0.9

Train Accuracy: 91.50%
Confusion Matrix:
[[7414  206  156]
 [ 917 6578  281]
 [ 233  189 7354]]
Epoch: 823, Train Loss: 0.63606
-----------------------------------------
Valid Accuracy: 91.59%
Confusion Matrix:
[[88557  5814  2112]
 [  333  2309   106]
 [   12    28   729]]

Precision: 0.9707725656084297
Recall: 0.91595
F1 Score: 0.9364445990158072
93 91.853
-----------------------------------------


Train Accuracy: 91.51%
Confusion Matrix:
[[7415  205  156]
 [ 913 6578  285]
 [ 244  178 7354]]
Epoch: 824, Train Loss: 0.635978
-----------------------------------------
Valid Accuracy: 91.57%
Confusion Matrix:
[[88536  5849  2098]
 [  335  2309   104]
 [   10    30   729]]

Precision: 0.9707468886964393
Recall: 0.91574
F1 Score: 0.9363040698485344
94 91.853
-----------------------------------------


Train Accuracy: 91.52%
Confusion Matrix:
[[7417  203  156]
 [ 914 6578  284]
 [ 225  197 7354]]
Epoch: 825, Train Loss: 0.635959
-----------------------------------------
Valid Accuracy: 91

Train Accuracy: 91.53%
Confusion Matrix:
[[7421  200  155]
 [ 916 6578  282]
 [ 243  179 7354]]
Epoch: 843, Train Loss: 0.635588
-----------------------------------------
Valid Accuracy: 91.65%
Confusion Matrix:
[[88608  5795  2080]
 [  334  2309   105]
 [    7    33   729]]

Precision: 0.9708528681040881
Recall: 0.91646
F1 Score: 0.9367836928886935
6 91.893
-----------------------------------------


Train Accuracy: 91.53%
Confusion Matrix:
[[7421  200  155]
 [ 917 6578  281]
 [ 241  181 7354]]
Epoch: 844, Train Loss: 0.635564
-----------------------------------------
Valid Accuracy: 91.65%
Confusion Matrix:
[[88611  5792  2080]
 [  334  2309   105]
 [   16    24   729]]

Precision: 0.9707672740531221
Recall: 0.91649
F1 Score: 0.9367681092028016
7 91.893
-----------------------------------------


Train Accuracy: 91.53%
Confusion Matrix:
[[7421  200  155]
 [ 918 6578  280]
 [ 232  190 7354]]
Epoch: 845, Train Loss: 0.635541
-----------------------------------------
Valid Accuracy: 91.

Train Accuracy: 91.54%
Confusion Matrix:
[[7422  199  155]
 [ 916 6578  282]
 [ 232  190 7354]]
Epoch: 863, Train Loss: 0.635507
-----------------------------------------
Valid Accuracy: 92.00%
Confusion Matrix:
[[88957  5446  2080]
 [  344  2309    95]
 [   35     5   729]]

Precision: 0.9708439556188286
Recall: 0.91995
F1 Score: 0.938914098567387
7 92.273
-----------------------------------------


Train Accuracy: 91.54%
Confusion Matrix:
[[7422  198  156]
 [ 916 6578  282]
 [ 238  184 7354]]
Epoch: 864, Train Loss: 0.635501
-----------------------------------------
Valid Accuracy: 91.94%
Confusion Matrix:
[[88899  5497  2087]
 [  333  2309   106]
 [   29    11   729]]

Precision: 0.9709527560356245
Recall: 0.91937
F1 Score: 0.9386045118759794
8 92.273
-----------------------------------------


Train Accuracy: 91.54%
Confusion Matrix:
[[7423  198  155]
 [ 915 6578  283]
 [ 231  191 7354]]
Epoch: 865, Train Loss: 0.635441
-----------------------------------------
Valid Accuracy: 91.9

-----------------------------------------
Valid Accuracy: 91.85%
Confusion Matrix:
[[88816  5582  2085]
 [  337  2309   102]
 [   36     4   729]]

Precision: 0.9707543547350803
Recall: 0.91854
F1 Score: 0.938016958481927
27 92.273
-----------------------------------------


Train Accuracy: 91.57%
Confusion Matrix:
[[7430  194  152]
 [ 912 6578  286]
 [ 247  175 7354]]
Epoch: 884, Train Loss: 0.635335
-----------------------------------------
Valid Accuracy: 92.47%
Confusion Matrix:
[[89427  4947  2109]
 [  336  2309   103]
 [   39     1   729]]

Precision: 0.9714506332355827
Recall: 0.92465
F1 Score: 0.9420484880246268
28 92.273
-----------------------------------------


##############################################
saved 92.465
##############################################


Train Accuracy: 91.57%
Confusion Matrix:
[[7429  196  151]
 [ 918 6578  280]
 [ 239  183 7354]]
Epoch: 885, Train Loss: 0.635601
-----------------------------------------
Valid Accuracy: 92.13%
Confusion Matri

-----------------------------------------
Valid Accuracy: 91.87%
Confusion Matrix:
[[88830  5576  2077]
 [  334  2309   105]
 [   30    10   729]]

Precision: 0.9708552379266949
Recall: 0.91868
F1 Score: 0.9381417319944431
18 92.465
-----------------------------------------


Train Accuracy: 91.60%
Confusion Matrix:
[[7436  188  152]
 [ 914 6578  284]
 [ 247  175 7354]]
Epoch: 904, Train Loss: 0.634824
-----------------------------------------
Valid Accuracy: 91.78%
Confusion Matrix:
[[88742  5653  2088]
 [  333  2309   106]
 [   10    30   729]]

Precision: 0.970972408459043
Recall: 0.9178
F1 Score: 0.9376513145425244
19 92.465
-----------------------------------------


Train Accuracy: 91.60%
Confusion Matrix:
[[7436  189  151]
 [ 912 6578  286]
 [ 243  179 7354]]
Epoch: 905, Train Loss: 0.634789
-----------------------------------------
Valid Accuracy: 91.84%
Confusion Matrix:
[[88806  5589  2088]
 [  334  2309   105]
 [   30    10   729]]

Precision: 0.9708337164963975
Recall: 0.91

Train Accuracy: 91.61%
Confusion Matrix:
[[7438  186  152]
 [ 916 6578  282]
 [ 231  191 7354]]
Epoch: 924, Train Loss: 0.63469
-----------------------------------------
Valid Accuracy: 91.79%
Confusion Matrix:
[[88753  5630  2100]
 [  334  2309   105]
 [   22    18   729]]

Precision: 0.970860383060202
Recall: 0.91791
F1 Score: 0.9376759634657139
39 92.465
-----------------------------------------


Train Accuracy: 91.61%
Confusion Matrix:
[[7438  186  152]
 [ 915 6578  283]
 [ 246  176 7354]]
Epoch: 925, Train Loss: 0.634669
-----------------------------------------
Valid Accuracy: 92.00%
Confusion Matrix:
[[88963  5448  2072]
 [  348  2309    91]
 [   32     8   729]]

Precision: 0.9708362221846338
Recall: 0.92001
F1 Score: 0.9389458672036993
40 92.465
-----------------------------------------


Train Accuracy: 91.61%
Confusion Matrix:
[[7438  186  152]
 [ 916 6578  282]
 [ 237  185 7354]]
Epoch: 926, Train Loss: 0.634806
-----------------------------------------
Valid Accuracy: 92.

-----------------------------------------
Valid Accuracy: 91.91%
Confusion Matrix:
[[88868  5524  2091]
 [  334  2309   105]
 [    4    36   729]]

Precision: 0.971154314396985
Recall: 0.91906
F1 Score: 0.938494617419837
59 92.465
-----------------------------------------


Train Accuracy: 91.62%
Confusion Matrix:
[[7442  182  152]
 [ 913 6578  285]
 [ 252  170 7354]]
Epoch: 945, Train Loss: 0.634529
-----------------------------------------
Valid Accuracy: 91.84%
Confusion Matrix:
[[88801  5582  2100]
 [  333  2309   106]
 [    4    36   729]]

Precision: 0.9710968210835301
Recall: 0.91839
F1 Score: 0.9380632841801734
60 92.465
-----------------------------------------


Train Accuracy: 91.62%
Confusion Matrix:
[[7442  183  151]
 [ 912 6578  286]
 [ 249  173 7354]]
Epoch: 946, Train Loss: 0.634503
-----------------------------------------
Valid Accuracy: 91.87%
Confusion Matrix:
[[88834  5549  2100]
 [  333  2309   106]
 [    4    36   729]]

Precision: 0.971131632751541
Recall: 0.918

Train Accuracy: 91.62%
Confusion Matrix:
[[7442  182  152]
 [ 916 6578  282]
 [ 254  168 7354]]
Epoch: 965, Train Loss: 0.634733
-----------------------------------------
Valid Accuracy: 91.67%
Confusion Matrix:
[[88631  5764  2088]
 [  333  2309   106]
 [    7    33   729]]

Precision: 0.9708885251785662
Recall: 0.91669
F1 Score: 0.9369395015160535
80 92.465
-----------------------------------------


Train Accuracy: 91.62%
Confusion Matrix:
[[7442  183  151]
 [ 918 6578  280]
 [ 223  199 7354]]
Epoch: 966, Train Loss: 0.634608
-----------------------------------------
Valid Accuracy: 92.24%
Confusion Matrix:
[[89200  5180  2103]
 [  344  2309    95]
 [   39     1   729]]

Precision: 0.9710917461532411
Recall: 0.92238
F1 Score: 0.9405073970991351
81 92.465
-----------------------------------------


Train Accuracy: 91.62%
Confusion Matrix:
[[7442  183  151]
 [ 917 6578  281]
 [ 245  177 7354]]
Epoch: 967, Train Loss: 0.634604
-----------------------------------------
Valid Accuracy: 9

<All keys matched successfully>

In [20]:
Cf.load_state_dict(torch.load('cnn60.pt'))

<All keys matched successfully>

In [21]:
valid_latents = []
VR,VL = [], []
valid_loss = 0.0
for j, (inp, lab) in enumerate(train_loader):
    probability = 0.0
    coin_toss = random.random()  

    if coin_toss < probability:
        continue
    inp = inp.to(device)
    lab = lab.to(device)

    with torch.no_grad():
        # Forward pass
        outp = Cf(inp)

    VR.append(outp)
    VL.append(lab)

VR = torch.cat(VR, dim=0)
VL = torch.cat(VL, dim=0)
_, vpre = torch.max(VR.data, 1)
_, vlbl = torch.max(VL.data, 1)
total = vlbl.size(0)
correct = (vpre == vlbl).sum().item()

vaccuracy = 100 * correct / total
print('-----------------------------------------')
print(f'Train Accuracy: {vaccuracy:.2f}%')
lb = vlbl.cpu().detach().numpy()
pre = vpre.cpu().detach().numpy()
conf_matrix = confusion_matrix(lb,pre)
precision = precision_score(lb, pre,average=avg)
recall = recall_score(lb, pre,average=avg)
f1 = f1_score(lb, pre,average=avg)
print('Confusion Matrix:')
print(conf_matrix)
print()
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print(epochs_without_improvement, best_loss)
print('-----------------------------------------')
print()
print()

valid_latents = []
VR,VL = [], []
valid_loss = 0.0
for j, (inp, lab) in enumerate(valid_loader):
    probability = 0.0
    coin_toss = random.random()  

    if coin_toss < probability:
        continue
    inp = inp.to(device)
    lab = lab.to(device)

    with torch.no_grad():
        # Forward pass
        outp = Cf(inp)

    VR.append(outp)
    VL.append(lab)

VR = torch.cat(VR, dim=0)
VL = torch.cat(VL, dim=0)
_, vpre = torch.max(VR.data, 1)
_, vlbl = torch.max(VL.data, 1)
total = vlbl.size(0)
correct = (vpre == vlbl).sum().item()

vaccuracy = 100 * correct / total
print('-----------------------------------------')
print(f'Valid Accuracy: {vaccuracy:.2f}%')
lb = vlbl.cpu().detach().numpy()
pre = vpre.cpu().detach().numpy()
conf_matrix = confusion_matrix(lb,pre)
precision = precision_score(lb, pre,average=avg)
recall = recall_score(lb, pre,average=avg)
f1 = f1_score(lb, pre,average=avg)
print('Confusion Matrix:')
print(conf_matrix)
print()
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print(epochs_without_improvement, best_loss)
print('-----------------------------------------')
print()
print()

valid_latents = []
VR,VL = [], []
valid_loss = 0.0
for j, (inp, lab) in enumerate(test_loader):
    probability = 0.0
    coin_toss = random.random()  

    if coin_toss < probability:
        continue
    inp = inp.to(device)
    lab = lab.to(device)

    with torch.no_grad():
        # Forward pass
        outp = Cf(inp)

    VR.append(outp)
    VL.append(lab)

VR = torch.cat(VR, dim=0)
VL = torch.cat(VL, dim=0)
_, vpre = torch.max(VR.data, 1)
_, vlbl = torch.max(VL.data, 1)
total = vlbl.size(0)
correct = (vpre == vlbl).sum().item()

vaccuracy = 100 * correct / total
print('-----------------------------------------')
print(f'Test Accuracy: {vaccuracy:.2f}%')
lb = vlbl.cpu().detach().numpy()
pre = vpre.cpu().detach().numpy()
conf_matrix = confusion_matrix(lb,pre)
precision = precision_score(lb, pre,average=avg)
recall = recall_score(lb, pre,average=avg)
f1 = f1_score(lb, pre,average=avg)
print('Confusion Matrix:')
print(conf_matrix)
print()
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print(epochs_without_improvement, best_loss)
print('-----------------------------------------')
print()
print()

-----------------------------------------
Train Accuracy: 91.58%
Confusion Matrix:
[[7432  191  153]
 [ 904 6578  294]
 [ 413    9 7354]]

Precision: 0.9208869784354304
Recall: 0.9158093278463649
F1 Score: 0.9158807273160834
100 92.465
-----------------------------------------


-----------------------------------------
Valid Accuracy: 92.47%
Confusion Matrix:
[[89427  4947  2109]
 [  336  2309   103]
 [   39     1   729]]

Precision: 0.9714506332355827
Recall: 0.92465
F1 Score: 0.9420484880246268
100 92.465
-----------------------------------------


-----------------------------------------
Test Accuracy: 94.02%
Confusion Matrix:
[[150484   6454   2661]
 [   536   2863    112]
 [    54      1    917]]

Precision: 0.9769263505458952
Recall: 0.9401640643093088
F1 Score: 0.954174115431449
100 92.465
-----------------------------------------




In [19]:
 # Iterate over mini-batches
latents = []
train_label = []
for i, (inputs, labels, lbl) in enumerate(train_loader):

    inputs = inputs.to(device)
    lbl = lbl.to(device)
    
    with torch.no_grad():

        # Forward pass
        latent = Encoder(inputs)


    latents.append(latent)
    train_label.append(lbl)


ValueError: not enough values to unpack (expected 3, got 2)

In [ ]:
latents = torch.cat(latents,dim=0)

In [ ]:
train_label = torch.cat(train_label,dim=0)

In [ ]:
latents = latents.cpu().detach().numpy()

In [ ]:
rs = reconstructData(latents)

In [ ]:
torch.argmax(train_label,dim=1)

In [ ]:
labl = torch.argmax(train_label,dim=1).cpu().detach().numpy()

In [ ]:
rs.shape

In [ ]:
real_data_reshaped = np.reshape(latents, (latents.shape[0], -1))


# Perform tsne on real and fake data
perplexity = min(30, real_data_reshaped.shape[0] - 1)
tsne = TSNE(n_components=2, perplexity=perplexity, random_state=seed)
real_tsne = tsne.fit_transform(real_data_reshaped)
label_names = ['No-Movement', 'Small Movement',  'Large Movement']
# Plot the t-SNE visualization with labeled data
plt.figure(figsize=(20, 15))
for label in np.unique(labl):
    indices = np.where(labl == label)
    plt.scatter(real_tsne[indices, 0], real_tsne[indices, 1], label=label_names[int(label)], edgecolors='black')
    
plt.legend()
plt.show()

In [ ]:
-----------------------------------------
Train Accuracy: 91.58%
Confusion Matrix:
[[7432  191  153]
 [ 904 6578  294]
 [ 413    9 7354]]

Precision: 0.9208869784354304
Recall: 0.9158093278463649
F1 Score: 0.9158807273160834
100 92.465
-----------------------------------------


-----------------------------------------
Valid Accuracy: 92.47%
Confusion Matrix:
[[89427  4947  2109]
 [  336  2309   103]
 [   39     1   729]]

Precision: 0.9714506332355827
Recall: 0.92465
F1 Score: 0.9420484880246268
100 92.465
-----------------------------------------


-----------------------------------------
Test Accuracy: 94.02%
Confusion Matrix:
[[150484   6454   2661]
 [   536   2863    112]
 [    54      1    917]]

Precision: 0.9769263505458952
Recall: 0.9401640643093088
F1 Score: 0.954174115431449
100 92.465
-----------------------------------------

In [ ]:
-----------------------------------------
Train Accuracy: 88.61%
Confusion Matrix:
[[6682  954  140]
 [ 945 6710  121]
 [ 435   62 7279]]

Precision: 0.8875690656187784
Recall: 0.8861025377229081
F1 Score: 0.8866658095578258
100 80.479
-----------------------------------------


-----------------------------------------
Valid Accuracy: 80.48%
Confusion Matrix:
[[77819 17188  1475]
 [  763  1940    46]
 [   33    16   720]]

Precision: 0.9603073569758481
Recall: 0.80479
F1 Score: 0.8661478300003829
100 80.479
-----------------------------------------


-----------------------------------------
Test Accuracy: 84.33%
Confusion Matrix:
[[135089  22386   2124]
 [  1087   2374     50]
 [    47     23    902]]

Precision: 0.9683679846076022
Recall: 0.8432673906948964
F1 Score: 0.8945902175201007
100 80.479
-----------------------------------------